### PR TITLE
Enable npm version for specific tag

### PR DESCRIPTION
**Pull request by caseyWebb**
Allows for getting the npm version of a tag by appending `/<tag>` to the url.

screenshot 2017-03-31 14 27 08

[x-ref] #925

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Cool, thanks!

It appears this also fixes #757, as an alternative to #796. Is that correct?

**Comment by caseyWebb** [comment]
This only affect the npm version endpoint, not license. I can make the same change to version if desired, however.

**Comment by paulmelnikow** [comment]
Gotcha.

Since #976 is already open and active as of today, let's keep it there.

I'll test and merge this tomorrow. Thanks!

**Comment by paulmelnikow** [comment]
Thanks so much!

**Pull request merged**
