### PR TITLE
Configure max-age header for frontend

### PR DESCRIPTION
**Pull request by chris48s**
I'll get rid of 12240df and replace it with a pin to a NPM release once we publish an updated package to NPM. Then I'll mark it ready to review.

### CODE REVIEW

**Comment by chris48s** [comment]
I realised the other day that I have push access on the scoutcamp repo and package so I just went ahead and did it. This is ready for review.

**Comment by calebcartwright** [comment]
Am I correct in understanding this is a continuation/final step of https://github.com/badges/sc/pull/3? I've just realized I didn't have my notifications enabled for that repo so have missed all the discussion there

**Review by calebcartwright — APPROVED** [review]
Changes here LGTM, and seems there's an agreement on the SC side so :+1: from me though not sure if there's still ongoing discussions elsewhere :man_shrugging:

**Comment by chris48s** [comment]
Yeah exactly. Sorry probably should have linked that and #5014 in the top post

**Pull request merged**
