### PR TITLE
[Jenkins] Support for Jenkins plugin version

### LINKED ISSUE #622: Support for Jenkins plugin version
Jenkins supports list of the plugins with versions as [JSON](http://updates.jenkins-ci.org/update-center.json) file. It would be great if I can put shield on my README to inform everyone about last release which has been published over Jenkins repository.

This is already supported for many repository so why not Jenkins?

### PR DESCRIPTION
**Pull request by mikkopiu**
Closes #622 

Added simple badge for Jenkins plugins: shows latest version published to Jenkins' repository (fetched from: <https://updates.jenkins.io/update-center.actual.json>).

This uses the URL format: `/jenkins/plugin/v/:pluginId.:format`

Created service-test cases and added under Version in `try.html`.

This is my first contribution here, so let me know if I need to change something.

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Hi! Thanks for this.

This downloads a 1.2M file for every badge. Is there an endpoint with a smaller payload you can use to get the version data?

**Comment by mikkopiu** [comment]
I'm not currently aware of another API/endpoint, but I'll check.

**Comment by mikkopiu** [comment]
Unfortunately Jenkins' Update Center doesn't have a separate JSON API apart from the full list, but it does serve tabular HTML data:

so a (not so pretty) solution could be:

```js
camp.route(/^\/jenkins\/plugin\/v\/([^\/]+)(?:\/(.+))?.(svg|png|gif|jpg|json)$/,
cache(function(data, match, sendBadge, request) {
  var pluginId = match[1];              // e.g. blueocean
  var versionPrefix = match[2] || '';   // e.g. 1.0.0
  var format = match[3];
  var options = {
    method: 'GET',
    headers: { 'Accept': 'text/html' },
    uri: 'https://updates.jenkins.io/download/plugins/' + pluginId
  };
  var badgeData = getBadgeData('plugin', data);
  request(options, function(err, res, data) {
    if (err != null) {
      badgeData.text[1] = 'inaccessible';
      sendBadge(format, badgeData);
      return;
    }
    try {
       // First row is a excess HTML + permalink to latest version,
       // last row is all the excess HTML.
      var versions = data.split("</tr>")
        .slice(1, -1)
        .map(function (row) {
          var cleaned = row.replace('\n', '');
          return cleaned.match(/^<tr>.*>(.*)<\/a>.*$/i)[1];
        });

      var version = versions.find(function(version){
        return version.indexOf(versionPrefix) === 0;
      });
      
      if (!version) {
        throw new Error('unknown version');
      }

      badgeData.text[1] = version;
      if (version === '0') {
        badgeData.colorscheme = 'orange';
      } else {
        badgeData.colorscheme = 'blue';
      }
      sendBadge(format, badgeData);
    } catch(e) {
      badgeData.text[1] = 'not found';
      sendBadge(format, badgeData);
    }
  });
}));
```

Which _works_ but is still parsing HTML in JS and not from an official API, so its stability cannot be guaranteed (although, those plugin download pages have remained identical for quite some time now).

On the positive side, it is much smaller (few kB vs. 1.2MB).

**Comment by paulmelnikow** [comment]
Hmm, yea, parsing the HTML doesn't seem better.

I wish I had a better sense of the memory usage on the server. If we used `regularUpdate` we could just fetch it occasionally. It would keep the whole thing in memory, though that seems like a better bet than fetching it each time.

**Comment by mikkopiu** [comment]
I'll try using the `regularUpdate` (didn't even notice that earlier), and I could just map the JSON to a simple:

```js
var versions = {
  plugin1: '0.1.0',
  plugin2: '1.1.0'
};
```

if memory usage is a concern. That way it wouldn't need to retain the whole, massive Object in memory.

Is there a recommended caching period? Is 1 day too long?

**Comment by paulmelnikow** [comment]
Simplifying the object down is a great idea!

> Is there a recommended caching period? Is 1 day too long?

I'd probably lean toward more like 1 hour. If someone publishes a change they might want to see a change sooner than that even, but a day is a very long time to wait.

**Comment by mikkopiu** [comment]
@paulmelnikow: I switched to `regularUpdate` with a 1 hour cache (should be acceptable considering Jenkins usually only publishes plugin updates once a day), and it is indeed much better. I parsed the original JSON to the format described above, so it shouldn't really use any considerable amount of memory.

I had to switch all tests to use mocked data as they would otherwise timeout constantly (the original payload is so big). 

I also added the orange colouring for alpha and beta versions.

**Comment by paulmelnikow** [comment]
Excellent!

I think it would be good to include a test that hits the real service. There's an open PR MarkHerhold/IcedFrisby#71 to allow overriding the timeout on a case-by-case basis. Since that isn't merged yet, maybe you could add the test and comment it out?

Temporarily while you're testing, you could override Mocha's global timeout.

```js
mocha.setup({ timeout: 10000 });
```

**Comment by mikkopiu** [comment]
The two tests that should hit the actual API, consistently go over 10s each, and even 20s quite regularly. Is something like a 30s timeout even reasonable?

**Comment by paulmelnikow** [comment]
Ooph, well that's not great, though I think it's okay. Really glad we're caching these!

If it's taking that long and Jenkins only updates once a day, maybe we should set our timeout to something longer, like 4 hours.

**Comment by paulmelnikow** [comment]
Hey, I just wanted to follow up on this. Since Jenkins only updates once a day, should we set our timeout to something longer, like 4 hours? As an alternative to a test with a 30 second timeout, you could add a test with a small example in a fixture, using `intercept()`.

**Comment by mikkopiu** [comment]
Yeah, sorry for taking so long, I'll set the timeout to 4 hours (seems reasonable even for couple-of-times-a-day releases).

For `intercept`, I'm not sure what you mean? Do you mean mocking out the backend (instead of increasing the test timeout unreasonably high), like what I've currently done in this PR?

**Comment by paulmelnikow** [comment]
My bad, I realize you are already using `.intercept()`. Let's leave it at that for now.

If we start getting reports that these are failing, let's add a slow test that pulls the real data, so that we find out about the problems first.

**Comment by paulmelnikow** [comment]
Thanks!

**Pull request merged**
