### PR TITLE
set expires header corresponding to maxAge

### LINKED ISSUE #1650: Problem with maxAge parameter
If I set maxAge=3600 then it set Cache-Control header correctly but it doesn't set Expires header accordingly that make it useless (instead it is set to a past date, by some seconds).

> Responding with a past date in the Expired header (earlier than the Date header value) makes no sense and would be a sign of some serious misconfiguration. That being said, clients would treat such response as "already expired" and not cache it. Same applies if Expires date is equal to Date header value (which is the correct way of server marking the response as "already expired") or having an invalid format.

### PR DESCRIPTION
**Pull request by RedSparr0w**
closes #1650
currently when using `?maxAge=` the `cache-control` header is set correctly but the `expires` header is always set to the current time.

### This PR:
```text
Cache-Control: max-age=3600
Date: Mon, 16 Apr 2018 21:57:47 GMT
Expires: Mon, 16 Apr 2018 22:57:47 GMT
```
### Current:
```text
cache-control: max-age=3600
date: Mon, 16 Apr 2018 21:55:33 GMT
expires: Mon, 16 Apr 2018 21:55:33 GMT
```

### CODE REVIEW

**Comment by RedSparr0w** [comment]
Probably a good idea, although i'm really not sure how to test the headers.

------------
Also according to [RFC 2616 on W3](https://www.w3.org/Protocols/rfc2616/rfc2616-sec13.html#sec13.2.4)

>The max-age directive takes priority over Expires, so if max-age is present in a response, the calculation is simply:
&nbsp;&nbsp;&nbsp;&nbsp;`freshness_lifetime = max_age_value`
>Otherwise, if Expires is present in the response, the calculation is:
&nbsp;&nbsp;&nbsp;&nbsp;`freshness_lifetime = expires_value - date_value`

So this PR may actually be pointless?

**Comment by RedSparr0w** [comment]
Have added some tests if you could please give it another look over @platan

**Comment by ale5000-git** [comment]
> So this PR may actually be pointless?
It may be pointless in a perfect world but different implementations take different approach, there will always be someone not following the spec or maybe also not supporting Cache-Control but supporting Expires.

**Comment by ale5000-git** [comment]
Deploy status

**Pull request merged**
