### PR TITLE
Update GitLab logo (2022)

### PR DESCRIPTION
**Pull request by tnir**
Updates GitLab logo.

GitLab logo was updated on 2022-04-27 by https://github.com/GitLab: https://about.gitlab.com/blog/2022/04/27/devops-is-at-the-center-of-gitlab/

Note that https://github.com/gitlabhq updated its icon, but https://github.com/GitLab did not.

## Checklist
- [x] Minimize SVG files through SVGO
- [x] Set a viewbox and ensure the logo is scaled to fit the viewbox, while preserving the logo's original proportions. This means the icon should be touching at least two sides of the viewbox.
- [x] Ensure the logo is vertically and horizontally centered.
- [x] Ensure the logo is minified to a single line with no formatting.
- [x] Ensure the SVG does not contain extraneous attributes.
- [x] Ensure your submission conforms to any relevant brand or logo guidelines.

> Minimize SVG files through SVGO
```
$ svgo --precision=3 logo/gitlab.svg

gitlab.svg:
Done in 50 ms!
0.981 KiB - 1.9% = 0.963 KiB
```

from https://github.com/badges/shields/blob/e94b9c104707da81f1e01451d59695905772a5db/doc/logos.md

Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>

### Note
These PRs did not help updating the logo:

- https://github.com/simple-icons/simple-icons/pull/7364
- https://github.com/badges/shields/pull/7946

### cf.

- https://github.com/github/explore/pull/3059

### CODE REVIEW

**Comment by calebcartwright** [comment]
think we should proceed with this in the same vein as #7831

**Review by calebcartwright — APPROVED** [review]
this lgtm but i'll hold off on merging in case another maintainer wants to weigh in

**Review by chris48s — CHANGES_REQUESTED** [review]
Agree with changing the logo, but can you make sure the new logo has been minified in line with our image contribution guidelines: https://github.com/badges/shields/blob/master/doc/logos.md#contributing-logos

**Comment by tnir** [comment]
@chris48s Updated.

**Review by chris48s — APPROVED** [review]

**Comment by tnir** [comment]
Thanks @chris48s!

**Pull request merged**
