### PR TITLE
Add Favicons (high res)

### LINKED ISSUE #1497: Provide high resolution favicon
Currently the `shields.io` favicon is low resolution only.

But current browsers like Firefox use big logo information in their top visites sites section.
There is also no image support for links placed on mobile homescreens (android +ios).

On basically all high resolution screens the operating system has to scale things up so it gets even worse.

### PR DESCRIPTION
**Pull request by jaas666**
Fix #1497... 

🤞hopefully it works now, at least all test passed locally

### CODE REVIEW

**Comment by jaas666** [comment]
I would have liked to make the files available in some folder and simply add links to the files instead of importing them but couldn't find how to do it. If anyone knows and can give me hand I'd be more than willing to resubmit

**Comment by calebcartwright** [comment]
Thanks for sticking with it! This seems to be in good order to me, but I'm going to hold off on merging so that some of the more UX minded/skilled maintainers can weigh in

**Comment by jaas666** [comment]
Perfect, thanks.

**Comment by calebcartwright** [comment]
@paulmelnikow assuming this is one you'd want to based on discussion in the linked issue and prior PR, but let us know if that's not the case and/or if you don't have bandwidth at this time

**Comment by jaas666** [comment]
Yes.. I started from scratch to make it work. Couldn't get previous PR to work.

**Comment by jaas666** [comment]
Is there something wrong ?

**Comment by calebcartwright** [comment]
> Is there something wrong ?

No, at least not necessarily. It's just that the best folks to review this haven't had the bandwidth to do so yet. Please sit tight, and thanks again for your patience and contribution!

**Comment by jaas666** [comment]
Got it
 No problem.

**Pull request closed without merging**
