### PR TITLE
Refactor - use renderVersionBadge - part 3 [luarocks gitlab nuget feedz]

### PR DESCRIPTION
**Pull request by jNullj**
This pull request refactors the codebase to use the `renderVersionBadge` function for rendering version badges.
Refactored services are luarocks, gitlab, feedz and nuget.
The pull request also modifies tests where needed.
This change is part of the ongoing work to address issue #2026 - refactor all versions to use  `renderVersionBadge`
And also helps archive user override for version prefix as mentioned in #10574

Additionally, the scm and cvs versions are now included as previews in the renderVersionBadge function project-wide.
And a comment was added to clojars to make it clear it uses non-standard style while pointing to relevant PR and commit.

The only services left for the next part are found using this regex first to see if all imports belong to version.js
`imports import\s*(?:[ \n\t]*(?:[^ \n\t\{\}]+[ \n\t]*,?)?\s*\{[^}]*\brenderVersionBadge\b[^}]*\})?\s*from\s*(['"])([^'"\n]+)\1`
Then i used `grep -rl "category = 'version'" . | xargs grep -L "renderVersionBadge"` to find all missing `renderVersionBadge` usages for badges in the versions category.

which only leaves
```
./services/visual-studio-app-center/visual-studio-app-center-releases-osversion.service.js
./services/github/github-release.service.js
./services/github/github-tag.service.js
```

`visual-studio-app-center-releases-osversion` uses os minimum versions so its not relevant.

### CODE REVIEW

**Review by PyvesB — APPROVED** [review]
Changes look good to me! Switching to `renderVersionBadge` will modify colors in some cases, but I don't think the colors in these badges were ever motivated by vertical consistency with the upstream service; consequently improving horizontal consistency across Shields.io badges is a good thing.

**Comment by robaho** [comment]
Hi @PyvesB - is there a reason `maven-central` was not included in the list of services that should be updated to use renderVersionBadge?

**Comment by jNullj** [comment]
> Hi @PyvesB - is there a reason `maven-central` was not included in the list of services that should be updated to use renderVersionBadge?

`maven-central` is a redirector to `maven-metadata` which uses `renderVersionBadge` since 2021.

**Comment by robaho** [comment]
@jNullj That doesn't appear to be the case in the code repo, but regardless, I tried using maven-metadata and still the prefix is not passed through and rendered. I think this is the correct url:

```
https://img.shields.io/maven-metadata/v?metadataUrl=https://repo1.maven.org/maven2/io/github/robaho/httpserver/maven-metadata.xml&prefix=X
```

It is rendered with the `v` not the `X`.

**Comment by jNullj** [comment]
@robaho Thank you for clarifying, I think i better understand now what you find missing.
This PR only adds the prefix param to `renderVersionBadge`, this is internal code. For the prefix to show as a badge param we still need to add it to the badges.
I did an attempt at https://github.com/badges/shields/pull/10685 but ended up closing the PR.
To better understand why prefix was not added please make a quick read for that PR.
Please continue discussion regarding the prefix feature in the related PR/issues, as this PR is for making the code more consistent and easier to maintain and not for adding the new user facing feature, this is a refactor, i only mentioned it here as i made it easier to implement in the future.

**Pull request merged**
