### PR TITLE
Fix enlarged text when min-font-size is enabled

### LINKED ISSUE #746: In Windows Firefox, labels and status text in badges overlap and push outside boundaries
Here are a few examples from [shields.io](http://shields.io/) website, to illustrate whats happening in projects Im involved in, clearly this is now a global issue.

[bitHound]()  
[Gem]()  
[Crates.io]()  
[MyGet tenant]()  
[MyGet tenant]()  
[David]()  
[CocoaPods]()

Would you guys consider adding padding to left and right of label portion and left and right of status portion?

### LINKED ISSUE #848: SVG layout when a minimum font size is enforced
I use my browser's minimum font size setting to prevent sites from using unreadable font sizes. Unfortunately it has this effect on shields.io SVG badges:

firefox_2017-01-05_19-31-57

Is there something which could be done to make SVG badges scale instead of squishing text like this?

### PR DESCRIPTION
**Pull request by RedSparr0w**
Fixes #746 
Fixes #848 

Works by making the font-size `110px` instead of `11px` so the browser doesnt enforce the minimum font size and then scales the text down to 10%.

Also fixes the padding issue on Firefox

Tested on the following:

Browser | Version | Status
:-- | :-- | :--:
Chrome | 61.0 | working
Firefox | 56.0 | working
Edge | 25 | working
IE | 11 | working
Mobile Safari | 9.3 | working

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Oh my gosh, what a brilliant workaround! I love it! 🍻 

I made this test page with two example images. Let's just be double-sure it fixes the problem! 😁 

http://whois.paulmelnikow.com/extra/1132.html

**Comment by RedSparr0w** [comment]
Working fine on Safari - iOS 9.3

Not sure I can set a minimum font size though but the text shrinks correctly 👍

Sent from my iPhone

On 6/10/2017, at 10:00 AM, Paul Melnikow <notifications@github.com<mailto:notifications@github.com>> wrote:


Oh my gosh, what a brilliant workaround! I love it! 🍻

I made this test page with two example images. Let's just be double-sure it fixes the problem! 😁

http://whois.paulmelnikow.com/extra/1132.html

**Comment by the-j0k3r** [comment]
My 2c on https://github.com/badges/shields/issues/746#issuecomment-334607980

this works...

**Comment by RedSparr0w** [comment]
Might pay to test the other styles aswell,
90% sure they are all okay, but just to be 100%!

**Comment by the-j0k3r** [comment]
The only thing Ill add is, when these shields and others that have a longer strings of text inside either part is that the space between the text and the left or right edge is really too close for comfort, so maybe consider adding a bigger buffer to increase legibility in those cases too.

e.g. 
[Ansible Role]()

[CocoaPods]()

[GitHub issue label]()

Some like appveyor really can throw bigger strings into right side.

**Comment by RedSparr0w** [comment]
those ones show up fine for me on edge/chrome:
image
But on firefox i get the padding issue:
image

**Comment by the-j0k3r** [comment]
> But on firefox i get the padding issue:

mm, mm 💬 😯

**Comment by paulmelnikow** [comment]
It looks like a letter spacing problem. Do you want to try setting the [letter-spacing attribute](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/letter-spacing) on the `<text>` elements to 0 and seeing if that fixes it?

**Comment by RedSparr0w** [comment]
Tried, but nothing unfortunately

Apparently:
>The letter-spacing attribute is poorly supported in SVG. As of May 2016, Firefox renders text exactly the same regardless of letter-spacing. Chrome does render text with spaced letters, but improperly computes the text length; textNode.getComputedTextLength() returns exactly the same length whether letter-spacing is set or not, producing grossly incorrect results when letters are spaced.

**Comment by RedSparr0w** [comment]
If i make the text 1 (or 10 in this PR) smaller it seems to align better on Firefox but screws up Chrome

Firefox | Chrome
:-- | :--
image | image

**Comment by RedSparr0w** [comment]
The problem also existed in chrome <=58 but shows fine in v59 so something changed that fixed it..
[View in Chrome v58](https://browserling.com/browse/win/7/chrome/58/http%3A%2F%2Fimg.shields.io%2Fansible%2Frole%2F3078.svg)
[View in Chrome v59](https://browserling.com/browse/win/7/chrome/59/http%3A%2F%2Fimg.shields.io%2Fansible%2Frole%2F3078.svg)

**Comment by RedSparr0w** [comment]
Think i may have fixed it 🤞
image

**Comment by paulmelnikow** [comment]
This seems to work in my testing as well.

@RedSparr0w thank you so much for addressing this long-standing issue! 🌟

**Comment by paulmelnikow** [comment]
Hmm, I've noticed that the letter spacing now looks different on my machine. It seems like `textLength="{{=(it.widths[1]-8)*10}}" lengthAdjust="spacing"` is responsible. Could you look into it a bit?

master:

screen shot 2017-10-11 at 10 18 29 am

production:

screen shot 2017-10-11 at 10 18 24 am

**Comment by paulmelnikow** [comment]
Flat badges with logos aren't rendering correctly either.

master:

screen shot 2017-10-11 at 10 22 21 am

production:

screen shot 2017-10-11 at 10 22 17 am

What do you think about removing the letter spacing adjustment to give us some time to sort this out? I like the master branch to be ready to deploy at any time, and don't feel comfortable deploying what's there now.

It might be good, also, to get some browser-based tests of these badges in place. Even some manual tests. Maybe we could use something like Netlify (#960).

**Comment by the-j0k3r** [comment]
> Hmm, I've noticed that the letter spacing now looks different on my machine. It seems like textLength="{{=(it.widths[1]-8)*10}}" lengthAdjust="spacing" is responsible. Could you look into it a bit?
> 
> master:
> 
> screen shot 2017-10-11 at 10 18 29 am
> 
> production:
> 
> screen shot 2017-10-11 at 10 18 24 am


@paulmelnikow for my money master letter spacing is more legible, considering that the whole badge is so small and the font inside it is even smaller.

When people with UHD screens / 2K and Up you may as well grab some binoculars.

By reverting it, you made it worst imo.

**Comment by paulmelnikow** [comment]
As you can see in this image, the letter spacing is now really inconsistent across badges.

screen shot 2017-10-11 at 1 22 03 pm

They go against [our own badge specification](https://github.com/badges/shields/blob/master/spec/SPECIFICATION.md) and our goal of providing consistent and attractive. IMO the inconsistent letter spacing makes them _less_ legible.

Because of the way SVG works, we can't make the badge size dynamic or adjustable in the browser. It sounds like you want the badges to be bigger, with larger text and more spacing. I hear that, and I'm sorry we can't do what you want without affecting everyone else.

The intent of the PR was not to change the letter spacing on all browsers, but to improve the visual appearance on Windows Firefox.

**Comment by RedSparr0w** [comment]
Just pushed another commit,
I fixed the spacing when there is a logo on the image,
Also think i may have made the badge fit the spec now:
image
The problem should exist in current badges aswell (for the label only) as the `x` position is calculated as the middle of the width of the left side instead of `(width/2)+1` to give 6 px on the left and 4px on the right.

I originally didn't account for the total padding of 10px (the correct amount) i for some reason thought it was 4px each side.
Heres some test:

This PR | Production
:---: | :---:
image | image
image | image
image | image
image | image
image | image
image | image
image | image

**Notes:**
* the Codetally badge shows up weird because for some reason it has an [extra space at the beginning](https://github.com/badges/shields/blob/master/server.js#L1114), should probably strip all outer spaces at some point in another PR
* the gem badge (rank) also has extra width due to when the width is calculated it counts the `ᵗʰ` as being a standard `th`
* no idea whats up with the `social` badge, not sure what the spec is supposed to be with those.

**Comment by the-j0k3r** [comment]
> They go against our own badge specification and our goal of providing consistent and attractive. IMO the inconsistent letter spacing makes them less legible.

Understood, its just sometimes I wish the font size could be bigger, especially badges that have longer string sometimes it takes effort on 2k screen to read. But if trade off is broken badges then best stick with what works.

**Comment by RedSparr0w** [comment]
depending where you are hosting the badge you could scale the badge up a bit in size,
for example:
```
<img src="https://img.shields.io/github/issues-raw/badges/shields.svg" height="40"></img>
```
</img>

**Comment by the-j0k3r** [comment]
@RedSparr0w nice one, thanks for tip, have to figure it out and play around in the project readmes.

Are there any more hidden knobs and dials?

**Comment by the-j0k3r** [comment]
@RedSparr0w managed to do the appveyor one with `<a href="link/to/service/branch"> </img></a>`

I used ?Label="some-label" also but would be nice to do both in markdown...

In any case its a 👍 for sure 🛐

**Pull request merged**
