### PR TITLE
Revert "Use old.stats.jenkins.io for JSON data"; test [jenkins]

### LINKED ISSUE #10534: Update Jenkins Plugin Installs for new stats.jenkins.io
:clipboard: **Description**

Refs https://github.com/badges/shields/pull/10522

As a stop-gap we are using old.stats.jenkins.io but this will be retired at some point.

It looks like a feature allowing us to grab machine-readable data from the new stats.jenkins.io will be introduced. Once that happens, we update our code to use that instead.

### PR DESCRIPTION
**Pull request by chris48s**
Closes #10534

### CODE REVIEW

**Comment by chris48s** [comment]
Hmm, so it seems the "404" response from stats.jenkins.io (e.g: https://stats.jenkins.io/plugin-installation-trend/not-a-plugin.stats.json ) is actually served with a `200 OK` status code.

**Comment by chris48s** [comment]
For the moment, I've raised an issue on
https://github.com/jenkins-infra/helpdesk/issues/4291
If old.stats.jenkins.io goes away before that is resolved, there's a couple of possible options:

1. Accept the "not found" message for this service is "unparseable json response" and update the tests.
2. Switch this badge to make a raw call to `_request()` instead of `_requestJson()`. If we get back a 200 OK with a HTML body, assume that is a "not found" response. Otherwise, parse it as JSON.

**Comment by PyvesB** [comment]
Slight preference for option 2.

**Comment by chris48s** [comment]
This has now been fixed upstream

**Comment by chris48s** [comment]
Given this got solved upstream, I'm just going to go ahead and merge this one

**Pull request merged**
