### PR TITLE
Add Bitcoin + PayPal Logo

### PR DESCRIPTION
**Pull request by HiramLevitch**
Bitcoin design by @ecogex
PayPal design by @paypal

### CODE REVIEW

**Comment by HiramLevitch** [comment]
Can you help me with the @paypal logo @espadrine please?

I plan to use those badges in READMEs to get donations.
Examples:
[https://github.com/php-telegram-bot/core](https://github.com/php-telegram-bot/core)
[https://github.com/patharanordev/donate-in-git](https://github.com/patharanordev/donate-in-git)
[https://github.com/bevry/projectz](https://github.com/bevry/projectz)
[https://github.com/gabrielecirulli/2048](https://github.com/gabrielecirulli/2048) (Donation paragraph at the end of the Readme)
[https://github.com/mgibas/paper-rating](https://github.com/mgibas/paper-rating) (uses a [Gitcheese](https://www.gitcheese.com/) badge made by @mgibas and many others)
[https://github.com/bitfireAT/davdroid](https://github.com/bitfireAT/davdroid)
[https://github.com/jahirfiquitiva/IconShowcase-Dashboard](https://github.com/jahirfiquitiva/IconShowcase-Dashboard) (uses a [Patreon](https://www.patreon.com/bePatron?u=5261073) badge)

**Comment by paulmelnikow** [comment]
@RedSparr0w would you mind reviewing this?

**Comment by RedSparr0w** [comment]
Just wondering where you found the PayPal logo,
I cant seem to find it anywhere.

Looks okay on the `social` style badge:
image
But blends into the background on the others:
image

Some other options would be:
Their [black logo](https://github.com/paypal/paypal-checkout/blob/master/src/components/button/templates/component/logos/pp_black.svg):
image
and the [white logo](https://github.com/paypal/paypal-checkout/blob/master/src/components/button/templates/component/logos/pp_white.svg) for `flat` & `flat-square` & `for-the-badge` & `plastic` style badges:
image
Or maybe just the [blue logo](https://github.com/paypal/paypal-checkout/blob/master/src/components/button/templates/component/logos/pp_blue.svg) which shows well on all the badges:
image
image

Bitcoin logo looks good as is:
image
image
image

Lastly could you also run them both through [svgomg](https://jakearchibald.github.io/svgomg/) to [minimize](https://github.com/badges/shields/blob/master/CONTRIBUTING.md#logos) them.

**Comment by HiramLevitch** [comment]
Thanks for your help @RedSparr0w! 👍
Both logos are minimized now and I uploaded the blue PayPal version.

**Comment by RedSparr0w** [comment]
Thanks looks good.

@paulmelnikow Before i merge can you confirm if the logo should be centered or aligned to the left when the height is greater than the width?
@HiramLevitch  If it should be centered you should only need to change `xMinYMin` &rarr; `xMidYMid`

Top is left aligned & bottom is center aligned
image
image

Enlarged for slightly more noticeable difference
image
image

If the badge is left aligned it matches the spec more (4px margin on left side) but IMO looks better centered.

**Comment by paulmelnikow** [comment]
@RedSparr0w I trust your judgement on this! Would be great to add some logo guidelines to the spec at some point.

**Comment by RedSparr0w** [comment]
@paulmelnikow Thanks, think ill keep them all centered for now then, until we come up with a guideline for the logos.

**Comment by RedSparr0w** [comment]
@HiramLevitch Could you please change `xMinYMin` → `xMidYMid` on the PayPal logo and then i can get this merged!
👍

**Comment by HiramLevitch** [comment]
Done. Thanks for your help @RedSparr0w!

**Comment by RedSparr0w** [comment]
👍 
Thanks for your contribution!

image
image

**Comment by SusanKenneth** [comment]
How does the Markdown look like which I need for the PayPal & Bitcoin badge, @RedSparr0w?

**Comment by RedSparr0w** [comment]
@SusanKenneth You should just need to add `?logo=bitcoin` or `?logo=paypal` to the end,
eg: `https://img.shields.io/badge/Bitcoin-Donate-orange.svg?logo=bitcoin`

But it doesn't look like the master branch has been merged into the live version yet,
The live page was updated 12 November, you can check [here](https://github.com/badges/shields/tree/gh-pages) for when it was merged with the master branch last.

**Pull request merged**
