### PR TITLE
added clojars downloads count

### LINKED ISSUE #1152: [Request] Add clojars downloads badge
Would be awesome to get clojars downloads.

### PR DESCRIPTION
**Pull request by flyboarder**
Add Clojars Downloads Count Badge

Closes #1152 

Does not include tests, can someone help with that?

### CODE REVIEW

**Comment by platan** [comment]
Here is a tutorial how to write and run service tests https://github.com/badges/shields/tree/master/service-tests#readme. And there is a lot of existing tests in https://github.com/badges/shields/tree/master/service-tests directory. Does it help you?

**Comment by paulmelnikow** [comment]
For this to be merged, it will need:
- [ ] Service tests
- [ ] Additions made to `all-example-badges.js`
- [ ] A new URL. If it's total downloads, probably it should be `/dt` to leave room for expansion.

**Comment by paulmelnikow** [comment]
@flyboarder Just wanted to follow up. Are you able to address these items? If not, no worries, someone else could come along later and take care of it.

**Comment by flyboarder** [comment]
@paulmelnikow I have not had time to look at this recently, I think I can solve all those items once I get a chance.

**Comment by paulmelnikow** [comment]
Hey @flyboarder feel free to reopen this when you have the time!

**Pull request closed without merging**
