### PR TITLE
PR for Docker Hub Automated Builds

### PR DESCRIPTION
**Pull request by jrottenberg**
badges/shields#241

Query https://registry.hub.docker.com/v2/repositories/USER/IMAGE/ to get the boolean 'is_automated'

'automated build' for the left part, 'docker automated' or 'docker automated build' didn't sound as good.

### CODE REVIEW

**Comment by jrottenberg** [comment]
Maybe 'docker build' on the left, with 'automated' or 'manual' on the right would work better. Let me know.

**Comment by espadrine** [comment]
Thanks for your contribution!

> Maybe 'docker build' on the left, with 'automated' or 'manual' on the right would work better.

You are absolutely right! It would be lovely.

**Comment by jrottenberg** [comment]
Great, let me know if it's merge-able now.

**Comment by tclarke** [comment]
Any eta on merge and deploy for this PR? Can't wait to use it!

**Comment by hairyhenderson** [comment]
Nice! Would be good to see this in - is there anything blocking this getting merged, @espadrine?

**Comment by seblegall** [comment]
Hi,

Any news of this PR? I will be glad to be one of the first to use this badge :-)

**Comment by jakirkham** [comment]
Are we sure this is working? I can't seem to see the badges when previewing the HTML.

**Comment by espadrine** [comment]
Thanks for the contribution!

Unfortunately, I am not in the greatest situation to push to production. I hope to push this change live this week-end.

**Pull request merged**
