### PR TITLE
Docker imagelayers

### PR DESCRIPTION
**Pull request by jrottenberg**
- size are for the compressed layers - docker/hub-feedback#331 docker/hub-feedback#242
- layers are for the actual image, regardless of the parent (ignoring the layers comming from the FROM)

I've added _docker/layer_ and _docker/size_ to the route , so we can deprecate _imagelayers_ prefix safely.

It's another resolution for #712

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Hi, thanks for this contribution. There's quite a backlog of PRs we're working through. Sorry it's taken so long to respond.

Since #712 was resolved with a change to a port number, imagelayers is back online. I'm wondering if we should pick one service and centralize, as this badge has done, or keep both badges around. Any thoughts on that?

Would you be willing to add tests using the project's [new testing framework](https://github.com/badges/shields/tree/master/service-tests)?

**Comment by paulmelnikow** [comment]
@jrottenberg if you have time, please address these comments and add tests. Also, if anyone would like to adopt this PR, please feel free to do so: grab the branch, add more commits addressing the comments, and open a new PR referencing this one. Will close in one month if no one has.

**Comment by paulmelnikow** [comment]
If anyone would like to adopt this PR, please feel free to do so: grab the branch, add more commits addressing the comments, and open a new PR referencing this one.

**Comment by jrottenberg** [comment]
Oh yeah forgot about that one, if imagelayer does the job, and it does after #712 no reason to change layer details provider ;-)

**Pull request closed without merging**
