### PR TITLE
Fix [AzureDevOps] branch specific badges

### LINKED ISSUE #2774: Azure Devops Test Badge always refers to latest build
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**
The Azure DevOps badge always shows test results of latest build, even if this build not refers to the configured branch.

:link: **Link to the badge**

https://img.shields.io/azure-devops/tests/jopohl/urh/2/master.svg

Note, badge says 2176 tests passed while this should truly be 2720. The number 2176 comes from a build which was made on another branch. Overview of builds is here: https://dev.azure.com/jopohl/urh/_build?definitionId=2

:bulb: **Possible Solution**
Configured branch should be evaluated to get test results from latest build on branch and not latest build overall.

### PR DESCRIPTION
**Pull request by calebcartwright**
Fixes #2774 (the underlying API changed the query param name from `branch` to `branchName`)

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Do you think it's worth mentioning in the doc that `/refs/heads/whatever` can be specified as `whatever`?

**Comment by paulmelnikow** [comment]
Are you sure we should bother to support both ways? If we don't support "with" `/refs/heads/` we can always add it if someone complains.

**Comment by calebcartwright** [comment]
Doesn't matter to me either way so I'll change it. Definitely more important to get the fix out so the branch filter will actually work than supporting fancy branch naming patterns!

**Comment by paulmelnikow** [comment]
I was a little preoccupied with the color bugs the last day or so. There was a lot of code moving! 😝

**Comment by calebcartwright** [comment]
> I was a little preoccupied with the color bugs the last day or so. There was a lot of code moving! 😝

I was thinking more along the lines of... why did I add that in the first place? 🤣

**Pull request merged**
