### PR TITLE
[New badge] Bitbucket open pull requests

### PR DESCRIPTION
**Pull request by chapulina**
See issue #789.

shield

### CODE REVIEW

**Comment by hugomatic** [comment]
+1

**Comment by andrejsc** [comment]
This PR is great, but has no support for [app passwords](https://blog.bitbucket.org/2016/06/06/app-passwords-bitbucket-cloud/).

**Comment by chapulina** [comment]
That's true. It was added following the existing code for Bitbucket issues, and is focused on publicly accessible repositories.

**Comment by espadrine** [comment]
Thanks a lot for this contribution!

Merged as 976e5f2.

I changed the API a bit to be shorter and closer to the equivalent one for GitHub: eg. https://img.shields.io/bitbucket/pr-raw/osrf/gazebo.svg. If you are fine with it, I'll update the website.

**Comment by chapulina** [comment]
The new API looks good to me, thanks for merging!

**Pull request closed without merging**
