### PR TITLE
Add Azure DevOps logo

### PR DESCRIPTION
**Pull request by aalmada**

### CODE REVIEW

**Comment by aalmada** [comment]
I think it now follows the guidance for logo submissions. Azure DevOps is one of the supported CI platforms and the logo was minimised using svgomg.

**Comment by chris48s** [comment]
Nice one. Thanks for minifying. Do you think it would be better to make the default logo white so it pops a bit more on the default background:




White seems to be an approved colour for the logo: https://twitter.com/azuredevops?lang=en

**Comment by aalmada** [comment]
I can change it to white but please note that most logos in that folder are in their original colors. The color can be changed using the _logoColor_ parameter. 
For example, the GitHub logo is black at https://github.com/badges/shields/blob/master/logo/github.svg but I'm using it in light gray at https://github.com/NetFabric/NetFabric.DoubleLinkedList/blob/master/README.md

**Comment by chris48s** [comment]
@RedSparr0w - do you have an opinion on this one?

**Comment by paulmelnikow** [comment]
It's hard to imagine anyone wanting blue on gray; it doesn't seem like the best default. For what it's worth, the GitHub logo is dark because it was originally designed for the static badge, which has a light background. If white is an approved color, my vote is for that, at least until we add something like #2431.

**Comment by calebcartwright** [comment]
FWIW - the default logo color is white for the Azure Pipelines badge (although it is a different logo) 

https://github.com/Microsoft/vscode#visual-studio-code---open-source
image

**Comment by RedSparr0w** [comment]
I think we should try to defer all icons to [simple-icons](https://github.com/simple-icons/simple-icons).
And if they do not accept it or it doesn't fit their spec for whatever reason then open one here.
What are your thoughts? @paulmelnikow @chris48s 

Otherwise if we are going to be merging this PR, i agree the white works better.

**Comment by paulmelnikow** [comment]
> I think we should try to defer all icons to [simple-icons](https://github.com/simple-icons/simple-icons).

I agree, I don't see a real advantage to keeping our own collection of icons.

So that we don't string along @aalmada, I might suggest:

1. Merge this with white.
2. Modify our logo guidelines to say we are no longer accepting new logos
3. Match up our existing logo collection with simple-icons, and get our existing logos matched in there. Maybe in the process, one of us could ask to join as a co-maintainer.
4. Remove our existing logos, leaving aliases in place for if needed for backward compatibility.

**Comment by aalmada** [comment]
White it is then... :)
Commits are all squashed to a single one.

**Pull request merged**
