### PR TITLE
Add GitLab logo

### PR DESCRIPTION
**Pull request by doniyor2109**

### CODE REVIEW

**Comment by RedSparr0w** [comment]
Thanks for submitting this PR.
Could you also run the logo though [this](https://jakearchibald.github.io/svgomg/) to [minimize the file](https://github.com/badges/shields/blob/master/CONTRIBUTING.md#logos)?

**Comment by paulmelnikow** [comment]
@doniyor2109 Just following up. Would you be able to address @RedSparr0w's request?

**Comment by doniyor2109** [comment]
Yes @paulmelnikow. Theses days, I could not work on it. I will fix it soon

**Comment by paulmelnikow** [comment]
Hi! By all means, feel free to reopen this when you have a chance to look at it!

**Pull request closed without merging**
