### PR TITLE
add [curseforge] downloads badge

### PR DESCRIPTION
**Pull request by Minecraftschurli**
this PR adds the curseforge downloads badge requested in #4498

it includes:
- auth helpers
- documentation for the api token
- the curseforge downloads badge

it sadly requires an api token to work for which the process for acquiring can be found [here](https://support.curseforge.com/en/support/solutions/articles/9000208346-about-the-curseforge-api-and-how-to-apply-for-a-key)

### CODE REVIEW

**Comment by calebcartwright** [comment]
Thanks for the PR!

> it sadly requires an api token to work for which the process for acquiring can be found here

Do you know how the authorization is scoped? I.e. will a request that authenticates with a valid token be allowed to pull data for _any_ target, or does the token have to be explicitly authorized/scoped to the target in order to work?

**Comment by Minecraftschurli** [comment]
it is an api token auth which is normally not scoped (in this case it is unscoped)

**Comment by Minecraftschurli** [comment]
I have tested it with my api token and it worked (I didn't have to set any scopes)

**Comment by calebcartwright** [comment]
The process for requesting an api key looks notably more involved and complicated than what we typically have to go through. What was your experience like?

**Comment by Minecraftschurli** [comment]
I used the game developer api key which just requires a google account login

**Comment by calebcartwright** [comment]
> I used the game developer api key which just requires a google account login

Gotcha. We're going to need some time to talk this over amongst the core team, as well as likely needing to have a dialog with the Curseforge folks to determine if/when this might be viable to proceed.

**Comment by curio-sitas** [comment]
Any news ?

**Comment by starboyceleste** [comment]
?

**Comment by PyvesB** [comment]
This work was effectively merged via #9252. Thanks for the contribution and the patience!

**Pull request closed without merging**
