### PR TITLE
Allow customization and removal of version prefixes.

### PR DESCRIPTION
**Pull request by ezzatron**
Gentlemen; imagine, if you will, a simpler world. A world unfettered by superfluous clutter. A cleaner, articulate, more eloquent way of being. That world is here and now.

This PR removes (by default) the `v` prefix for all version type shields. It also allows configuration of custom prefixes by way of the GET parameter `prefix`.

Think about it, why would you want **FILTHY** old this:

Disgusting!

When you could have **AMAZING** new this:

Delectable!

Or even **GLORIOUS** this:

Wow!

What is this sorcery? I'll let zero-time Academy Award® winner, Leonardo DiCaprio tell you in his own words:

It's the way of the future.

L-Dizzle is right, and you know it. A merge for this PR is a merge for the future. Not just your future, but for your children's futures. The future of the human race as we know it.

Merge today!

### CODE REVIEW

**Comment by espadrine** [comment]
Haha! Thanks.

I like succinctness, but having the `v` at the start was a conscious decision. For the example badge you give, the meaning is obvious. However, some badges would look like `hackage: 3`. The added `v` guarantees that we understand it to be a version.

Maybe we could make it so that if there are two dots, we don't put the `v`? It would make it a bit inconsistent, and I would prefer asking people.

As for the `?prefix=` parameter, I try to ensure that all query parameters have meaning for any badge, to avoid an explosion of parameters and simplify the cache system.

**Comment by mathiasbynens** [comment]
@ezzatron I like your style! :)

I prefer sticking with the `v` though, as it’s clearer.

**Comment by ezzatron** [comment]
No worries, I figured it would be a bit controversial. I'm happy to re-submit with `v` still being the default, but allowing removal via `&prefix=` if that would be preferred?

**Comment by espadrine** [comment]
@ezzatron Unfortunately, there wasn't an overwhelming majority in favour of that change.

As for the `?prefix=` parameter, I try to ensure that all query parameters have meaning for any badge, to avoid an explosion of parameters and simplify the cache system.

**Pull request closed without merging**
