### PR TITLE
minor changes in footer

### PR DESCRIPTION
**Pull request by pravdomil**
...

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Hi, thanks for the suggestion! I love the idea of improving this text and making it more welcoming and inviting.

I'm a little nervous about sending people directly to a "create issue" page. At the very least, people should search for an existing issue first.

Perhaps you could incorporate some of this text?

https://github.com/badges/shields/blob/master/CONTRIBUTING.md#suggesting-improvements

**Comment by pravdomil** [comment]
what about now?

**Comment by tooomm** [comment]
Isn't the meaning changed here? Is that intentional?

**Comment by pravdomil** [comment]
yes

**Comment by paulmelnikow** [comment]
I'd prefer to include some of the text at https://github.com/badges/shields/blob/master/CONTRIBUTING.md#suggesting-improvements.

However this change isn't making things any worse!

**Pull request merged**
