### PR TITLE
[Cauditor] Replace with error message

### PR DESCRIPTION
**Pull request by RedSparr0w**
Wait to merge until discussions in #1449 resolved.

Cauditor seems to no longer be a service:
[cauditor.org](http://cauditor.org)
[github](https://github.com/cauditor) - hasn't been updated since 2016

### CODE REVIEW

**Comment by RedSparr0w** [comment]
Thanks for reviewing @PyvesB 😄

**Comment by platan** [comment]
Here https://www.mullie.eu/projects/ is some information about Cauditor "Cauditor is currently offline - I got tired of the AWS bills :)", written 8 month ago
https://github.com/matthiasmullie/matthiasmullie.github.io/blame/cc55e21859cd6bb2b01d80afcf5adb42d9f39525/projects.html#L24

**Comment by paulmelnikow** [comment]
Let's switch this to `lightgray` and merge!

**Comment by RedSparr0w** [comment]
I **think** it uses `lightgray` by default,
But will update it to explicitly use `lightgray` in case the default color changes in the future.
Will also update the test, to test for color.

**Comment by paulmelnikow** [comment]
Ah, that's probably right! I couldn't remember what our default was.

**Comment by RedSparr0w** [comment]
I have also updated it to use
```javascript
setBadgeColor(badgeData, 'lightgray');
```
instead of
```javascript
badgeData.colorscheme = 'lightgray';
```
As this will override any choice of color the user makes with lightgray.
_Thought process being they will notice the non colored badge and remove it._

Do you think that's the right choice, or still fulfill the users preferred color?

**Comment by paulmelnikow** [comment]
Sounds good to me!

**Pull request merged**
