### PR TITLE
test review apps

### PR DESCRIPTION
**Pull request by chris48s**
is heroku going to make us a review app?

### CODE REVIEW

**Comment by calebcartwright** [comment]
the only thing i could see to do seems to have enabled the "new" review apps. i know we were holding off on making that change so wondering if that could be playing a factor too

**Comment by calebcartwright** [comment]
image

**Comment by chris48s** [comment]
We've got as far as a new error message, and that's progress

Screenshot at 2022-07-12 21-18-30

Here's the failed build log:

```


-----> Building on the Heroku-20 stack

-----> Determining which buildpack to use for this app

-----> Node.js app detected

       

-----> Creating runtime environment

       

       NPM_CONFIG_LOGLEVEL=error

       NODE_VERBOSE=false

       NODE_ENV=production

       NODE_MODULES_CACHE=true

       

-----> Installing binaries

       engines.node (package.json):  >=16.13.0

       engines.npm (package.json):   >=8.0.0

       

       Resolving node version >=16.13.0...

       Downloading and installing node 18.5.0...

       Bootstrapping npm >=8.0.0 (replacing 8.12.1)...

       npm 8.13.2 installed

       

-----> Installing dependencies

       Installing node modules

       npm ERR! code 1

       npm ERR! path /tmp/build_1af04fa4/node_modules/lmdb-store

       npm ERR! command failed

       npm ERR! command sh -c /tmp/install65765789633.sh

       npm ERR! make: Entering directory '/tmp/build_1af04fa4/node_modules/lmdb-store/build'

       npm ERR!   CXX(target) Release/obj.target/lmdb/src/node-lmdb.o

       npm ERR!   CC(target) Release/obj.target/lmdb/dependencies/lmdb/libraries/liblmdb/midl.o

       npm ERR!   CC(target) Release/obj.target/lmdb/dependencies/lmdb/libraries/liblmdb/chacha8.o

       npm ERR!   CC(target) Release/obj.target/lmdb/dependencies/lz4/lib/lz4.o

       npm ERR!   CXX(target) Release/obj.target/lmdb/src/env.o

       npm ERR!   CXX(target) Release/obj.target/lmdb/src/compression.o

       npm ERR!   CXX(target) Release/obj.target/lmdb/src/ordered-binary.o

       npm ERR! make: Leaving directory '/tmp/build_1af04fa4/node_modules/lmdb-store/build'

       npm ERR! gyp info it worked if it ends with ok

       npm ERR! gyp info using node-gyp@9.0.0

       npm ERR! gyp info using node@18.5.0 | linux | x64

       npm ERR! gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"

       npm ERR! gyp http GET https://nodejs.org/download/release/v18.5.0/node-v18.5.0-headers.tar.gz

       npm ERR! gyp http 200 https://nodejs.org/download/release/v18.5.0/node-v18.5.0-headers.tar.gz

       npm ERR! gyp http GET https://nodejs.org/download/release/v18.5.0/SHASUMS256.txt

       npm ERR! gyp http 200 https://nodejs.org/download/release/v18.5.0/SHASUMS256.txt

       npm ERR! gyp info spawn /usr/bin/python3

       npm ERR! gyp info spawn args [

       npm ERR! gyp info spawn args   '/tmp/build_1af04fa4/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',

       npm ERR! gyp info spawn args   'binding.gyp',

       npm ERR! gyp info spawn args   '-f',

       npm ERR! gyp info spawn args   'make',

       npm ERR! gyp info spawn args   '-I',

       npm ERR! gyp info spawn args   '/tmp/build_1af04fa4/node_modules/lmdb-store/build/config.gypi',

       npm ERR! gyp info spawn args   '-I',

       npm ERR! gyp info spawn args   '/tmp/build_1af04fa4/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',

       npm ERR! gyp info spawn args   '-I',

       npm ERR! gyp info spawn args   '/app/.cache/node-gyp/18.5.0/include/node/common.gypi',

       npm ERR! gyp info spawn args   '-Dlibrary=shared_library',

       npm ERR! gyp info spawn args   '-Dvisibility=default',

       npm ERR! gyp info spawn args   '-Dnode_root_dir=/app/.cache/node-gyp/18.5.0',

       npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/tmp/build_1af04fa4/.heroku/node/lib/node_modules/npm/node_modules/node-gyp',

       npm ERR! gyp info spawn args   '-Dnode_lib_file=/app/.cache/node-gyp/18.5.0/<(target_arch)/node.lib',

       npm ERR! gyp info spawn args   '-Dmodule_root_dir=/tmp/build_1af04fa4/node_modules/lmdb-store',

       npm ERR! gyp info spawn args   '-Dnode_engine=v8',

       npm ERR! gyp info spawn args   '--depth=.',

       npm ERR! gyp info spawn args   '--no-parallel',

       npm ERR! gyp info spawn args   '--generator-output',

       npm ERR! gyp info spawn args   'build',

       npm ERR! gyp info spawn args   '-Goutput_dir=.'

       npm ERR! gyp info spawn args ]

       npm ERR! gyp info spawn make

       npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]

       npm ERR! In file included from ../src/node-lmdb.h:32,

       npm ERR!                  from ../src/node-lmdb.cpp:1:

       npm ERR! ../../nan/nan.h: In function ‘void Nan::SetAccessor(v8::Local<v8::ObjectTemplate>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, Nan::imp::Sig)’:

       npm ERR! ../../nan/nan.h:2551:16: warning: ‘void v8::ObjectTemplate::SetAccessor(v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, v8::Local<v8::AccessorSignature>, v8::SideEffectType, v8::SideEffectType)’ is deprecated: Do signature check in accessor [-Wdeprecated-declarations]

       npm ERR!  2551 |     , signature);

       npm ERR!       |                ^

       npm ERR! In file included from /app/.cache/node-gyp/18.5.0/include/node/v8-function.h:15,

       npm ERR!                  from /app/.cache/node-gyp/18.5.0/include/node/v8.h:33,

       npm ERR!                  from ../src/node-lmdb.h:29,

       npm ERR!                  from ../src/node-lmdb.cpp:1:

       npm ERR! /app/.cache/node-gyp/18.5.0/include/node/v8-template.h:838:8: note: declared here

       npm ERR!   838 |   void SetAccessor(

       npm ERR!       |        ^~~~~~~~~~~

       npm ERR! In file included from ../src/node-lmdb.h:32,

       npm ERR!                  from ../src/env.cpp:25:

       npm ERR! ../../nan/nan.h: In function ‘void Nan::SetAccessor(v8::Local<v8::ObjectTemplate>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, Nan::imp::Sig)’:

       npm ERR! ../../nan/nan.h:2551:16: warning: ‘void v8::ObjectTemplate::SetAccessor(v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, v8::Local<v8::AccessorSignature>, v8::SideEffectType, v8::SideEffectType)’ is deprecated: Do signature check in accessor [-Wdeprecated-declarations]

       npm ERR!  2551 |     , signature);

       npm ERR!       |                ^

       npm ERR! In file included from /app/.cache/node-gyp/18.5.0/include/node/v8-function.h:15,

       npm ERR!                  from /app/.cache/node-gyp/18.5.0/include/node/v8.h:33,

       npm ERR!                  from ../src/node-lmdb.h:29,

       npm ERR!                  from ../src/env.cpp:25:

       npm ERR! /app/.cache/node-gyp/18.5.0/include/node/v8-template.h:838:8: note: declared here

       npm ERR!   838 |   void SetAccessor(

       npm ERR!       |        ^~~~~~~~~~~

       npm ERR! In file included from ../src/node-lmdb.h:32,

       npm ERR!                  from ../src/compression.cpp:26:

       npm ERR! ../../nan/nan.h: In function ‘void Nan::SetAccessor(v8::Local<v8::ObjectTemplate>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, Nan::imp::Sig)’:

       npm ERR! ../../nan/nan.h:2551:16: warning: ‘void v8::ObjectTemplate::SetAccessor(v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, v8::Local<v8::AccessorSignature>, v8::SideEffectType, v8::SideEffectType)’ is deprecated: Do signature check in accessor [-Wdeprecated-declarations]

       npm ERR!  2551 |     , signature);

       npm ERR!       |                ^

       npm ERR! In file included from /app/.cache/node-gyp/18.5.0/include/node/v8-function.h:15,

       npm ERR!                  from /app/.cache/node-gyp/18.5.0/include/node/v8.h:33,

       npm ERR!                  from ../src/node-lmdb.h:29,

       npm ERR!                  from ../src/compression.cpp:26:

       npm ERR! /app/.cache/node-gyp/18.5.0/include/node/v8-template.h:838:8: note: declared here

       npm ERR!   838 |   void SetAccessor(

       npm ERR!       |        ^~~~~~~~~~~

       npm ERR! In file included from ../src/node-lmdb.h:32,

       npm ERR!                  from ../src/ordered-binary.cpp:1:

       npm ERR! ../../nan/nan.h: In function ‘void Nan::SetAccessor(v8::Local<v8::ObjectTemplate>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, Nan::imp::Sig)’:

       npm ERR! ../../nan/nan.h:2551:16: warning: ‘void v8::ObjectTemplate::SetAccessor(v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, v8::Local<v8::AccessorSignature>, v8::SideEffectType, v8::SideEffectType)’ is deprecated: Do signature check in accessor [-Wdeprecated-declarations]

       npm ERR!  2551 |     , signature);

       npm ERR!       |                ^

       npm ERR! In file included from /app/.cache/node-gyp/18.5.0/include/node/v8-function.h:15,

       npm ERR!                  from /app/.cache/node-gyp/18.5.0/include/node/v8.h:33,

       npm ERR!                  from ../src/node-lmdb.h:29,

       npm ERR!                  from ../src/ordered-binary.cpp:1:

       npm ERR! /app/.cache/node-gyp/18.5.0/include/node/v8-template.h:838:8: note: declared here

       npm ERR!   838 |   void SetAccessor(

       npm ERR!       |        ^~~~~~~~~~~

       npm ERR! ../src/ordered-binary.cpp: In function ‘size_t valueToKey(const v8::Local<v8::Value>&, uint8_t*, size_t, bool, bool)’:

       npm ERR! ../src/ordered-binary.cpp:138:92: error: no matching function for call to ‘v8::Symbol::Description()’

       npm ERR!   138 |         Local<String> string = Local<String>::Cast(Local<Symbol>::Cast(jsKey)->Description());

       npm ERR!       |                                                                                            ^

       npm ERR! In file included from /app/.cache/node-gyp/18.5.0/include/node/v8-object.h:11,

       npm ERR!                  from /app/.cache/node-gyp/18.5.0/include/node/v8-array-buffer.h:13,

       npm ERR!                  from /app/.cache/node-gyp/18.5.0/include/node/v8.h:24,

       npm ERR!                  from ../src/node-lmdb.h:29,

       npm ERR!                  from ../src/ordered-binary.cpp:1:

       npm ERR! /app/.cache/node-gyp/18.5.0/include/node/v8-primitive.h:588:16: note: candidate: ‘v8::Local<v8::Value> v8::Symbol::Description(v8::Isolate*) const’

       npm ERR!   588 |   Local<Value> Description(Isolate* isolate) const;

       npm ERR!       |                ^~~~~~~~~~~

       npm ERR! /app/.cache/node-gyp/18.5.0/include/node/v8-primitive.h:588:16: note:   candidate expects 1 argument, 0 provided

       npm ERR! make: *** [lmdb.target.mk:150: Release/obj.target/lmdb/src/ordered-binary.o] Error 1

       npm ERR! gyp ERR! build error 

       npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2

       npm ERR! gyp ERR! stack     at ChildProcess.onExit (/tmp/build_1af04fa4/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)

       npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:537:28)

       npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)

       npm ERR! gyp ERR! System Linux 4.4.0-1104-aws

       npm ERR! gyp ERR! command "/tmp/build_1af04fa4/.heroku/node/bin/node" "/tmp/build_1af04fa4/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"

       npm ERR! gyp ERR! cwd /tmp/build_1af04fa4/node_modules/lmdb-store

       npm ERR! gyp ERR! node -v v18.5.0

       npm ERR! gyp ERR! node-gyp -v v9.0.0

       npm ERR! gyp ERR! not ok

       

       npm ERR! A complete log of this run can be found in:

       npm ERR!     /tmp/npmcache.RSksH/_logs/2022-07-12T20_29_31_521Z-debug-0.log

-----> Build failed

       

       We're sorry this build is failing! You can troubleshoot common issues here:

       https://devcenter.heroku.com/articles/troubleshooting-node-deploys

       

       Some possible problems:

       

       - Dangerous semver range (>) in engines.node

         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version

       

       Love,

       Heroku

       

 !     Push rejected, failed to compile Node.js app.

 !     Push failed


```

It is late now. I'll have to come back to it, but it feels like we are close..

**Comment by chris48s** [comment]
Seeing `NODE_ENV=production` in that log is making me also think once we've sorted that we might need to account for the fact I moved `requireCloudflare: true` into https://github.com/badges/shields/blob/master/config/shields-io-production.yml while review apps were turned off..

**Comment by chris48s** [comment]
Oh.. it'll be:

- https://github.com/badges/shields/pull/7973
- https://github.com/badges/shields/pull/7956

yay

**Comment by calebcartwright** [comment]
:crossed_fingers:

**Pull request closed without merging**
