### PR TITLE
[pypi] Service calls according to new Warehouse API

### LINKED ISSUE #8250: PyPI: Changes to the Warehouse api
### Are you experiencing an issue with...

badge-maker NPM package

### 🐞 Description

[The Warehouse API](https://warehouse.pypa.io/api-reference/json.html) is changing and will remove the key `releases` from the response.

This change is breaking service tests for PyPI.

### 🔗 Link to the badge

_No response_

### 💡 Possible Solution

Refactor `services/pypi/pypi-base.js` and `services/pypi/pypi-helpers.js` to use information from `urls` not from releases

### PR DESCRIPTION
**Pull request by ericof**
This PR fixes #8250

### CODE REVIEW

**Comment by ericof** [comment]
@calebcartwright New PR targetting only the PyPI API fix

**Comment by calebcartwright** [comment]
Is the deletion of several of the service and tester files intentional?

**Comment by ericof** [comment]
@calebcartwright No, it was not. I fixed the PR now

**Review by chris48s — APPROVED** [review]
LGTM. Thanks for the fix :+1:

**Pull request merged**
