### PR TITLE
Fix colors for new appveyor badge

### PR DESCRIPTION
**Pull request by paulmelnikow**
I noticed the new AppVeyor badges were gray. This fixes them.

### CODE REVIEW

**Comment by RedSparr0w** [comment]
Looks like this change wont allow the user to override the color.

Actually looks like it already wont allow user overrides:
[](https://shields-staging.herokuapp.com/appveyor/ci/gruntjs/grunt.svg?colorB=10ADED)
`https://shields-staging.herokuapp.com/appveyor/ci/gruntjs/grunt.svg?colorB=10ADED`
`#10ADED`

**Comment by paulmelnikow** [comment]
Oof, looks like I should add some tests of the color overriding!

**Comment by paulmelnikow** [comment]
Are you good with merging this in the meantime?

**Comment by RedSparr0w** [comment]
Sounds good, beats having the label grey currently.

**Comment by paulmelnikow** [comment]
I pushed a fix for the colors in #1581.

**Comment by RedSparr0w** [comment]
Although this may need to be reverted once you merge #1581 
Haven't had a chance to check yet but assuming this works similar to the current:
`badgeData.colorscheme = 'brightgreen';` - can be overridden by user.
`setBadgeColor(badgeData, 'red');` - will override users override.

**Comment by paulmelnikow** [comment]
It's quite a lot cleaner now! [`_makeBadgeData`](https://github.com/badges/shields/blob/2d65153/services/base.js#L90-L129) is a pure function which accepts two parameters: (1) output of the `handle()` function and (2) query-string overrides. It cascades through all the possible places to set the color: the user override, the service output, the service default, and the Shields default, and sets it once. Then it returns `badgeData` that `makeBadge` understands.

That's still a bit indirect, since it's basically translating one schema to another. Though, probably it's easiest if it stays that way until we finish the service rewrite. At that point, we can rework `makeBadge` so it understands the new schema.

The code in master doesn't address #1446 yet, though I think it'll be easy enough to fix that. First, though, I want to land #1581, so I can open a PR for some BaseService error-handling code that I have in flight. Maybe I can address #1446 as part of that PR!

**Pull request merged**
