### PR TITLE
Add Dependabot logo

### PR DESCRIPTION
**Pull request by greysteil**
To be used with badges like the one [here](https://github.com/dependabot/dependabot-core/pull/253).

### CODE REVIEW

**Comment by greysteil** [comment]
Of course - done!

**Comment by greysteil** [comment]
🎉. Thanks for the review @PyvesB.

**Comment by RedSparr0w** [comment]
Which badges would this logo used for?
As we generally do not accept logo's which do not have a relevant badge.

-----
You can also include logos in base64 format (you will also need to replace any `+`'s with `%2B`),
The following could be appended to your badge url to include this PR's logo:
```
?logo=data:image/svg%2bxml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjggOCAxOTAgMTkwIj48ZyBmaWxsPSIjRkZGIj48cGF0aCBkPSJNMTQuNiA1Ni4ySDE3NXYxMTguN0gxNC42ek03Ny4yIDguN2gzNS4ydjM1LjZINzcuMnoiLz48cGF0aCBkPSJNMTAwLjcgMzIuNGgxMS43djM1LjRoLTExLjd6TTIuOSAxMTEuNmgyMy41djM1LjZIMi45ek0xNjMuMiAxMTEuNmgyMy41djM1LjZoLTIzLjV6Ii8%2bPC9nPjxnIGZpbGw9IiM1NTUiPjxwYXRoIGQ9Ik01Ny43IDExNS41bC03LjktNy45LTcuOCA4IDE1LjcgMTUuN0w4MSAxMDcuNmwtNy44LTh6TTEyNC4xIDExNS41bC03LjgtNy45LTcuOCA4IDE1LjYgMTUuNyAyMy41LTIzLjctNy44LTh6Ii8%2bPC9nPjwvc3ZnPg==
```

### Example:

```
https://img.shields.io/:dependabot-badge-blue.svg?logo=data:image/svg%2bxml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjggOCAxOTAgMTkwIj48ZyBmaWxsPSIjRkZGIj48cGF0aCBkPSJNMTQuNiA1Ni4ySDE3NXYxMTguN0gxNC42ek03Ny4yIDguN2gzNS4ydjM1LjZINzcuMnoiLz48cGF0aCBkPSJNMTAwLjcgMzIuNGgxMS43djM1LjRoLTExLjd6TTIuOSAxMTEuNmgyMy41djM1LjZIMi45ek0xNjMuMiAxMTEuNmgyMy41djM1LjZoLTIzLjV6Ii8%2bPC9nPjxnIGZpbGw9IiM1NTUiPjxwYXRoIGQ9Ik01Ny43IDExNS41bC03LjktNy45LTcuOCA4IDE1LjcgMTUuN0w4MSAxMDcuNmwtNy44LTh6TTEyNC4xIDExNS41bC03LjgtNy45LTcuOCA4IDE1LjYgMTUuNyAyMy41LTIzLjctNy44LTh6Ii8%2bPC9nPjwvc3ZnPg==
```

**Comment by greysteil** [comment]
I want to use it for Dependabot, which creates badges on its PRs like the ones [here](https://github.com/dependabot/dependabot-core/pull/253) and [here](https://dependabot.com/compatibility-score). We'd been using the base64 format until recently, but it appears the API for it changed slightly recently as the logos stopped appearing. I'll update our code with the one from the example above now.

**Comment by paulmelnikow** [comment]
> We'd been using the base64 format until recently, but it appears the API for it changed slightly recently as the logos stopped appearing.

Separately from the discussion in this PR, could you open an issue for that so we can fix it? I'd really appreciate that!

**Comment by paulmelnikow** [comment]
Dependabot looks really cool! Is there an API? I would love to have a badge that projects could include, to show off their likelihood of compatibility.

@RedSparr0w I'm fine with including _some_ logos that don't have badges. We'd need a guideline, though. How about, if they are tools that are widely used by developers?

**Comment by PyvesB** [comment]
Should we add something along the following lines to the Logo section in Contributing.md?

> In general we only accept logos that have a corresponding badge on the homepage (e.g. an Eclipse logo because we support service badges for the Eclipse Marketplace), but we may also approve logos for tools widely used by developers (e.g. our Slack logo).

I'm happy to open a pull request if we're all on the same page here. 👍

**Comment by greysteil** [comment]
> Separately from the discussion in this PR, could you open an issue for that so we can fix it? I'd really appreciate that!

Done - https://github.com/badges/shields/issues/1540.

> Is there an API? I would love to have a badge that projects could include, to show off their likelihood of compatibility.

No, but I could easily add one! The badges show how compatible a new dependency release is with a previous version, based on all the update PRs Dependabot has created between those two version. So, for example, a 95% compatibility score between Rails 5.1.0 and Rails 5.1.4 would mean 95% of people who updated from Rails 5.1.0 to Rails 5.1.4 had all of their tests passing with no code changes required. Could be a useful thing for dependency authors to put in their changelogs, as well as to be included on Dependabot PRs.

**Comment by paulmelnikow** [comment]
> So, for example, a 95% compatibility score between Rails 5.1.0 and Rails 5.1.4 would mean 95% of people who updated from Rails 5.1.0 to Rails 5.1.4 had all of their tests passing with no code changes required. Could be a useful thing for dependency authors to put in their changelogs, as well as to be included on Dependabot PRs.

That sounds like it would be really useful! A great use of a badge too, since that data changes over time.

We do have [a great tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md) for adding badges, if you're up for taking that on.

**Comment by greysteil** [comment]
> We do have a great tutorial for adding badges, if you're up for taking that on.

Totally up for that in a few weeks, when I've gotten on top of a couple of other things!

**Comment by greysteil** [comment]
Badge added in https://github.com/badges/shields/pull/1734, using the great tutorial. I've included the logo there, because it's move obvious than merging this separately.

Thanks for your help everyone!

**Pull request closed without merging**
