### PR TITLE
Fix rendering in Firefox on Windows

### LINKED ISSUE #4275: Letter spacing is incorrect on social badges
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [x] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

The social badges display with incorrect letter spacing. 

:link: **Link to the badge**

https://img.shields.io/github/stars/badges/shields?style=social

By removing the `textWidth` you can see what the letter spacing would be if the width were correct:

Correct:

Screen Shot 2019-10-31 at 6 21 00 PM

Incorrect:

Screen Shot 2019-10-31 at 6 21 18 PM

:bulb: **Possible Solution**

- Measure the text using the font used for display (I suppose Helvetica or Helvetica Neue)
- Measure the text in the correct weight (700)
- Make sure nothing else is getting in the way 🤓

### LINKED ISSUE #4813: Improve text appearance in Firefox on Windows
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)

:beetle: **Description**

There is room to improve the badge kerning / keming.

Between "o" and "w".
image

As well as "z" and "e".
image

:link: **Link to the badge**

This is an issue with the text on any badge with the aforementioned character combinations. (Possibly others that I have not noticed)

e.g. "Powershell", "bower"

Note that the issue does not appear on the `for-the-badge` style.

### PR DESCRIPTION
**Pull request by FTOH**
Fix #4813 
Complements #4979
May be fixed #4275 

Should be tested on other OS

Documentation for text-rendering attribute:
https://developer.mozilla.org/ru/docs/Web/SVG/Attribute/text-rendering

Comparison
image

image

### CODE REVIEW

**Comment by paulmelnikow** [comment]
This is amazing @FTOH! Thanks so much for tracking this down!

I re-added DejaVu Sans at the end. Would you mind updating the snapshots again?

Otherwise I think this is good to merge.

@calebcartwright does this look good to you on all the platforms? @RedSparr0w @chris48s any concerns?

**Comment by chris48s** [comment]
Looks like there are still some failing tests - probably because the font order has changed.

The easiest thing to do is usually just to delete the snapshots file, re-run the package tests and then check the diff, rather than try to manually update the snapshots.

Beyond that, I think the core change here is useful

**Comment by calebcartwright** [comment]
What's the page/listing shown in the screenshots so that i can compare from ubuntu?

**Comment by paulmelnikow** [comment]
They look great, yea? Thanks!

**Comment by calebcartwright** [comment]
The changes in those screenshots on Windows look great.

I'm not sure if I was supposed to be able to see any differences on Linux. I felt a bit like this :laughing: 
https://youtu.be/gW2LtX1217s?t=124

**Comment by paulmelnikow** [comment]
Thanks for this awesome contribution to Shields @FTOH! I so appreciate your digging into this, and helping us make good on our "pixel perfect" promise.

If you're interested in continuing to dig in on these kinds of issues there's lots to do!

These are two really impactful examples:

- Arabic text (#4140)
- Correct font-width computation for boldface type (#4275)

Recently @chris48s and I rewrote all the badge generation using plain JavaScript and template literals, so it's much more readable and changeable than when they were DoT templates. (See #4459 and #3637. There is a lot of refactoring that can be done to make it even more readable.)

IIRC there are a handful of open issues relating to padding computations that are slightly off. With the code as it is now it should be pretty reasonable to track down the issues and fix them.

**Comment by FTOH** [comment]
@paulmelnikow When will the changes take effect?

**Comment by paulmelnikow** [comment]
It's live now!

**Pull request merged**
