### PR TITLE
Fix style picker in markup modal

### LINKED ISSUE #1330: for-the-badge style not available in style dropdown (preview window)
The new `for-the-badge` style isn't available in the preview window anymore.
In https://github.com/badges/shields/pull/1242 its display size got fixed there, but now it's not available in the selection anymore at all:
preview

Also something related to the big rewrite maybe? @paulmelnikow 

Verified at: https://shields-staging.herokuapp.com/

### PR DESCRIPTION
**Pull request by paulmelnikow**
- Restore correct list of styles to markup modal
- DRY lists of styles

Fix #1330

### CODE REVIEW

**Comment by paulmelnikow** [comment]
It looks like the page needs to load completely before the preview modal becomes responsive, which makes sense. It doesn't know to prioritize the preview image over the others.

**Comment by paulmelnikow** [comment]
@tooomm Thanks! Could you try it again once this deploys? I ran into a conflict with #1190 which I just resolved.

**Comment by tooomm** [comment]
All good. Also double checked with Chromium and Edge.

I realized that the style-selection gets remembered though... I would expect it to reset back to the default to be honest. But one could consider this behavior a feature as well. :)

**Comment by paulmelnikow** [comment]
Yea, I thought about that. It seems like it'd be annoying to keep picking `flat-square` if that's what you prefer. Probably if you are making a bunch of badges, you'll want them to have the same style.

**Comment by paulmelnikow** [comment]
Thanks for the testing!

**Comment by tooomm** [comment]
Also, I spotted that the adjusted link regarding your style choice is altered for all code boxes (like `Markdown` etc.), but not for the `image` link itself.

I didn't want to open even another issue regarding such small issues... ;)

**Comment by RedSparr0w** [comment]
I think it is supposed to be that way,
Due to the image being generated from the `image` link where you insert your own details and custom params
image
But there probably should also be a direct image link with all the options included.

**Comment by tooomm** [comment]
Then it's a bit confusing in my opinion.
If you shouldn't copy that link there to use it in whatever form to integrate your badge, it should only be labeled `custom parameter` to allow a simple input of those.
Otherwise image implies that you get the link to the exact image you see/generated at the top.

Actually, I think both are helpful/needed.

This should be related to https://github.com/badges/shields/issues/701 and could be incorporated/tracked there.

**Comment by RedSparr0w** [comment]
Yeah I agree, and once something like #701 is implemented it shouldn't be a problem.

Sent from my iPhone

On 6/12/2017, at 1:02 PM, tooomm <notifications@github.com<mailto:notifications@github.com>> wrote:


Then it's a bit confusing in my opinion.
If you shouldn't copy that link there to use it in whatever form to integrate your badge, it should only be labeled custom parameter to allow a simple input of those.
Otherwise image implies that you get the link to the exact image you see/generated at the top.

Actually, I think both are helpful/needed.

This should be related to #701<https://github.com/badges/shields/issues/701> and could be incorporated/tracked there.

**Comment by paulmelnikow** [comment]
Right, I think once we have #701 we won't need that image URL to be editable. I'd be fine adding an image URL display, too, between the style box and the markup.

We could repurpose #1311 to discuss frontend UX tweaks if you'd like.

**Pull request merged**
