### PR TITLE
Fix invalid `rst` format when `alt` or `target` is present

### PR DESCRIPTION
**Pull request by abitrolly**

### CODE REVIEW

**Comment by calebcartwright** [comment]
Could you elaborate on the problem you're trying to solve with these proposed changes? If you have an example that reproduces the behavior that'd be great

**Comment by abitrolly** [comment]
@calebcartwright I've looked for a test and found none, but I guess I could at least post the output, indeed. 

The badge generated for https://github.com/fschulze/sqlalchemy_schemadisplay/pull/31 was
```
.. image:: https://img.shields.io/pypi/v/sqlalchemy_schemadisplay   :alt: PyPI
```
And that is rendered as a missing image, because GitHub probably translates it to URL. The correct rST markup.
```
.. image:: https://img.shields.io/pypi/v/sqlalchemy_schemadisplay
   :alt: PyPI
```

**Comment by chris48s** [comment]
@calebcartwright This PR does fix a bug. See https://docutils.sourceforge.io/docs/ref/rst/directives.html#image for the correct RST syntax.

@abitrolly The tests for this are in https://github.com/badges/shields/blob/7d452472defa0e0bd71d6443393e522e8457f856/frontend/lib/generate-image-markup.spec.ts#L49-L63 and will need updating

I've closed and re-opened this to get the CI to run. We do have an issue where sometimes the Circle CI builds don't run for particular PRs - there is some info on this at https://github.com/badges/shields/issues/8109 I dunno if any of the info in https://github.com/badges/shields/issues/8109#issuecomment-1169152338 are actionable for you. If not, we'll have to do the same again.

**Comment by abitrolly** [comment]
The `.spec.ts` extension didn't trigger me that it is a file with tests. Looked like some alien typescript thing to me. Or maybe I was browsing my fork, which was too old to include this file.

Anyway, I think I've fixed tests.

**Comment by abitrolly** [comment]
Regarding unblocking `CircleCI`, I don't see this as acceptable for my repos.

image

**Review by chris48s — APPROVED** [review]
Merging this having pushed 5260a08 - Lets just merge the fix than do another round of back-and-forth over whitespace. Thanks

**Comment by abitrolly** [comment]
Forgot `\n` at the ends :facepalm: but seems that wouldn't satisfy the linter anyways.

Thanks.

**Pull request merged**
