### PR TITLE
Fix broken travis branches

### PR DESCRIPTION
**Pull request by driskell**
Hello,

Looks like when you request a build status for a branch it ignores the branch!
Seems a typo in the code.

Jason

### CODE REVIEW

**Comment by espadrine** [comment]
Good lord, you're right! Thank you!

**Comment by jakirkham** [comment]
I think the original issue I was raising here ( https://github.com/badges/shields/issues/528 ) is addressed by this change. However, I think discussion in that issue turned to a potentially different issue so I will leave it open for now.

**Comment by jakirkham** [comment]
Is it possible the HHVM branch badge is suffering from a similar problem?

**Comment by jakirkham** [comment]
Also, TeamCity CodeBetter Coverage badge is complaining it is malformed. Wondering if a similar fix would help it.

**Comment by espadrine** [comment]
Usually, those caused by a change in the format of the data. Adding a breakpoint in server.js reveals what needs fixing. But it is a game of whack-a-mole, so patches are very welcome!

**Pull request merged**
