### PR TITLE
🚢 Deploy!

### PR DESCRIPTION
**Pull request by greysteil**
There are 82 commits on master waiting to be deployed.

If there's anything blocking this going out then I'd love to help :octocat:.

### CODE REVIEW

**Comment by RedSparr0w** [comment]
Closing as unfortunately this will not deploy to production.

-----------
See #1538 [Deploy status]

Quoting @paulmelnikow:

> Deploys usually happen every 1–3 weeks. Thaddée [@espadrine], who has limited time on this project, is the only sysadmin. He's working on giving me access to deploy and logs, but doing so is complicated because the hosting account (and maybe the servers too) are shared with other services he runs.

It has been almost 3 months since the last deploy (Mar 25) so hopefully there will be one soon.
🤞

**Comment by greysteil** [comment]
Ah, 👍, and thanks both for all your work on this project!

**Comment by espadrine** [comment]
The commit currently deployed is 57a1bf2f082be3c0bcef4250f6a5e783a02fc9cf, which is from May 30.

(I typically deploy every two weeks ; although last week-end was spent with the step-family, to prepare my sister's wedding. We were in a rural area of French Bourgogne, which is known for its wine, but not for its Internet access.)

@greysteil What fundamental change are you not seeing? Is there a commit that should have been deployed, but hasn't? Maybe there was a regression?

**Comment by greysteil** [comment]
The commit that I (selfishly) want deployed is ca58d84447db73c52d3a67f82979e539d29ed2e0, but when I saw the badge saying there were 81 commits awaiting deploy and looked into it I figured a deploy was needed more generally, hence the PR.

Is there any way that we can tell which commit is the latest deployed and fix the badge on the readme? I wouldn't have created this PR and caused this trouble if I'd known it was only a few weeks since the last deploy.

<a href="https://github.com/badges/shields/compare/gh-pages...master">
        commits to be deployed</a>

**Comment by paulmelnikow** [comment]
Thanks for deploying the servers! For some reason gh-pages is not updating:

screen shot 2018-06-20 at 11 10 55 am

Hence the status badge being wrong, as well…

**Comment by paulmelnikow** [comment]
I know there's a bunch of tooling in the front-end deploy. If it's not working, let me know and I can fix whatever is broken and deploy 57a1bf2.

**Comment by espadrine** [comment]
@greysteil No trouble! You're right to ask.

@paulmelnikow I didn't notice that… I'll look into what is wrong tonight.

By the way, with Sentry working, do you feel OK with making deployments yourself? It is not ideal, but you have the ability to deploy individual servers or all of them at once, so this deployment workflow may work for you (it is pretty close to what I do):
1. Look at new commits compared to the latest deployed hash.
2. Check that it works on localhost.
3. Deploy a single server (say s0).
4. Look it up by IP by loading https://192.99.59.72/index.html in your browser.
5. Check Sentry for new errors for a bit.
6. If it looks OK, deploy all servers.
7. Keep an eye on Sentry.

**Comment by espadrine** [comment]
Looks like there indeed is something a bit broken:

```
$ make website
…
$ make deploy-gh-pages
(LONG_CACHE=true BASE_URL=https://img.shields.io npm run build && \
git checkout -B gh-pages master && \
cp build/index.html index.html && \
cp -r build/_next next && \
pushd next/*/page && mv {_,}error && popd && \
sed -i 's,/_next/,./next/,g' index.html $(find next -type f) && \
sed -i 's,_error,error,g' index.html $(find next -type f) && \
git add -f build index.html next && \
git commit -m '[DEPLOY] Build index.html' && \
git push -f origin gh-pages:gh-pages) || git checkout master

> gh-badges@1.3.0 prebuild /home/tyl/file/github/gh-badges
> npm run depcheck


> gh-badges@1.3.0 depcheck /home/tyl/file/github/gh-badges
> check-node-version --node ">= 8.0"


> gh-badges@1.3.0 build /home/tyl/file/github/gh-badges
> npm run examples && next build && next export -o build/


> gh-badges@1.3.0 examples /home/tyl/file/github/gh-badges
> node lib/export-badge-examples-cli.js > badge-examples.json

> Using external babel configuration
> Location: "/home/tyl/file/github/gh-badges/package.json"
  using build directory: /home/tyl/file/github/gh-badges/.next
  copying "static" directory
  exporting path: /

Switched to and reset branch 'gh-pages'
~/file/github/gh-badges/next/c8b571e7-c012-44f1-9a20-e4eba9321dd0/page ~/file/github/gh-badges
mv: cannot stat '_error': No such file or directory
…
```

I don't quite know what it is; you are welcome to take a stab at it!

**Comment by RedSparr0w** [comment]
Thanks for the update @espadrine :smile:,
I probably should have tried some of the badges instead of relying solely on the gh-pages branch.

As for the above problem would changing this line to something like this fix it:
```diff
-pushd next/*/page && mv {_,}error && popd && \
// If the _error directory is needed:
+pushd next/*/page && (mv {_,}error || mkdir error\_error) && popd && \
// If not:
+pushd next/*/page && (mv {_,}error || true) && popd && \
```

**Comment by platan** [comment]
Can we somehow update `gh-pages`? Or should we wait for the next deployment? <a href="https://github.com/badges/shields/compare/gh-pages...master">
        commits to be deployed</a> badge and [Deployment status in PR](https://github.com/badges/shields/issues/1708) feature are based on a content of this branch.

**Comment by paulmelnikow** [comment]
@platan I'll look into this tonight.

> By the way, with Sentry working, do you feel OK with making deployments yourself? It is not ideal, but you have the ability to deploy individual servers or all of them at once, so this deployment workflow may work for you (it is pretty close to what I do):

@espadrine,

As a stopgap, this seems okay. It's possible that things could break in a way that crashes the servers without getting a message to Sentry. Without logs, we won't know what's causing the problems. We also can't monitor server resources, see our traffic, or control the load balancer.

Could we make a plan to get this project onto dedicated hosting, so that no part of it is dependent on any one person?

**Comment by espadrine** [comment]
We can switch the VPS instances one by one to a shared account. That said, SSH access will still need to be heavily restricted. Also, having a proper set up, where each deployment requires the validation of another member, and all SSH sessions are logged in a tamper-proof way, and can be inspected by other members, would require quite a bit of work.

**Comment by chris48s** [comment]
I'm not going to express a strong preference for a particular solution because I don't have access to the logs/monitoring etc so its difficult for me to make an informed judgement on the best way forward given traffic, finances, etc.

I would like to see us move towards better performance, more frequent deploys and the ability to share ops burden with more maintainers (without compromising security, etc). Happy to pitch in with that where appropriate.

One thing I will add to @paulmelnikow 's suggestion is that because everything is served up from behind cloudfront, it should be possible to test a new setup (e.g: PaaS) without doing a 'big bang' migration. We could load-balance some % of traffic to a new solution and some to the existing 3xVPS setup. That would allow a low-risk trial to be conducted on real-world traffic with option to back out or conduct phased migration.

**Comment by paulmelnikow** [comment]
> We could load-balance some % of traffic to a new solution and some to the existing 3xVPS setup. That would allow a low-risk trial to be conducted on real-world traffic with option to back out or conduct phased migration.

Love that idea!

> I'm not going to express a strong preference for a particular solution because I don't have access to the logs/monitoring etc so its difficult for me to make an informed judgement on the best way forward given traffic, finances, etc.

I don't have access to logs or monitoring either, though I could speak to the finances. For a while I was arguing against new hosting for cost reasons. However things have changed. We've gotten some big donations and have some good-sized regular donations too. I took the liberty of reaching out to Zeit about donating hosting, though if that doesn't come through, we could pay our own way.

Clearing up any uncertainty about the cost would be another good reason for the load-balancer approach you're suggesting. We can get better cost numbers that way, and still have an option to back things out.

**Comment by paulmelnikow** [comment]
A week ago I wrote @espadrine, following up on the above. I’m concerned. If we don't fix our reliability problems now, I'm afraid our users will go elsewhere and this project will die.

**Pull request closed without merging**
