### PR TITLE
High Resolution Favicon.png 

### PR DESCRIPTION
**Pull request by sidhyatikku**
You can preview the favicon here. Canvas size (1000x1000)px #1497 
favicon

### CODE REVIEW

**Comment by chris48s** [comment]
Hi thanks for submitting your first PR to shields. I think in order to resolve the linked issue we will need a few different icon sizes/types and `<link>` headers to serve relevant icon sizes in different contexts. There's a good stackoverflow post on this here: https://stackoverflow.com/a/25961390

/cc @RedSparr0w

**Comment by sidhyatikku** [comment]
okay sure. I guess 192px X 192px will do the show.

**Comment by sidhyatikku** [comment]
[iconified.zip](https://github.com/badges/shields/files/2441384/iconified.zip)
Please check if the attached file has all the required favicon specs

**Comment by sidhyatikku** [comment]
Yes, the favicon will be better without the margin

**Comment by RedSparr0w** [comment]
Hey @sidhyatikku, Just checking in to see if you've managed to find some time to adjust the favicon? 😄

**Comment by sidhyatikku** [comment]
I rebased incorrectly, closing this PR and will make a fresh one. Apologies to all.

**Pull request closed without merging**
