### PR TITLE
feat: Added Spectrum.chat badge

### PR DESCRIPTION
**Pull request by FezVrasta**
The resulting badge will look like this:

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Hi! Thanks for this.

We can definitely add a logo, though this logo doesn't seem to be the spectrum logo.

Is there an API that returns, e.g. the number of users in the room? That could be a more helpful badge.

There isn't consensus about adding routes for static badges.  We do have a gitter badge, but that is the only one. As I wrote in #1031:

> I'm ambivalent about whether to add more API-free badges like this, or simply use the custom badge route like Daniel suggests. On the one hand, it makes standardization and updating easy. On the other, it clutters the project with unnecessary code.

**Comment by FezVrasta** [comment]
That's the logo used in their own version of the badge:
https://github.com/withspectrum/badge

About the number of users, they have a GraphQL API, I should ask if it's possible to use it for this kind of thing or not. I'll let you know.

**Comment by RedSparr0w** [comment]
Agree with what @paulmelnikow has said,
At this stage it should just use the static badge,
And if needed just create a PR to add the logo.
The uri could then be:
`/badge/chat-on%20spectrum-7B16FF.svg?logo=spectrum`
image

But once the API goes public this could be a good addition.

**Comment by paulmelnikow** [comment]
> About the unnecessary code part, could we add a new API to read those static badges info from a JSON or YML file maybe?

We could discuss this in #1252. Maintaining static badges fer errything might be a lot of discussion work, but I think is something this project could take, on if people think we should.

Going to close for now.

**Pull request closed without merging**
