### PR TITLE
Add [github] PR additions/deletions

### PR DESCRIPTION
**Pull request by JosepBernad**
From issue #3363.

I'm still working but I wanted to show you guys my process. 
I need to fix some lint issues and write some tests.

Thanks for your help!

### CODE REVIEW

**Comment by paulmelnikow** [comment]
This pull request **introduces 1 alert** when merging eb8cd9aadd1432cb0c55ed394dae1c675dad9638 into b87bf0f4ba779ba26ebb008b982f7eab8fa89335 - [view on LGTM.com](https://lgtm.com/projects/g/badges/shields/rev/pr-c759616905df8ed1eb335409c336c24c25db43ca)

**new alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by JosepBernad** [comment]
Fixed, thanks!

**Comment by PyvesB** [comment]
Thanks for starting looking at this @JosepBernad! I'm wondering whether it would be possible to add it to the existing `GithubIssueDetail` class (see [this file](https://github.com/badges/shields/blob/master/services/github/github-issue-detail.service.js)) as it already handles several badges for GitHub pull requests/issues. Maybe it's worth giving it a try before creating a separate service?

**Comment by PyvesB** [comment]
@JosepBernad have you had a chance to look into this again? 😄

**Comment by PyvesB** [comment]
It's been a while so I'm going to close this pull request for now. Feel free to reopen when you're ready to progress it again. 😉

**Pull request closed without merging**
