### PR TITLE
[Github] Add 2 new badges for Github pull request state and review

### PR DESCRIPTION
**Pull request by ruizb**
**Github pull request state**

URL pattern:

```
/github/pr-state/<user>/<repo>/<issueId>.<format>
```

The issue (which ID is provided in the URL) must be a pull-request.

The following states are handled:
- `inaccessible` (lightgrey) if the request failed or the response was not 
  a json-formatted issue
- `closed` (red) if the PR is closed and not merged
- `merged` (Github purple-ish) if the PR is closed and merged
- `mergeable` (green) if the PR is open and clean (build OK, no conflicts detected, rebased on latest version of the base branch)
- `unstable` (yellow) if the PR is open but unstabe
- `has conflicts` (red) if the PR is open but not mergeable (conflicts with base branch detected)
- `unknown` (lightgrey) if the PR is open but the mergeability is not computed yet ([more details here](http://stackoverflow.com/questions/30619549/why-does-github-api-return-an-unknown-mergeable-state-in-a-pull-request))

**Github pull request review**

URL pattern:

```
/github/pr-review/<user>/<repo>/<issueId>.<format>
```

The issue (which ID is provided in the URL) must be a pull-request.

The following states are handled:
- `inaccessible` (lightgrey) if the request failed or the response was not 
  a json-formatted issue
- `none` (lightgrey) if no review has been requested
- `pending` (yellow) if there are still reviewers that didn't perform the review OR if no review has been approved or requested changes
- `approved` (green) if at least 1 review has been approved and none requested changes
- `need changes` (red) if at least 1 review requested changes

*Note: Only the latest review of every reviewer is taken into account.*

### CODE REVIEW

**Comment by yannickglt** [comment]
+1

**Comment by paulmelnikow** [comment]
Hi, thanks for this contribution. This looks awesome, and it'd be great to get it merged.

Would it make sense to integrate the review feature, as you mention?

Would you be willing to add tests using the project's [new testing framework](https://github.com/badges/shields/tree/master/service-tests)?

**Comment by ruizb** [comment]
Hi, the "review" feature has been officially released a few days ago on the Github API (https://developer.github.com/changes/2017-05-09-end-black-cat-preview/). However, the `pr-state` badge being already "complex", I actually created another one for the reviews, I hope that makes sense.

I will gladly add some tests for these badges! It's actually the next step 😃

**Comment by ruizb** [comment]
Hello @paulmelnikow, I added tests for the 2 badges (`pr-state` and `pr-review`). Coverage reaches 100% (except for 2 "else" paths that are not defined in the code).

Please tell me what do you think ;)

**Comment by paulmelnikow** [comment]
Thanks for the great tests! Can you clean up the merge conflict and I'll get this merged? So sorry for the delay.

**Comment by paulmelnikow** [comment]
I've proposed similar functionality for PR details and check state in #1114. It doesn't really overlap, since it's providing info about reviews, and a higher-level piece of status info. We should think about how to make the URL schemes work together.

**Comment by paulmelnikow** [comment]
If anyone would like to adopt this PR, please feel free to do so: grab the branch, add more commits addressing the comments, and open a new PR referencing this one. Will close in one month if no one has.

**Comment by ivanovyordan** [comment]
Hi. I will do it. In fact, I am almost done.

**Comment by paulmelnikow** [comment]
Closing in favor of #1207.

**Comment by tooomm** [comment]
@paulmelnikow 

Doesn't #1207 leaves out all of the `Pull Request Review` badge?

>**Github pull request review**
>
>URL pattern:
>
>`/github/pr-review/<user>/<repo>/<issueId>.<format>`
>
>The issue (which ID is provided in the URL) must be a pull-request.
>
>The following states are handled:
>
>    `inaccessible` (lightgrey) if the request failed or the response was not a json-formatted issue
>    `none` (lightgrey) if no review has been requested
>    `pending` (yellow) if there are still reviewers that didn't perform the review OR if no review has been approved or requested changes
>    `approved` (green) if at least 1 review has been approved and none requested changes
>    `need changes` (red) if at least 1 review requested changes
>
>*Note: Only the latest review of every reviewer is taken into account.*

**Comment by paulmelnikow** [comment]
Good catch. I'll put back the stale label and update the title. This PR is about to be closed for inactivity anyway so I'm just going to leave it closed.

If you're reading this and want this implemented, don't be discouraged. You can grab the commits from the pull request branch using `git fetch origin pull/806/head:pr-806`, address the comments, and reopen.

**Comment by ivanovyordan** [comment]
I will try to do the second part in a separate PR.

**Pull request closed without merging**
