### PR TITLE
restore version comparison updates #4173, run [pub Debian GemDownloads GitHubRelease GitHubTag Packagist]

### LINKED ISSUE #4172: Version issues with pub package firebase_core
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

The pub package **firebase_core**  shows version as v0.4.0+1 but on [pub.dev](https://pub.dev/packages/firebase_core) it's v0.4.0+9

pub package

:link: **Link to the badge**

https://img.shields.io/pub/v/firebase_core

:bulb: **Possible Solution**

### PR DESCRIPTION
**Pull request by calebcartwright**
Restores the version comparison updates originally made in #4173 that were temporarily reverted in #4252 

Also ref #4227 

Closes #4172

### CODE REVIEW

**Comment by paulmelnikow** [comment]
The deploy is running now. Let's give it a few days to bake under normal load before merging this. (Maybe until Wednesday?)

**Comment by calebcartwright** [comment]
> The deploy is running now. Let's give it a few days to bake under normal load before merging this and #4255. (Maybe until Wednesday?)

SGTM

**Comment by calebcartwright** [comment]
Do we want to try to merge/test these before the swarm of Dependabot updates tomorrow?

**Comment by paulmelnikow** [comment]
Hmm, maybe best to do the dependencies first and push this off until next week?

**Comment by calebcartwright** [comment]
> Hmm, maybe best to do the dependencies first and push this off until next week?

I'm good with whatever is easiest. If we defer on this til next week then I'd like to re-open the two associcated issues that were closed with the original merges of these two PRs though

**Comment by paulmelnikow** [comment]
Okay, that seems fine. As long as I can get a deploy done over the weekend I think these can go in on Tuesday. I don't want to hold these up but my time on this is a little limited so I think it makes sense to optimize for smoothness.

**Comment by calebcartwright** [comment]
> I don't want to hold these up but my time on this is a little limited so I think it makes sense to optimize for smoothness.

Definitely agree!

**Comment by PyvesB** [comment]
Is there anything still blocking us, or can we go ahead and merged this and #4255?

**Comment by calebcartwright** [comment]
> Is there anything still blocking us, or can we go ahead and merge this as well as #4255?

Yes this is still intentionally blocked and should not be merged. Both of these PRs tie back to the major capacity issue we had several weeks ago, where we suspect that one (or perhaps both) of the original changes may have been the root cause since the resource/capacity issues subsided after those changes were reverted. 

The point of these PRs is to attempt to re-apply the respective original changes in isolation to see whether or not they are indeed the culprits, and that requires them to be deployed and validated independently. I believe Paul's been exceptionally busy of late and we've simply not had the opportunity to be able to deploy them independently.

**Comment by paulmelnikow** [comment]
I have been super busy 🙃 

Do you want to try to merge one of these and I'll deploy it?

**Comment by calebcartwright** [comment]
SGTM!

**Comment by PyvesB** [comment]
@calebcartwright can we just merge this?

**Comment by calebcartwright** [comment]
> @calebcartwright can we just merge this?

@PyvesB  - I'll rebase to get the CI checks passing, but I don't have the bandwidth to go through the isolated deployment, monitoring, and potential rollback that we wanted to do with this. If anyone else does though then please feel free to go ahead

**Review by zx7o2 — APPROVED** [review]

**Comment by calebcartwright** [comment]
Realize this has been sitting for ages. To recap, this was reverted (along with #4254) because of a potential correlation with a performance event observed in our old OVH environment. I've had it parked for a while for various reasons, including some trial comparison periods we've been running with different http client libs.

This should be much easier to deploy in our current Heroku world given how easily we can roll back, though I think it probably warrants a reconsideration on whether it's necessary, and crucially, what the impact is on modifying the message values on existing badges.

**Comment by calebcartwright** [comment]
This has been parked for so long that I wonder if it's worth at least revisiting whether this is something we should/want to do. The diff is of course still as simple today as it was ~2.5 years ago, but I'm a little worried about unintended/undesirable side effects (and no I don't have anything specific just a general hesitation/concern)

Curious what others think, especially whether it'd be safer/better to try to make this conditional and wrapped behind a query param

**Comment by PyvesB** [comment]
I'd say let's go ahead and merge it. We can always revert again if this causes issues or user complaints, but I don't think we should complexity things with a query param until we've proven there's a definite need for one.

**Comment by calebcartwright** [comment]
Rebased so should be back in a ready-for-merge state.

Looking at the diff I can't conjure any rationale for this being a source of perf issues, though out of an abundance of caution would likely still advise whoever merges to promote to prod afterwards and monitor it for a day or so

**Comment by PyvesB** [comment]
I'm gonna merge this and keep a close-ish eye on production behaviour.

**Review by PyvesB — APPROVED** [review]

**Pull request merged**
