### PR TITLE
[Github] Optionally add name to release badge

### PR DESCRIPTION
**Pull request by dagwieers**
This PR makes it possible to add a name to the Github release badge.
This is useful if your project wants to show the various release of used
components.

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Hi! Thanks for the PR.

I'm not sure I understand it. What is the difference between `/release/qubyte/rubidium.svg`, `/release-name/qubyte/rubidium.svg`, and `/release-raw/qubyte/rubidium.svg`?

**Comment by dagwieers** [comment]
I modified try.html, so you can test it yourself and you would see this:

image

**Comment by dagwieers** [comment]
I will add service tests as soon as #1020 is merged. I want to make sure what I did was acceptable in #1020

**Comment by dagwieers** [comment]
@paulmelnikow I added service tests now, and I think this is ready for a re-review !

**Comment by paulmelnikow** [comment]
Ah, I gotcha.

Instead of adding more `-raw` badges, how about we just make `?label=` work as intended? So, for `/release-name/photonstorm/phaser.json` you'd use `/release/photostorm/phaser.json?label=phaser`. This would be like to the changes to the badge code that were done in #1090.

**Comment by dagwieers** [comment]
That is fine by me. I think it would have worked as well on #1020, I prefer modifying the query-string over messing with the URL TBH.

**Comment by paulmelnikow** [comment]
Would you like to update this PR to use `?label=`?

**Comment by paulmelnikow** [comment]
Ah, I guess this is already working. e.g.

https://img.shields.io/github/release/photonstorm/phaser.svg?label=phaser%20release

Let me know if I've misinterpreted the current state of affairs.

**Comment by dagwieers** [comment]
Perfect ! Thanks for following up on this.

**Pull request closed without merging**
