### PR TITLE
Discord social button added at very bottom of the page. #985

### PR DESCRIPTION
**Pull request by ritwickdey**
Quick Added https://github.com/badges/shields/issues/985 😄 

image

### CODE REVIEW

**Comment by ritwickdey** [comment]
Sorry, mistakenly I deleted the branch.

**Comment by paulmelnikow** [comment]
You're on fire! 🔥 🥇

**Comment by ritwickdey** [comment]
hahaha 😃 .... Actually, i was getting bored that day that why I grab 3-4 bugs (small) from this project & tried to fix that... 😄

**Comment by paulmelnikow** [comment]
Many hands make light work. Come spend your bored day here anytime!

**Pull request merged**
