### PR TITLE
add missing keys to private config schema

### LINKED ISSUE #4685: Drone configuration fails with "Check these paths: drone_token" while using a self-hosted instance of shields
Are you experiencing an issue with...

- [ ] [shields.io](https://shields.io/#/)
- [x] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

I have been trying to set up a self hosted shields, with my own GH Enterprise server and my own self hosted Drone CICD server. It seems to be working fine until I add `drone_token` as one of the configuration parameters. I get the following error: 

```
Configuration:
{ bind: { address: '0.0.0.0' },
  metrics: { prometheus: { enabled: false } },
  ssl: { isSecure: false },
  cors: { allowedOrigin: [] },
  persistence: { dir: './private' },
  services:
   { github:
      { baseUri: 'https://github.bhargavrao.com/api/v3/',
        debug: { enabled: false, intervalSeconds: 200 } },
     trace: false },
  profiling: { makeBadge: false },
  cacheHeaders: { defaultCacheLengthSeconds: 120 },
  rateLimit: true,
  handleInternalErrors: true,
  fetchLimit: '10MB' }
/usr/src/app/core/server/server.js:139
      throw Error(
      ^
Error: Private configuration is invalid. Check these paths: drone_token
    at new Server (/usr/src/app/core/server/server.js:139:13)
    at Object.<anonymous> (/usr/src/app/server.js:49:34)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

:link: **Link to the badge**

:bulb: **Possible Solution**

The error seems to be coming from [Line 90 in server.js](https://github.com/badges/shields/blob/master/core/server/server.js#L90), as there is no `drone_token` in that list. I am not really sure that this is the problem, though. 

Thanks for your help, and the shields product. I've been really liking it.

### PR DESCRIPTION
**Pull request by calebcartwright**
Refs #4685 

@Bhargav-Rao if you have the bandwidth and are willing to do a quick test of this branch with your Drone instance that'd be great! No worries if not though as this should do the trick.

### CODE REVIEW

**Comment by Bhargav-Rao** [comment]
Hey @calebcartwright, I can test it tomorrow. 

However, I do remember making just that change and it did not seem to work for me. Even though it got rid of that immediate error, I was not able to get it working completely. I was getting an unauthorized error. I also added [some logs in this method](https://github.com/badges/shields/blob/master/services/drone/drone-build.service.js#L91), and it printed out that the auth header was empty. (It was only after this, that I created the bug report)

I can understand that this might be a different bug. Let me know if I need to open a separate bug report for that, or if the current one will suffice.

**Comment by calebcartwright** [comment]
This update needs to be made anyway, but i'll update the PR description to not close the original issue.  

> I can understand that this might be a different bug. Let me know if I need to open a separate bug report for that, or if the current one will suffice.

If you get an error even after this change, feel free to post that on the original issue and we'll figure it out from there 👍

**Comment by Bhargav-Rao** [comment]
Hey @calebcartwright, sorry for the delayed response. I was a bit held up on other stuff. 

I tried it out today with the image `shieldsio/shields:next` instead of building my own, and drone seemed to be working correctly. You can close the original issue (#4685). as "fixed" now. Thanks for the help!

**Comment by calebcartwright** [comment]
No worries, thanks for following up and letting us know!

**Pull request merged**
