### PR TITLE
Allow token authentication on github

### PR DESCRIPTION
**Pull request by yannickglt**
This allows connecting to github using a private token, accessing to private and enterprise github repositories.

### CODE REVIEW

**Comment by espadrine** [comment]
Thanks for this contribution!

There are other places where we set GitHub's client_id and client_secrets in other badges; search for `gh_client_id` to find them all.

**Comment by yannickglt** [comment]
Hi, I made a mistake. In fact, using a private token allows to connect to private github repositories (e.g.: for github enterprise accounts).

**Comment by espadrine** [comment]
Could you add a comment before the line explaining how to obtain and set `gh_token`?

**Comment by yannickglt** [comment]
Sure! That's done.

**Comment by espadrine** [comment]
Thanks a lot!

**Pull request merged**
