### PR TITLE
[Travis] Add travis-ci.com support

### LINKED ISSUE #1674: Travis-ci.com support
Travis CI starts merging open source and private repositories on travis-ci.com. Does shields.io support travis-ci.com instead of travis-ci.org?

### PR DESCRIPTION
**Pull request by ivandelabeldad**
Add new badges for `travis-ci.com` using two new possible paths (maintaining consistency with travis-ci.org badges): 

`/travis/com/USER/REPO.(svg|png|gif|jpg|json)`
`/travis-ci/com/USER/REPO.(svg|png|gif|jpg|json)`

close #1674  #1710

### CODE REVIEW

**Comment by RedSparr0w** [comment]
Thanks for the PR!

But could you merge this with the current travis.org implementation please?
<details>
<summary>As there is only a couple lines difference.</summary>

[`com`](https://github.com/ivandelabeldad/shields/blob/5c5a28d27338c18af2df2063975224b7d7713647/server.js#L388-L429) [`org`](https://github.com/ivandelabeldad/shields/blob/5c5a28d27338c18af2df2063975224b7d7713647/server.js#L431-L472) [`diff`](https://www.diffchecker.com/gbrLZ9EW)
```diff
-camp.route(/^\/travis(-ci)?\/([^/]+\/[^/]+)(?:\/(.+))?\.(svg|png|gif|jpg|json)$/,
+camp.route(/^\/travis(-ci)?\/com\/([^/]+\/[^/]+)(?:\/(.+))?\.(svg|png|gif|jpg|json)$/,
cache(function(data, match, sendBadge, request) {
  var userRepo = match[2];  // eg, espadrine/sc
  var branch = match[3];
  var format = match[4];
  var options = {
    method: 'HEAD',
-    uri: 'https://api.travis-ci.org/' + userRepo + '.svg',
+    uri: 'https://api.travis-ci.com/' + userRepo + '.svg',
  };
  if (branch != null) {
    options.uri += '?branch=' + branch;
  }
  var badgeData = getBadgeData('build', data);
  request(options, function(err, res) {
    if (err != null) {
      log.error('Travis error: ' + err.stack);
      if (res) { log.error(''+res); }
    }
    if (checkErrorResponse(badgeData, err, res)) {
      sendBadge(format, badgeData);
      return;
    }
    try {
      var state = res.headers['content-disposition']
                     .match(/filename="(.+)\.svg"/)[1];
      badgeData.text[1] = state;
      if (state === 'passing') {
        badgeData.colorscheme = 'brightgreen';
      } else if (state === 'failing') {
        badgeData.colorscheme = 'red';
      } else {
        badgeData.text[1] = state;
      }
      sendBadge(format, badgeData);

    } catch(e) {
      badgeData.text[1] = 'invalid';
      sendBadge(format, badgeData);
    }
  });
}));
```
</details>

**Comment by ivandelabeldad** [comment]
Merged done.
Thanks to you for maintain this amazing project!

**Comment by ivandelabeldad** [comment]
I've read that you're trying to implement `const` and `let` instead of `var`. So because I've changed travis integration I've updated it in this same pull request. Also the `travis-php` integration now use template literals (so much easier to read).

**Comment by paulmelnikow** [comment]
@ivandelabeldad Do you have a moment to address the review comment? It would be great to get this merged. 😁

**Comment by paulmelnikow** [comment]
Yea, that's what I noticed that was outstanding.

**Comment by simonepri** [comment]
@Pyves When this will go online?

**Comment by PyvesB** [comment]
@simonepri it has not yet been deployed, as indicated by the badge posted by our shields-deployment bot. We've got ongoing work to make deployments smoother (#1774), so I'll expect this to go live sooner rather than later. 😉

**Pull request merged**
