### PR TITLE
[pypi] Implement Plone versions badge

### PR DESCRIPTION
**Pull request by ericof**
This PR implements #8246 using the PyPI api.

### CODE REVIEW

**Comment by ericof** [comment]
Hello there, any idea why the tests failed?

**Comment by calebcartwright** [comment]
> Hello there, any idea why the tests failed?

Not from looking at the CI output (which is admittedly and suspiciously empty). Are the tests passing for you locally? 

```
npm run test:services -- --only=pypi
```

**Comment by ericof** [comment]
@calebcartwright I just re-run the tests locally and noticed it was flaky due to a change on the [PyPI API](https://warehouse.pypa.io/api-reference/json.html).
Hopefully, this was the cause of the error.

**Comment by ericof** [comment]
New error, but not sure what it means

**Comment by calebcartwright** [comment]
I've still not looked at this in detail, but I wouldn't have expected the addition of this badge to require modification to unrelated unit and service tests for other badges.

> noticed it was flaky due to a change on the [PyPI API](https://warehouse.pypa.io/api-reference/json.html).

It does seem like we've got some recurring test failures with `invalid response data` being quite prevalent which does indeed typically indicate an upstream change. However, I'm a bit surprised we haven't had any bug reports about this yet :thinking: 

If you feel like there's an existing bug (and I suspect something may be afoot too), it would be best to address that in a separate standalone PR so we can push that through independent of adding a new badge. Would you be up for doing that?

**Comment by ericof** [comment]
@calebcartwright I could break this PR into 2: One for the PyPI issue and another one for the new badge.

The issue for the PyPI API change is #8250

I will close this PR for now

**Pull request closed without merging**
