### PR TITLE
Add required attribute to <input> tags

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Help remind users to enter essential info before badge being generated and then failed.

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Hi, thanks for this! I like this idea, however some of the logic may need to be adjusted. For one, `label` is optional on both the static badge and the dynamic badge. There may be others as well. Would you like to take another pass through and check? If not, no problem, I or another maintainer can tackle it.

**Comment by PeterDaveHello** [comment]
Thanks @paulmelnikow, I'm not 100% sure but I removed the attribute for `label` ;)

**Comment by PeterDaveHello** [comment]
BTW, the `Make Badge` button can't be clicked if `label` is empty.

**Comment by paulmelnikow** [comment]
I appreciate the motivation here. To be merged this will need a bit more care to go into the logic and the cases for each modal. If you want to take that on, feel free to reopen!

**Comment by PeterDaveHello** [comment]
I don't have a reopen button ...

**Comment by paulmelnikow** [comment]
I meant you can open a new PR, though I just reopened it. This conflicts with master so I’m not sure the branch is any help.

**Comment by paulmelnikow** [comment]
Feel free to open a new PR if you'd like to resume!

**Pull request closed without merging**
