### PR TITLE
[GithubIssues] Add examples for count github pull requests closed by label

### LINKED ISSUE #2536: Badge request: GitHub closed PRs/Issues by label
:clipboard: **Description**
GitHub badge exactly the same as the current closed issues/pull requests badges with by the label filtering ability of the open issues/pull request badges.

:link: **Data**
Presumably the same place as the existing badges?

### PR DESCRIPTION
**Pull request by MonliH**
This PR adds two more examples, as described by the title. It seems this functionality was always supported, but not documented.
For example, with the current API this works already:
`https://img.shields.io/github/issues-pr-closed/badges/shields/service-badge`
Closed PRs

Closes #2536.

It also changes the `pullrequests` search tag to `pullrequest` for consistency.

### CODE REVIEW

**Comment by MonliH** [comment]
How can I rerun tests? (I forgot to add `[Github]` to the title)

**Comment by calebcartwright** [comment]
> How can I rerun tests? (I forgot to add `[Github]` to the title)

You won't have access in Circle to manually re-run the workflow, but no worries. In cases like this we'll often do so on your behalf, and you can always update your branch either by rebasing or merging in latest changse

**Comment by calebcartwright** [comment]
I think we'll need two additional example listings for closed issues with labels to be able to close #2536 in addition to the closed PRs which are now covered

**Comment by MonliH** [comment]
Alright, will add those examples too.

**Review by calebcartwright — APPROVED** [review]
Thank you! The changes LGTM, though for future reference it's easier for reviewers if you can rebase your fork on the upstream or otherwise start from a clean branch state. This is often easiest if you also leverage topic branches within your fork vs. working directly off the default branch in your fork

**Pull request merged**
