### PR TITLE
[travis] Get tested PHP version from Travis CI

### PR DESCRIPTION
**Pull request by peter-gribanov**
I rewrite PR #1255

Badge for Symfony 2.8.0

Tested

Badge for Symfony 4.0.0

Tested

Attention
======

Testing [Yii](https://github.com/yiisoft/yii) on HHVM starts, but [fails](https://travis-ci.org/yiisoft/yii/builds/265525345) and this affects the result.

Tested

And in .travis.yml #1258 badge it is not visible:

PHP

### CODE REVIEW

**Comment by peter-gribanov** [comment]
[summary table](https://github.com/badges/shields/issues/819#issuecomment-343502743)

**Comment by peter-gribanov** [comment]
Build failed because to exceeding [GitHub limit](https://developer.github.com/v3/#rate-limiting).

**Comment by paulmelnikow** [comment]
Just a heads up that the test failure is a timeout in this badge request. It's not related to Github.

```
    gets the package version of yii
      1) 
	[ GET http://localhost:1111/travis/php-tested/yiisoft/yii.json ]
```

**Comment by paulmelnikow** [comment]
As I wrote [here](https://github.com/badges/shields/pull/1255#issuecomment-350092069), I appreciate the work you put into this. This badge is different from the ones you added in #1258 or #1372. However this makes a lot of requests so it's many times more expensive, and in my estimation the slight difference in the result isn't worth all the extra overhead. If there is demand for this badge from a lot of other people I'm open to reconsidering. I'm also open to adding Composer if you'd like.

**Pull request closed without merging**
