### PR TITLE
fix docker command, add NetflixOSS OSSMETADATA osslifecycle support

### PR DESCRIPTION
**Pull request by aspyker**
Add support for github OSSMETADATA osslifecycle.  This is heavily used by Netflix OSS and is being considered by use across the TODO Group (Facebook, Yahoo, Microsoft, etc.).

also, fixed the command for docker ... didn't seem right as is

### CODE REVIEW

**Comment by aspyker** [comment]
Can someone ( @espadrine ? ) tell me if this will be merged before I resolve merge conflicts?

**Comment by espadrine** [comment]
Hi @aspyker, sorry for the wait!

We have a similar existing badge called "maintenance", which flags projects that are not updated after a year, but it is likely more contrived, which makes me very interested in this patch.

We have a way to document badges when they are not explicit, which I believe is the case for this badge. The way you add documentation in `try.html` is by adding a div in `div#documentation`, and referencing its `id` in a `data-doc` field in the `th` of the name of the example badge.

I'd be fine with rebasing this patch and adding the documentation, but I'd like to be sure what to put in.

Do you have a link documenting the format of the `OSSMETADATA` file?

(Future self: I reviewed the code, it looks good.)

**Comment by aspyker** [comment]
@espadrine sorry I haven't gotten back to you more quickly.

We haven't documented the format of the file, but expect to add to it.  Also, the TODO Group (many large corporations doing open source) are working to define a common format across them:

https://groups.google.com/forum/#!topic/todogroup/dyeb7Ye36zs

I expect that over time, this format would be better defined by a group beyond Netflix and we'd deprecate our current OSSMETADATA format.  Until that time, we'll have the format we have now and work to add to it.

**Comment by espadrine** [comment]
Thanks! Keep me in the loop on the evolution of the TODO group.

**Comment by aspyker** [comment]
Thanks @espadrine.  Will do.  Do you know when this will be deployed on shields.io?

**Comment by espadrine** [comment]
It is live now. Thanks again!

**Pull request merged**
