### PR TITLE
feat($logos): add new logo

### PR DESCRIPTION
**Pull request by rios0rios0**
package of logos included:
- added Coveralls.io logo

### CODE REVIEW

**Comment by RedSparr0w** [comment]
Thanks for taking the time to create this PR,

But as per our [contributing guidelines](https://github.com/badges/shields/blob/master/doc/logos.md#contributing-logos):
>Our preferred way to consume icons is via the SimpleIcons logo. As a first port of call, we encourage you to contribute logos to the [SimpleIcons project](https://github.com/simple-icons/simple-icons). Please review their [guidance](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md) before contributing.

If you could try and get this logo merged there first would be preferred.

**Comment by rios0rios0** [comment]
@RedSparr0w I tried find it on the site. But, I not contributed with the project.
I searched on the https://simpleicons.org/, and the Coveralls.io logo, there is not exists there.
Then, I got it in the GitHub marketplace, and I converted the "png" file to "svg" with the conditions in here: https://github.com/badges/shields/blob/master/doc/logos.md.

The, I followed the compression instructions.
But, I have to contribute on the Simple Icons project? That is it?

**Comment by calebcartwright** [comment]
> But, I have to contribute on the Simple Icons project? That is it?

Yes, please first try to get the Coveralls logo submitted to Simple Icons. If for some reason we can't get that Coveralls logo merged over at Simple Icons, then we can revisit. Thanks!

**Comment by chris48s** [comment]
:+1: Coveralls is [popular enough](https://www.alexa.com/siteinfo/coveralls.io) for inclusion in simple-icons and it is essentially a 1-colour logo. This should be fair game for a PR to simple-icons and that would be our ideal way to consume this logo.

**Pull request closed without merging**
