### PR TITLE
Updates *GPL licenses to new SPDX ids and adds additional aliases, run service tests for [apm aur bowerlicense cocoapodslicense cpanlicense cran crates ctan dublicense eclipsemarketplacelicense githublicense hexpm npmlicense packagistlicense pypilicense]

### PR DESCRIPTION
**Pull request by chintal**
[SPDX v3.5](https://spdx.org/licenses/) changes the IDs for GPL, LGPL, and AGPL licenses. This PR changes the list of licenses in the spexLicenceIds list to conform to the current standard, while adding the old forms to the aliases list to make sure nothing breaks.

Additionally, the following aliases are added based on the form in which these licenses are represented in [Python's classifiers](https://pypi.org/pypi?%3Aaction=list_classifiers). These old classifiers have informed python users and developers for years, and it is more common to come across one of those formats (ex. `GPLv3+`) in python packages than spdx licence IDs, as reported (by me) in #3685 .

### CODE REVIEW

**Comment by PyvesB** [comment]
I believe you forgot to run `npm run prettier` to get the formatting right. 😉

**Comment by chintal** [comment]
Fixed it. Took me a while to swallow how many dependencies npm has.

**Comment by calebcartwright** [comment]
Oops! Thanks for fixing that service name @PyvesB

**Comment by balibebas** [comment]
I cannot attach screenshots here like I can in Gitea using a 📱browser but wanted to mention how pleased I am my AGPL-3.0-or-later badge [shows up with color](https://www.npmjs.com/package/after-dark) now. Thanks, @chintal.

**Pull request merged**
