### PR TITLE
fix: support logoColor to shield icons.

### LINKED ISSUE #6208: logoColor is ignored for specific icons
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**
Some specific logos/icons seem to ignore the `logoColor` override when applied.
In my case does this happen with the `paypal` logo.

The SVG icon provided by SimpleIcons seems to be a single-coloured SVG.

- https://github.com/simple-icons/simple-icons/blob/develop/icons/paypal.svg
- https://simple-icons.github.io/simple-icons-website/icons/paypal.svg

I can't tell if the icon actually is single-coloured tho, or if either shields.io or SimpleIcons override this default SVG colouring when requested.

:link: **Link to the badge**

Example:
https://img.shields.io/badge/Donate%20with-PayPal-blue?logo=paypal&logoColor=white

Result:
badge

:bulb: **Possible Solution**

If any override is used to alter the colour, or if the PayPal icon is actually a different one (Not from SimpleIcons), should it either respect the logoColor option, or not have the override at all.

If this is a SimpleIcons bug, let me know and I'll report it to them.

### PR DESCRIPTION
**Pull request by regseb**
This pull request fixes #6208 (and its duplicates: #7576, #8139, #8248) and finds a compromise for [_Simple Icons or custom Shields logos?_ #7684](https://github.com/badges/shields/issues/7684).

- Without `logoColor` query parameter: display [custom Shields logo](https://github.com/badges/shields/tree/22380c5e9435e2a59e236d2a58ff55d1db7c8f1e/logo) multiple colors;
- With `logoColor` query parameter: display [Simple Icon](https://github.com/simple-icons/simple-icons) by changing the color.

If you want:

- multiple custom Shields logo multiple colors: `https://img.shields.io/badge/shields-gitlab-blue?logo=gitlab`
- orange Simple Icon with the default color (you must specify color): `https://img.shields.io/badge/shields-gitlab-blue?logo=gitlab&logoColor=FC6D26`
- white Simple Icon with specific color: `https://img.shields.io/badge/shields-gitlab-blue?logo=gitlab&logoColor=white`

There is one exception for the [Dependabot logo](https://github.com/badges/shields/blob/cf7b76d5a68f3edf0d5c4c929b3fceed0f046c8e/logo/dependabot.svg). The custom Shields logo version is monochrome and its color is customizable. With `logoColor` query parameter, it is the custom Shields logo that is displayed by changing its color.

### CODE REVIEW

**Comment by chris48s** [comment]
I haven't been massively following all of the discussion in https://github.com/badges/shields/issues/7684 but I think I'd be fine with this as a solution: Seems like a reasonable way to reduce our support burden without taking on much additional complexity (which are really the 2 things I think we want to optimise for here).

The one issue is `travis` (because in simpleicons the slug is `travis-ci`).

**Comment by calebcartwright** [comment]
> I haven't been massively following all of the discussion in #7684 but I think I'd be fine with this as a solution: Seems like a reasonable way to reduce our support burden without taking on much additional complexity (which are really the 2 things I think we want to optimise for here).
> 
> The one issue is `travis` (because in simpleicons the slug is `travis-ci`).

IMO this isn't _directly_ related to #7684 and the fundamental question of whether users still want the custom logos. I view this as simply adding new functionality to Shields to give a minor assist to users that want to use the SI version instead of one of the corresponding ten custom logos we have, without having to base64 encode the SI icon themselves to be used with `?customLogo`. I realize we could use this to decide to settle the matter since both camps could rely on us to do their logo work for them, but just want to underscore that we could still drop the custom logos before or even after potentially making a change like this.

There's also the potential for a small slice of our existing users to be impacted by a change like this, if they happen to have a `logoColor` param in their badge urls. That's most likely a fairly small portion given that param is a functional no-op today, but it's still the case that the same badge url would produce a different badge and potentially require unhappy users to update their badge urls. Obviously that doesn't need to be treated as a hard blocker, but it's something to be cognizant of, and transparent about, if we were to move forward.

**Comment by chris48s** [comment]
> IMO this isn't directly related to https://github.com/badges/shields/issues/7684

Yeah - sorry. I think @regseb 's description:

> This pull request fixes https://github.com/badges/shields/issues/6208 (and its duplicates: https://github.com/badges/shields/issues/7576, https://github.com/badges/shields/issues/8139, https://github.com/badges/shields/issues/8248) and finds a compromise for https://github.com/badges/shields/issues/7684.

is better.

> but I just wanted to also underscore that we could still drop the custom logos before or even after potentially making a change like this

Agreed. We could. Tbh though, as much as I'd like to bin them all and simplify things, I think #7684 tells us there isn't really a clear consensus for it.

---

Given the point we're starting from, It seems like merging some variation of this solution (accepting it probably needs an additional special-case for the travis logo) would:

- reduce support requests/confusion like in the linked issues
- not add much additional complexity to the code
- keep users who like the custom logos happy
- keep users who want to use `logoColor=` happy
- maybe require some existing users to remove an unwanted/spurious `logoColor` param from some existing badge URLs
- not make anything else worse than it already is (I think?)

which seems like a pretty decent set of tradeoffs to me, all things considered.

**Comment by calebcartwright** [comment]
I think I largely agree, though do you think it'd be better to shift the discussion over to #6208 or to at least recap? Both so that those involved/subscribed to that convo can see this articulated position and for posterity so that thread will contain all relevant parts?

**Comment by regseb** [comment]
@chris48s @calebcartwright Is there anything I should do to advance this pull request?

**Comment by chris48s** [comment]
I think the thing that stalled this is not "the code is bad and it needs changes", its more "do we agree this idea is the right solution?". Personally, I think yes it is.

@calebcartwright - I'm going to invoke your suggestion about making decisions here and say: If you want to say "no its not", object in the next week.

@regseb - In terms of the code, the one thing we'd need to do is add a special case to fix travis. This one breaks because our custom logo is `travis` and in simpleicons the slug is `travis-ci` (`?logo=travis&logoColor=red` show no logo at all). If you want to do it straight away, fine but if you want to hold off on making that change then that's reasonable. I don't like to see people spend more time than needed on a PR that doesn't get merged.

@SnoozeThis wait 7 days

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/bRTxKqHPz6o) I will wait until Tue, 29 Nov 2022 16:50:08 UTC and then add a comment.

**Comment by regseb** [comment]
I handled the Travis case.

**Comment by calebcartwright** [comment]
> @calebcartwright - I'm going to invoke your suggestion about making decisions here and say: If you want to say "no its not", object in the next week.

Agreed. Hopefully already evident from the above thread, but I'm not personally going to object. I do think the code will need another pass through (and I can't promise I'll have a chance to do so particularly given the holiday this week in the US), and would also need some accompanying items e.g. solid documentation, both in readme docs and on the site, and a communication plan

**Comment by chris48s** [comment]
The code is fine so far and I'm happy to review any further commits.

Documentation is a good shout - thanks :+1:

At the moment we don't mention anything about `logoColor` in https://github.com/badges/shields/blob/master/doc/logos.md so I am fine with leaving that as it is.

We do need to update

https://github.com/badges/shields/blob/c5476b4dd506e4b205311c4a3e1cbc0d10932e9f/frontend/components/usage.tsx#L362-L372

and

https://github.com/badges/shields/blob/c5476b4dd506e4b205311c4a3e1cbc0d10932e9f/frontend/pages/endpoint.tsx#L210-L214

Also the comment in

https://github.com/badges/shields/blob/c5476b4dd506e4b205311c4a3e1cbc0d10932e9f/core/base-service/coalesce-badge.js#L9-L34

could do with an update.

In terms of communicating the change, I think posting a comment in the various linked issues when we merge this and close them will be fine. https://github.com/badges/shields/issues/7684 is already pinned and it can stay pinned. I've not drafted a post yet, but I'm happy to cover that.

**Comment by regseb** [comment]
I have updated the documentation. English is not my first language, so I'm open to any changes.

**Review by chris48s — APPROVED** [review]
Going to merge this with a 1 word tweak to the docs. I'll update the issue threads once I've deployed

**Comment by SnoozeThis** [comment]
Resolved.

**Pull request merged**
