### PR TITLE
Fix invalid Cache-Control header, run [Endpoint]

### LINKED ISSUE #5138: Invalid HTTP headers
- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

**Description**

Few HTTP headers are incorrect.
https://redbot.org/?uri=https%3A%2F%2Fimg.shields.io%2Fpackagist%2Fdt%2Fszepeviktor%2Fphpstan-wordpress.svg

kép

Please consider fixing them.
Thanks.

**Link to the badge**

https://img.shields.io/packagist/dt/szepeviktor/phpstan-wordpress.svg

### PR DESCRIPTION
**Pull request by szepeviktor**
Fixes #5138

### CODE REVIEW

**Comment by szepeviktor** [comment]
Should we have a class handling HTTP headers?

`name => values-array`

**Comment by paulmelnikow** [comment]
This looks good to me!



> Should we have a class handling HTTP headers?
> 
> `name => values-array`

I'm not sure what you mean by that!

**Comment by szepeviktor** [comment]
> I'm not sure what you mean by that!

Now I see plain string in place of HTTP header values.

A JSON example.

```json
{
  "Content-Lenght": 0,
  "Cache-Control": {
    "max-age": 120,
    "smax-age": 120
  }
}
```

**Comment by paulmelnikow** [comment]
They'd still have to be converted to the longer versions. It might simplify the tests but at the cost of another abstraction and another conversion function to test. Unless there's something built in that I'm not aware of which converts `{"max-age": 120, "smax-age": 120 }` into the right thing.

Fortunately we make pretty limited use of HTTP headers in Shields. Most of that work happens right in this file, I think.

**Comment by szepeviktor** [comment]
Yes, it would come with a high cost.

**Pull request merged**
