### PR TITLE
New Favicon - Update favicon.png

### LINKED ISSUE #1497: Provide high resolution favicon
Currently the `shields.io` favicon is low resolution only.

But current browsers like Firefox use big logo information in their top visites sites section.
There is also no image support for links placed on mobile homescreens (android +ios).

On basically all high resolution screens the operating system has to scale things up so it gets even worse.

### PR DESCRIPTION
**Pull request by sidhyatikku**
### New favicon
* This PR refers to #2139 #1497 @RedSparr0w @chris48s 
* As noted earlier, I've uploaded `36px X 36px favicon`
* Apologies for the previous rebasing error.

favicon

closes #1497

### CODE REVIEW

**Comment by sidhyatikku** [comment]
Logo is fully centered and is 36px X 36px

**Comment by RedSparr0w** [comment]
>I think in order to resolve the linked issue we will need a few different icon sizes/types and <link> headers to serve relevant icon sizes in different contexts. There's a good stackoverflow post on this here: https://stackoverflow.com/a/25961390

Relevant parts of linked stackoverflow post:
>### Question:
>What is the best practice for creating a favicon on a web site?


>### First method: Use a favicon generator
>If you want to get the job done well and quickly, you can use a [favicon generator](http://realfavicongenerator.net/). This one creates the pictures and HTML code for all major desktop and mobiles browsers. Full disclosure: I'm the author of this site.
>
>Advantages of such solution: it's quick and all compatibility considerations were already addressed for you.

From the favicon generator page:
>Your picture should be 260x260 or more for optimal results.

Based on that, I think the previous 1000 x 1000 icon you uploaded would work better for this, once it has been centered.

**Comment by sidhyatikku** [comment]
@RedSparr0w I've added `1000px X 1000px` centre aligned logo.
screen shot 2018-11-06 at 3 37 22 pm
favicon

**Comment by RedSparr0w** [comment]
Thanks, but we still will need a few different icon sizes/types and headers to serve relevant icon sizes in different contexts.

>If you want to get the job done well and quickly, you can use a [favicon generator](http://realfavicongenerator.net/). This one creates the pictures and HTML code for all major desktop and mobiles browsers

**Comment by sidhyatikku** [comment]
Should I commit in the PR?  I've uploaded the zip here.
[favicomatic (2).zip](https://github.com/badges/shields/files/2556923/favicomatic.2.zip)

**Comment by RedSparr0w** [comment]
👍 Yes please, and if you could also update the `<link>`'s in the header

**Comment by paulmelnikow** [comment]
@RedSparr0w Would you be up for wrapping this up?

**Comment by paulmelnikow** [comment]
If anyone wants to take this on, feel free to grab these commits and reopen!

**Pull request closed without merging**
