### PR TITLE
Autoselect badge link when clicking it on the homepage

### PR DESCRIPTION
**Pull request by WouterDS**
Personally I found it kinda annoying when manually selecting thm

### CODE REVIEW

**Comment by espadrine** [comment]
Interesting! Thanks a lot!

I think we can deal the same treatment to the menu that appears when we click on the badge. Clicking on the markdown code should select it. Right now, they're not `<code>`, they're `<input>`, because it was easier to style and prevent them from taking all the space while easily allowing people to ctrl+a to select it all, but with that patch, it becomes possible to switch them to `<code>`. Or, if you want, we can keep them as `<input>` and select them when we click it.

However, your event listener never gets called because we do `stopPropagation()` in the markup dialog.

Do you want to add that in, or fix this in any way?

**Comment by WouterDS** [comment]
Switched the last 2 inputs with code fields and fixed binding, should be working now (tested it, it works).

**Comment by jenssegers** [comment]
Looks good! :+1:

**Comment by espadrine** [comment]
Thanks. It doesn't quite work right, as now updating the text fields don't update the contents of the markup fields in the dialog box.

I didn't dig into why it fails, since your commits seem to erase the whole file, making the diff unreadable. Please don't do that. Please remove the commit that “fixes” the markup (8878252). Such an operation would deserve a separate pull request. As an aside, a PR with that commit would not be accepted, as there are only a [handful](https://validator.nu/?doc=http%3A%2F%2Fshields.io%2F) of things that make the page fail HTML validation, and adding a `<head>` or increasing indentation is not it — in fact, your changes double the number of validation errors.

In a pull request, do one thing, and do it well.

Therefore, I'd also like you to squash your commits together with a `git rebase -i 9ffba57^^`.

**Pull request closed without merging**
