### PR TITLE
Add [GitHubTotalCommits] Badge

### PR DESCRIPTION
**Pull request by YashTotale**
Adds the GitHub Total Commits Badge discussed in #6070

### CODE REVIEW

**Comment by calebcartwright** [comment]
> I'm running into this error every time I try running npm start:

You can ignore the token pool error, or just add a GH_TOKEN to your local env: https://github.com/badges/shields/blob/master/doc/server-secrets.md#github (this is typically a good idea anyway if you're developing badges for GitHub)

As for the rest, looks like you've got a syntax error which is causing errors in Heroku, tests, and presumably your local env as well:
```bash
/tmp/build_0e08ee14_/services/github/github-total-commits.service.js:87

    const json = await this.fetch({ user, repo, branch: branch ?? 'HEAD' })

                                                                ^

SyntaxError: Unexpected token '?'
```

Try just adding 'HEAD' as a default value for the param above on the function signature

**Comment by YashTotale** [comment]
The tests that are failing seem to be failing for the `master` branch as well. The [daily service tests](https://app.circleci.com/pipelines/github/badges/daily-tests) show this. 
Please let me know if I have anything left to add or fix.

**Comment by calebcartwright** [comment]
Have adjusted the title so that only the tests for this service are executed (as opposed to the entire GitHub suite).

From the perspective of the end user experience, I'm not convinced that it makes sense to expose this as a separate badge/separate route. The existing GitHub Commit Activity badge presents users with the option to choose the interval, and I feel like this is just another interval (total/all time), much like the various download badges that allow users to select between the all time download count or count during interval period.

Under the hood, I know the target implementation for this is quite different than the existing commit badges, in no small part because the former is leveraging the newer v4 API option while the latter are still using the older v3 APIs. However, I don't we want those internals to leak through and drive the user experience and add a separate route.

I would rather see the existing commit activity service class refactored to take fully take advantage of the graphql/v4 approach. If it seems like it would be too much to refactor that and add support for total/all time interval in a single PR, then that's alright, but I'd still prefer to see the total interval incorporated on the existing badge route by adding some conditionals to that class to use different fetch/transform logic when the interval is `t` (for total/all time)

**Comment by PyvesB** [comment]
I agree with @calebcartwright 's reasoning. @YashTotale is this something you would be keen on working on? :)

**Comment by YashTotale** [comment]
@PyvesB, I would love to work on this, but probably won't be able to get to it for a while. If anyone else wants to give it a shot, feel free to do so. :)

**Comment by PyvesB** [comment]
Thanks for the update. Will close this for now then. We can always reopen if need-be. 😉

**Pull request closed without merging**
