### PR TITLE
Add 2 dependencies badge, can warn about security issue

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by espadrine** [comment]
Dependencies are a very harsh thing for this project, because it needs to combine things that don't usually work well together. Therefore, the default situation would be to have a warning there, which would not provide useful information. Please remove it.

On the other one, the security one is very useful!

**Comment by PeterDaveHello** [comment]
I don't understand, the security one is Dependencies, but you say to remove it?

**Comment by espadrine** [comment]
I was talking about devDependencies. I suppose the dependencies one, while my comment does apply to it, also does give information about security, which is valuable. It would still pretty much always be red, right?

**Comment by PeterDaveHello** [comment]
If we upgrade the dependencies in period, I think it will at least be yellow. 
I am going to remove devDependencies badge now.

**Comment by PeterDaveHello** [comment]
@espadrine Updated.

**Comment by espadrine** [comment]
Thanks!

**Pull request merged**
