### PR TITLE
Store raster badges in the LRU cache

### PR DESCRIPTION
**Pull request by espadrine**
In ef1a5159, the switch to using imagemagick made a faulty use of the library by
listening for an 'end' event that is never raised. As a result, the cache was
never populated.

In d985f81f, a fix that takes care of the fact that the previously mentioned
dead code relies on a non-existent variable caused it to kill the server when a
raster badge is requested twice, as what it stored in the cache was the pipe
transmitting chunks, not the chunks themselves, and the pipe (a Socket object)
cannot be subsequently sent through a pipe. The following error occured instead:

    events.js:163
          throw er; // Unhandled 'error' event
          ^

    TypeError: Invalid non-string/buffer chunk
        at chunkInvalid (_stream_readable.js:395:10)
        at readableAddChunk (_stream_readable.js:150:12)
        at DataStream.Readable.push (_stream_readable.js:136:10)
        at DataStream._read (/home/m/shields/lib/svg-to-img.js:45:21)
        at DataStream.Readable.read (_stream_readable.js:350:10)
        at resume_ (_stream_readable.js:739:12)
        at _combinedTickCallback (internal/process/next_tick.js:80:11)
        at process._tickDomainCallback (internal/process/next_tick.js:128:9)

@paulmelnikow Could you have a look, please?

### CODE REVIEW

**Comment by espadrine** [comment]
(This has been deployed to stop the crashes.)

**Comment by espadrine** [comment]
If you have time, I'd love it.

**Comment by paulmelnikow** [comment]
Sure. Will aim for tomorrow.

**Comment by paulmelnikow** [comment]
I took a stab at this. I was able to reproduce the problem in a test, however I'm having two issues getting the tests to pass.

First, piping from `DataStream` to the [in-memory writable stream implementation I'm using](https://www.npmjs.com/package/memory-streams) isn't working correctly. Piping to `process.stdout` isn't working either, which is puzzling. It's as if `DataStream` only works with ScoutCamp.

I could swap in the memory-streams readable stream implementation, which seems to fix the issue.

Second, since there isn't a good way to detect when the `DataStream` has closed, it's difficult to invoke the callback at the appropriate time. Unfortunately memory-streams hasn't solved that problem either.

Here's what I'm thinking: given the chunks coming from imagemagick are getting stored memory and then tucked into a cache, svg2img could as easily return a buffer via callback. Streaming is just making it more complex. (And trickier to test!)

**Comment by paulmelnikow** [comment]
Implemented in this branch: https://github.com/badges/shields/compare/master...paulmelnikow:raster-badges-in-lru-cache-2

**Comment by espadrine** [comment]
Ok. So, 06195ea doesn't pass the tests?

I put a few comments on the commits.

I am noticing some ENOMEM errors upon imagemagick's spawn, and, rarer, OOM kills. I started performing some tracking on one server; the first ENOMEM occurs when the cache is 34.7% filled. I'll continue the investigation to study the cache further. We may need to reduce it or remove it.

**Comment by espadrine** [comment]
More information: the cache gets filled to ≥ 30% with a cache hit rate of 4.7 (= num hits / num misses). Then the ENOMEM occur (as a result, beyond that point, the cache does not get filled up further). Eventually, the OOM-killer does its job.

So, I added a commit to change the capacity of the cache. I'll keep monitoring the results.

**Comment by paulmelnikow** [comment]
> So, 06195ea doesn't pass the tests?

That's right. Against master the first test passes and the second one caused the crash you described. Rebased on this branch, they both fail, the first because of a missing callback and the second because of the issues I mentioned.

I'll address your comments on the commits.

Interesting about the OOM issues. Are these issues new since caching was enabled?

It's possible that concatenating the buffers will help, though it depends whether in practice there are more than one chunk per image.

In the past I've also tweaked Node's `max_old_space_size` setting to make sure the garbage collector runs before the memory usage grows too high. That setting lets you configure a tradeoff between memory usage and performance, and affects when the garbage collector runs. Might be worth a shot.

- https://github.com/nodejs/node/issues/2738
- https://github.com/nodejs/node/issues/7937
- http://erikcorry.blogspot.ru/2012/11/memory-management-flags-in-v8.html

We could also look at caching in redis instead of in process.

**Comment by paulmelnikow** [comment]
I pushed an update to https://github.com/badges/shields/compare/master...paulmelnikow:raster-badges-in-lru-cache-2

It's working as expected and looking pretty good. When I uninstall imagemagick, the buffer is empty, and `gm` emits a nice error via the callback ("Stream yields empty buffer").

I tested the server's svg2img error logic manually. It works as expected, except that the content type is `image/png` instead of `text/html`. Is that something easy to fix?

At some point it would be good to get an automated test around the server logic, but that could wait for another day.

**Comment by paulmelnikow** [comment]
I added that test of the server logic.

**Comment by espadrine** [comment]
I merged https://github.com/badges/shields/compare/master...paulmelnikow:raster-badges-in-lru-cache-2 which includes this PR, as commits 2d71e844a2f15257b9447142ba3912fece06e835 to de18dce94a6a9425d01a465c017f680c98c231f9.

**Pull request closed without merging**
