### PR TITLE
Fix [CodefactorGrade] again

### LINKED ISSUE #4033: Error: Unknown grade: -
Sentry Issue: [SHIELDS-44](https://sentry.io/organizations/shields/issues/1226894023/?referrer=github_integration)

```
Error: Unknown grade: -
  File "/home/m/shields/services/codefactor/codefactor-helpers.js", line 26, in gradeColor
    throw Error(`Unknown grade: ${grade}`)
  File "/home/m/shields/services/codefactor/codefactor-grade.service.js", line 47, in Function.render
    color: gradeColor(grade),
  File "/home/m/shields/services/codefactor/codefactor-grade.service.js", line 58, in CodeFactorGrade.handle
    return this.constructor.render({ grade: message })
  ?, in null.<anonymous>
```

### PR DESCRIPTION
**Pull request by paulmelnikow**
This looks like a case of confusing `Joi.allow()` with `Joi.valid()`.

`Joi.valid(...['A', 'A-']).validate('-')` throws an error but `Joi.allow(...['A', 'A-']).validate('-')` allows it through.

Closes #4033

### CODE REVIEW

**Comment by calebcartwright** [comment]
TBH though I still wonder how in the world a grade value of `-` is coming in from Codefactor 🤷‍♂

**Comment by paulmelnikow** [comment]
> TBH though I still wonder how in the world a grade value of `-` is coming in from Codefactor 🤷‍♂

Yea, that's a fair point. Could that be what's sent for missing data?

**Comment by calebcartwright** [comment]
> Could that be what's sent for missing data?

Perhaps, though from what I've seen the endpoint returns an http 404 in not found/not scanned scenarios. (https://www.codefactor.io/repository/github/badges/shields/badge for example). 

I think for this to occur it would require an http 200 response with a badge that only has `-` in the message

**Comment by paulmelnikow** [comment]
Okay, well I guess we can merge this for now and if we get some clarity about what the `-` means, update again.

**Pull request merged**
