### PR TITLE
Add grade badge for [lgtm]

### PR DESCRIPTION
**Pull request by samlanning**
We've just launched project grades on lgtm: https://discuss.lgtm.com/t/announcing-project-grades-on-lgtm-com/1003

And this PR uses this data (that's exposed over the API) to add a new lgtm badge that displays the grade for a particular language.

EG:

rsyslog
rsyslog 1
cloudstack 2

Added new tests as appropriate.

### CODE REVIEW

**Comment by samlanning** [comment]
(Side note: I wasn't sure whether to include the language as part of the badge name or value, for consistency with the rest of the badges, i thought it would make more sense for it to also be in the value, but i'm open to suggestions)

**Comment by chris48s** [comment]
Code looks fine to me - no comments there.

I think the way round you've proposed (with the language on the right) makes it seem like the colour is in some way connected to the language, whereas it is only the grade which influences the colour. Given that, maybe it would be better to go with 



As a point of reference I think the closest comparison we already have is 

screenshot at 2018-05-10 21 11 37

which doesn't include the service name in the badge. You might also consider something like .

Happy to defer to your opinion on whether you want to include the service name in the label or not.

**Comment by samlanning** [comment]
@chris48s i like your first solution actually, I've made those changes, also lower-cased the languages now that they're part of the label and that feels more consistent.

**Comment by RedSparr0w** [comment]
I'm not quite sure as i've never used lgtm, But I feel like one of these would be better/more descriptive for the badge?

**Comment by samlanning** [comment]
Hmm, I see what you mean. Looking at the other badges that provide grades, it seems like "code quality" is the phrase to use here, so let's go with that. Dropping the service name probably also makes sense too. I like the `code quality: python` format.

I also realised i forgot to add the new badge to the homepage, so i've done that now.

**Pull request merged**
