### PR TITLE
add hundredths to the downloads metrics

### PR DESCRIPTION
**Pull request by tamtamchik**
Just proposal to add 2 hundredths digits for downloads, money and so on…

### CODE REVIEW

**Comment by espadrine** [comment]
Thanks for contributing! I'm not sure how I feel about that change, however. So I made a Twitter poll: https://twitter.com/Shields_io/status/673987276095881216.

**Comment by tamtamchik** [comment]
:laughing: 50 / 50

**Comment by espadrine** [comment]
Sorry :/

**Comment by tamtamchik** [comment]
@espadrine no worries! It was just a proposal :)

**Pull request closed without merging**
