### PR TITLE
[maven-central] Add the ability to filter by version prefix

### PR DESCRIPTION
**Pull request by reda-alaoui**
On my github project page, I need to be able to display the latest version of each maintenance branch.
This is currently impossible, since maven badge display the latest version without any consideration to branches.
E.g `https://img.shields.io/maven-central/v/org.apache.maven/apache-maven` displays version `v3.5.0`

With this PR you can define the badge as:
`https://img.shields.io/maven-central/v/org.apache.maven/apache-maven/3.3.svg` to display the latest 3.3 version which is currently `v3.3.9`.

This is not a breaking change. The first url will keep working.

### CODE REVIEW

**Comment by reda-alaoui** [comment]
Hello there?

**Comment by reda-alaoui** [comment]
Up :p

**Comment by paulmelnikow** [comment]
Looks great! Thanks for the tests and sorry for the delay. Just re-running the Travis checks now, and will merge after that.

**Comment by paulmelnikow** [comment]
Could you add a second example to try.html? That way it will be clear that the version is optional.

**Comment by paulmelnikow** [comment]
Thanks!

**Comment by reda-alaoui** [comment]
Great !

**Comment by reda-alaoui** [comment]
When can we expect to see this working on img.shields.io ?

**Comment by paulmelnikow** [comment]
Usually within a few weeks. I don't have access to deploy, so it'll happen once Thaddée has a chance.

**Pull request merged**
