### PR TITLE
Add High res favicons

### LINKED ISSUE #1497: Provide high resolution favicon
Currently the `shields.io` favicon is low resolution only.

But current browsers like Firefox use big logo information in their top visites sites section.
There is also no image support for links placed on mobile homescreens (android +ios).

On basically all high resolution screens the operating system has to scale things up so it gets even worse.

### PR DESCRIPTION
**Pull request by jaas666**
Add high resolution favicon images using images created for PR #2228

Fix #1497

### CODE REVIEW

**Comment by jaas666** [comment]
I tried getting this to run but these checks are brutal man.

Pretty simple change though. Should be mostly completed and files where included in the PR

I cant get the "npm ci" command to install so Im flying solo without dev.

If anyone with the dev environment correctly running want to fix this one be my guest.

**Comment by paulmelnikow** [comment]
Hey @jaas666 thank you so much for picking this up! If you can handle the file prep I’d be game to wrangle Gatsby for you here. I imagine there is a way we can ship these as static files so they aren’t all embedded into every page load, and I’m
happy to dig into that.

**Comment by paulmelnikow** [comment]
I think you’d need to check in the new files though.

**Comment by jaas666** [comment]
I thought I committed the files on my first commit.. guess not. Sorry about that.. maybe thats why most tests were failing 🤣

**Comment by jaas666** [comment]
Got them? I still can't make the "npm ci" work. Sorry

**Comment by calebcartwright** [comment]
> I still can't make the "npm ci" work. Sorry

Can you provide a little more context, like what version of npm & node you're using, any error message specifics, etc.

**Comment by jaas666** [comment]
> > I still can't make the "npm ci" work. Sorry
> 
> Can you provide a little more context, like what version of npm & node you're using, any error message specifics, etc.

Want me to create an issue about it so we don't polite this discussion?

**Comment by paulmelnikow** [comment]
> Want me to create an issue about it so we don't polute this discussion?

If it's a problem you're running into doing this work, this is a good place to talk about it and it actually makes the conversation easier to follow. Happy to try to get it resolved.

That said, I'm still game to pick this up from here (sorry haven't had a chance to yet).

**Comment by jaas666** [comment]
I don't think the error I'm having is specificaly related to this issue/PR but I do agree that it'll be easier to follow here.

I've tried a couple times deleting my local version and re-cloning.. Right after it finishes the clone process I run `npm ci` and this is the output I get.

`$ npm -v` 8.3.1
`$ node -v` v16.14.0


```
$ npm ci
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm ERR! code 1
npm ERR! path C:\Users\JAAS666\OneDrive\Documents\GIT\shields\node_modules\lmdb
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp-build-optional-packages
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.14.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.10.4 found at "C:\Users\JAAS666\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:363:14)
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:384:16
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:406:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\JAAS666\OneDrive\Documents\GIT\shields\node_modules\lmdb
npm ERR! gyp ERR! node -v v16.14.0
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\JAAS666\AppData\Local\npm-cache\_logs\2022-05-16T23_37_11_887Z-debug-0.log

JAAS666@DESKTOP-Q8RPCNM MINGW64 ~/OneDrive/Documents/GIT/shields (master)
```


Looks like something missing when installing dependencies but can't quite figure it out.. Let me know if you need anything else..

**Comment by calebcartwright** [comment]
Well that's... interesting, thanks for sharing.

Realize I may be telling you something you already know but in the spirit of completeness:

To resolve this you'll need to install the `node-gyp` package from the npm registry, but it will require that you first install Python as well as the MSVC build tools (recommend grabbing directly via https://aka.ms/vs/17/release/vs_BuildTools.exe or from https://visualstudio.microsoft.com/downloads/ if you'd rather get the download link from the MS site). Some more detailed instructions on the setup can be found in https://www.npmjs.com/package/node-gyp.

As to _why_ this is necessary, Node.js supports something called "native add-ons" which, in grossly oversimplified terms, is a mechanism that allows developers to write and distribute modules that are actually compiled and executed natively (typically in C++ or C) in order to get a performance boost vs. JavaScript. Most systems, including Unix-like and Unix-based ones, ship with basic compiler toolsets as part of the operating system. Windows, annoyingly, does not do this and instead requires developers to manually install additional tooling to perform basic compilation and linking actions.

Shields itself is a pure JavaScript/TypeScript application, but apparently at some point one of our transitive dependencies (via Gatsby apparently) has incorporated a Native Addon and this unfortunately means that Shields developers on Windows will also need to have node-gyp and it's prerequisites and configured.

Separately for the Shields maintainers, I think this is another reason why it will beneficial to find an alternative to Gatsby.

**Comment by jaas666** [comment]
OK that helped. I'm being able to install dependencies without problem now.
This is what I'm getting when running  `npm start`

```
$ npm start

> shields.io@0.0.0 prestart
> run-s --silent depcheck defs features

C:\Users\JAAS666\OneDrive\Documents\GIT\shields\node_modules\joi\lib\errors.js:193
        return new exports.ValidationError(message, details, original);
               ^

Error [ValidationError]: {
  "schemaVersion": "0",
  "categories": [
    {
      "id": "build",
      "name": "Build",
      "keywords": [
        "build"
      ]
    },
    {
      "id": "coverage",
      "name": "Code Coverage",
      "keywords": [
        "coverage"
      ]
    },
    {
      "id": "test-results",
      "name": "Test Results",
      "keywords": [
        "tests"
      ]
    },
    {
      "id": "analysis",
      "name": "Analysis",
      "keywords": [
        "analysis"
      ]
    },
    {
      "id": "chat",
      "name": "Chat",
      "keywords": [
        "chat"
      ]
    },
    {
      "id": "dependencies",
      "name": "Dependencies",
      "keywords": [
        "dependencies"
      ]
    },
    {
      "id": "size",
      "name": "Size",
      "keywords": [
        "size"
      ]
    },
    {
      "id": "downloads",
      "name": "Downloads",
      "keywords": [
        "downloads"
      ]
    },
    {
      "id": "funding",
      "name": "Funding",
      "keywords": [
        "funding"
      ]
    },
    {
      "id": "issue-tracking",
      "name": "Issue Tracking",
      "keywords": [
        "issue"
      ]
    },
    {
      "id": "license",
      "name": "License",
      "keywords": [
        "license"
      ]
    },
    {
      "id": "rating",
      "name": "Rating",
      "keywords": [
        "rating"
      ]
    },
    {
      "id": "social",
      "name": "Social",
      "keywords": [
        "social"
      ]
    },
    {
      "id": "version",
      "name": "Version",
      "keywords": [
        "version"
      ]
    },
    {
      "id": "platform-support",
      "name": "Platform & Version Support",
      "keywords": [
        "platform"
      ]
    },
    {
      "id": "monitoring",
      "name": "Monitoring",
      "keywords": [
        "monitoring"
      ]
    },
    {
      "id": "activity",
      "name": "Activity",
      "keywords": [
        "activity"
      ]
    },
    {
      "id": "other",
      "name": "Other",
      "keywords": []
    }
  ],
  "services" [1]: []
}

[1] "services" does not contain 1 required value(s)
    at Object.exports.process (C:\Users\JAAS666\OneDrive\Documents\GIT\shields\node_modules\joi\lib\errors.js:193:16)
    at Object.internals.entry (C:\Users\JAAS666\OneDrive\Documents\GIT\shields\node_modules\joi\lib\validator.js:153:26)
    at Object.exports.entry (C:\Users\JAAS666\OneDrive\Documents\GIT\shields\node_modules\joi\lib\validator.js:27:30)
    at internals.Base.validate (C:\Users\JAAS666\OneDrive\Documents\GIT\shields\node_modules\joi\lib\base.js:548:26)
    at Object.internals.assert (C:\Users\JAAS666\OneDrive\Documents\GIT\shields\node_modules\joi\lib\index.js:225:27)
    at Object.assert (C:\Users\JAAS666\OneDrive\Documents\GIT\shields\node_modules\joi\lib\index.js:102:19)
    at assertValidServiceDefinitionExport (file:///C:/Users/JAAS666/OneDrive/Documents/GIT/shields/core/base-service/service-definitions.js:70:7)
    at collectDefinitions (file:///C:/Users/JAAS666/OneDrive/Documents/GIT/shields/core/base-service/loader.js:89:3)
    at async file:///C:/Users/JAAS666/OneDrive/Documents/GIT/shields/scripts/export-service-definitions-cli.js:4:23 {
  _original: {
    schemaVersion: '0',
    categories: [
      { id: 'build', name: 'Build', keywords: [ 'build' ] },
      {
        id: 'coverage',
        name: 'Code Coverage',
        keywords: [ 'coverage' ]
      },
      {
        id: 'test-results',
        name: 'Test Results',
        keywords: [ 'tests' ]
      },
      { id: 'analysis', name: 'Analysis', keywords: [ 'analysis' ] },
      { id: 'chat', name: 'Chat', keywords: [ 'chat' ] },
      {
        id: 'dependencies',
        name: 'Dependencies',
        keywords: [ 'dependencies' ]
      },
      { id: 'size', name: 'Size', keywords: [ 'size' ] },
      { id: 'downloads', name: 'Downloads', keywords: [ 'downloads' ] },
      { id: 'funding', name: 'Funding', keywords: [ 'funding' ] },
      {
        id: 'issue-tracking',
        name: 'Issue Tracking',
        keywords: [ 'issue' ]
      },
      { id: 'license', name: 'License', keywords: [ 'license' ] },
      { id: 'rating', name: 'Rating', keywords: [ 'rating' ] },
      { id: 'social', name: 'Social', keywords: [ 'social' ] },
      { id: 'version', name: 'Version', keywords: [ 'version' ] },
      {
        id: 'platform-support',
        name: 'Platform & Version Support',
        keywords: [ 'platform' ]
      },
      {
        id: 'monitoring',
        name: 'Monitoring',
        keywords: [ 'monitoring' ]
      },
      { id: 'activity', name: 'Activity', keywords: [ 'activity' ] },
      { id: 'other', name: 'Other', keywords: [] }
    ],
    services: []
  },
  details: [
    {
      message: '"services" does not contain 1 required value(s)',
      path: [ 'services' ],
      type: 'array.includesRequiredUnknowns',
      context: {
        unknownMisses: 1,
        label: 'services',
        value: [],
        key: 'services'
      }
    }
  ]
}
```

**Comment by jaas666** [comment]
Any update?

**Comment by calebcartwright** [comment]
Couldn't tell ya, but CI is failing on various fronts and I'd probably start there. Specifically, make sure you can get an `npm run build` passing locally

**Comment by jaas666** [comment]
Tried lots of things. Running from WSL and nothing, even spun up a new Linux VM just to try this and still nothing. Furthest I could get is to have the server running but the frontend loads a white empty screen... Here's the log from the `npm start` in case you or someone else can identify the problem. Otherwise I give up, someone can pick up what I already did and complete it. 

This is using WSL (Ubuntu)
```
$ npm start

> shields.io@0.0.0 prestart
> run-s --silent depcheck defs features


> shields.io@0.0.0 start
> concurrently --names server,frontend "npm run start:server" "cd frontend && cross-env GATSBY_BASE_URL=http://localhost:8080 gatsby develop --port 3000"

[server] 
[server] > shields.io@0.0.0 start:server
[server] > cross-env NODE_CONFIG_ENV=development nodemon server 8080
[server]
[server] [nodemon] 2.0.16
[server] [nodemon] reading config ./package.json
[server] [nodemon] to restart at any time, enter `rs`
[server] [nodemon] or send SIGHUP to 5576 to restart
[server] [nodemon] ignoring: package.json **/*.spec.js **/*.tester.js **/*.integration.js ./frontend/**/* build/**/* ./cypress/**/*
[server] [nodemon] watching path(s): *.*
[server] [nodemon] watching extensions: js
[server] [nodemon] starting `node server.js 8080`
[server] [nodemon] forking
[server] [nodemon] child pid: 5589
[server] [nodemon] watching 657 files
[server] Configuration:
[server] {
[server]   bind: { address: 'localhost', port: 8080 },
[server]   metrics: {
[server]     prometheus: { enabled: false, endpointEnabled: false },
[server]     influx: { enabled: false, timeoutMilliseconds: 1000, intervalSeconds: 15 }
[server]   },
[server]   ssl: { isSecure: false },
[server]   cors: { allowedOrigin: [ 'http://localhost:3000' ] },
[server]   services: {
[server]     github: {
[server]       baseUri: 'https://api.github.com/',
[server]       debug: { enabled: false, intervalSeconds: 200 }
[server]     },
[server]     obs: { authorizedOrigins: 'https://api.opensuse.org' },
[server]     weblate: { authorizedOrigins: 'https://hosted.weblate.org' },
[server]     trace: false
[server]   },
[server]   cacheHeaders: { defaultCacheLengthSeconds: 120 },
[server]   handleInternalErrors: false,
[server]   fetchLimit: '10MB',
[server]   userAgentBase: 'shields (self-hosted)',
[server]   requestTimeoutSeconds: 120,
[server]   requestTimeoutMaxAgeSeconds: 30,
[server]   requireCloudflare: false
[server] }
[server] 0519025043 Server is starting up: http://localhost:8080/
[server] (node:5589) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
[server] (Use `node --trace-deprecation ...` to show where the warning was created)
[frontend] success open and validate gatsby-configs, load plugins - 0.227s
warn gatsby-plugin-remove-trailing-slashes: Gatsby now has a trailingSlash
[frontend] option. Learn more at https://gatsby.dev/trailing-slash
success onPreInit - 0.007s
success initialize cache - 0.062s
success copy gatsby files - 0.093s
success Compiling Gatsby Functions - 0.227s
success onPreBootstrap - 0.238s
success createSchemaCustomization - 0.001s
success Checking for changed pages - 0.001s
success source and transform nodes - 0.104s                                                                               
success building schema - 0.380s
success createPages - 0.030s
warn Non-deterministic routing danger: Attempting to create page:
[frontend] "/dev-404-page/", but page "/dev-404-page" already exists
[frontend] This could lead to non-deterministic routing behavior
warn Non-deterministic routing danger: Attempting to create page: "/community/",
[frontend]  but page "/community" already exists
[frontend] This could lead to non-deterministic routing behavior
warn Non-deterministic routing danger: Attempting to create page: "/endpoint/",                                           
[frontend] but page "/endpoint" already exists
[frontend] This could lead to non-deterministic routing behavior
success createPagesStatefully - 0.124s
info Total nodes: 51, SitePage nodes: 24 (use --verbose for breakdown)                                                    
success Checking for changed pages - 0.001s                                                                               
success write out redirect data - 0.002s                                                                                  
success onPostBootstrap - 0.002s                                                                                          
info bootstrap finished - 3.078s
success onPreExtractQueries - 0.001s                                                                                      
success extract queries from components - 0.198s
success write out requires - 0.007s

[frontend]  ERROR #98123  WEBPACK
[frontend]
[frontend] Generating development JavaScript bundle failed
[frontend]
[frontend] Module build failed (from ../node_modules/url-loader/dist/cjs.js):
[frontend] Error: error:0308010C:digital envelope routines::unsupported
[frontend]     at new Hash (node:internal/crypto/hash:67:19)
[frontend]     at Object.createHash (node:crypto:135:10)
[frontend]     at getHashDigest (/home/jaas666/shields/node_modules/file-loader/node_module
[frontend] s/loader-utils/lib/getHashDigest.js:46:34)
[frontend]     at /home/jaas666/shields/node_modules/file-loader/node_modules/loader-utils/
[frontend] lib/interpolateName.js:113:11
[frontend]     at String.replace (<anonymous>)
[frontend]     at interpolateName (/home/jaas666/shields/node_modules/file-loader/node_modu
[frontend] les/loader-utils/lib/interpolateName.js:110:8)
[frontend]     at Object.loader
[frontend] (/home/jaas666/shields/node_modules/file-loader/dist/index.js:29:48)
[frontend]     at Object.loader
[frontend] (/home/jaas666/shields/node_modules/url-loader/dist/index.js:127:19)
[frontend]
[frontend] File: ../node_modules/@fontsource/lato/index.css
[frontend]

[frontend]  ERROR #98123  WEBPACK
[frontend]
[frontend] Generating development JavaScript bundle failed
[frontend]
[frontend] Module build failed (from ../node_modules/url-loader/dist/cjs.js):
[frontend] Error: error:0308010C:digital envelope routines::unsupported
[frontend]     at new Hash (node:internal/crypto/hash:67:19)
[frontend]     at Object.createHash (node:crypto:135:10)
[frontend]     at getHashDigest (/home/jaas666/shields/node_modules/file-loader/node_module
[frontend] s/loader-utils/lib/getHashDigest.js:46:34)
[frontend]     at /home/jaas666/shields/node_modules/file-loader/node_modules/loader-utils/
[frontend] lib/interpolateName.js:113:11
[frontend]     at String.replace (<anonymous>)
[frontend]     at interpolateName (/home/jaas666/shields/node_modules/file-loader/node_modu
[frontend] les/loader-utils/lib/interpolateName.js:110:8)
[frontend]     at Object.loader
[frontend] (/home/jaas666/shields/node_modules/file-loader/dist/index.js:29:48)
[frontend]     at Object.loader
[frontend] (/home/jaas666/shields/node_modules/url-loader/dist/index.js:127:19)
[frontend]
[frontend] File: ../node_modules/@fontsource/lekton/index.css
[frontend]
failed Building development bundle - 6.982s                                                                               
ERROR in ../node_modules/@fontsource/lato/index.css
[frontend] Module build failed (from 
[frontend] ../node_modules/mini-css-extract-plugin/dist/loader.js):
[frontend] ModuleBuildError: Module build failed (from 
[frontend] ../node_modules/url-loader/dist/cjs.js):
[frontend] Error: error:0308010C:digital envelope routines::unsupported
[frontend]     at new Hash (node:internal/crypto/hash:67:19)
[frontend]     at Object.createHash (node:crypto:135:10)
[frontend]     at getHashDigest (/home/jaas666/shields/node_modules/file-loader/node_module
[frontend] s/loader-utils/lib/getHashDigest.js:46:34)
[frontend]     at /home/jaas666/shields/node_modules/file-loader/node_modules/loader-utils/
[frontend] lib/interpolateName.js:113:11
[frontend]     at String.replace (<anonymous>)
[frontend]     at interpolateName (/home/jaas666/shields/node_modules/file-loader/node_modu
[frontend] les/loader-utils/lib/interpolateName.js:110:8)
[frontend]     at Object.loader
[frontend] (/home/jaas666/shields/node_modules/file-loader/dist/index.js:29:48)
[frontend]     at Object.loader
[frontend] (/home/jaas666/shields/node_modules/url-loader/dist/index.js:127:19)
[frontend]     at processResult
[frontend] (/home/jaas666/shields/node_modules/webpack/lib/NormalModule.js:751:19)
[frontend]     at /home/jaas666/shields/node_modules/webpack/lib/NormalModule.js:853:5
[frontend]     at
[frontend] /home/jaas666/shields/node_modules/loader-runner/lib/LoaderRunner.js:399:11
[frontend]     at
[frontend] /home/jaas666/shields/node_modules/loader-runner/lib/LoaderRunner.js:251:18
[frontend]     at runSyncOrAsync
[frontend] (/home/jaas666/shields/node_modules/loader-runner/lib/LoaderRunner.js:156:3)
[frontend]     at iterateNormalLoaders
[frontend] (/home/jaas666/shields/node_modules/loader-runner/lib/LoaderRunner.js:250:2)
[frontend]     at
[frontend] /home/jaas666/shields/node_modules/loader-runner/lib/LoaderRunner.js:223:4
[frontend]     at /home/jaas666/shields/node_modules/webpack/lib/NormalModule.js:827:15
[frontend]     at Array.eval (eval at create (/home/jaas666/shields/node_modules/webpack/no
[frontend] de_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
[frontend]     at runCallbacks (/home/jaas666/shields/node_modules/enhanced-resolve/lib/Cac
[frontend] hedInputFileSystem.js:27:15)
[frontend]     at /home/jaas666/shields/node_modules/enhanced-resolve/lib/CachedInputFileSy
[frontend] stem.js:200:4
[frontend]     at /home/jaas666/shields/node_modules/graceful-fs/graceful-fs.js:123:16
[frontend]     at FSReqCallback.readFileAfterClose [as oncomplete]
[frontend] (node:internal/fs/read_file_context:68:3)
[frontend]  @ ./components/meta.tsx 10:0-26
[frontend]  @ ./pages/endpoint.tsx 9:0-38 65:39-43
[frontend]  @ ./.cache/_this_is_virtual_fs_path_/$virtual/async-requires.js 31:11-33:5
[frontend]  @ ./.cache/app.js 16:0-52 29:87-33:1 32:29-42 35:27-40 29:0-33:2
[frontend]
[frontend] ERROR in ../node_modules/@fontsource/lekton/index.css
[frontend] Module build failed (from 
[frontend] ../node_modules/mini-css-extract-plugin/dist/loader.js):
[frontend] ModuleBuildError: Module build failed (from 
[frontend] ../node_modules/url-loader/dist/cjs.js):
[frontend] Error: error:0308010C:digital envelope routines::unsupported
[frontend]     at new Hash (node:internal/crypto/hash:67:19)
[frontend]     at Object.createHash (node:crypto:135:10)
[frontend]     at getHashDigest (/home/jaas666/shields/node_modules/file-loader/node_module
[frontend] s/loader-utils/lib/getHashDigest.js:46:34)
[frontend]     at /home/jaas666/shields/node_modules/file-loader/node_modules/loader-utils/
[frontend] lib/interpolateName.js:113:11
[frontend]     at String.replace (<anonymous>)
[frontend]     at interpolateName (/home/jaas666/shields/node_modules/file-loader/node_modu
[frontend] les/loader-utils/lib/interpolateName.js:110:8)
[frontend]     at Object.loader
[frontend] (/home/jaas666/shields/node_modules/file-loader/dist/index.js:29:48)
[frontend]     at Object.loader
[frontend] (/home/jaas666/shields/node_modules/url-loader/dist/index.js:127:19)
[frontend]     at processResult
[frontend] (/home/jaas666/shields/node_modules/webpack/lib/NormalModule.js:751:19)
[frontend]     at /home/jaas666/shields/node_modules/webpack/lib/NormalModule.js:853:5
[frontend]     at
[frontend] /home/jaas666/shields/node_modules/loader-runner/lib/LoaderRunner.js:399:11
[frontend]     at
[frontend] /home/jaas666/shields/node_modules/loader-runner/lib/LoaderRunner.js:251:18
[frontend]     at runSyncOrAsync
[frontend] (/home/jaas666/shields/node_modules/loader-runner/lib/LoaderRunner.js:156:3)
[frontend]     at iterateNormalLoaders
[frontend] (/home/jaas666/shields/node_modules/loader-runner/lib/LoaderRunner.js:250:2)
[frontend]     at
[frontend] /home/jaas666/shields/node_modules/loader-runner/lib/LoaderRunner.js:223:4
[frontend]     at /home/jaas666/shields/node_modules/webpack/lib/NormalModule.js:827:15
[frontend]     at Array.eval (eval at create (/home/jaas666/shields/node_modules/webpack/no
[frontend] de_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
[frontend]     at runCallbacks (/home/jaas666/shields/node_modules/enhanced-resolve/lib/Cac
[frontend] hedInputFileSystem.js:27:15)
[frontend]     at /home/jaas666/shields/node_modules/enhanced-resolve/lib/CachedInputFileSy
[frontend] stem.js:200:4
[frontend]     at /home/jaas666/shields/node_modules/graceful-fs/graceful-fs.js:123:16
[frontend]     at FSReqCallback.readFileAfterClose [as oncomplete]
[frontend] (node:internal/fs/read_file_context:68:3)
[frontend]  @ ./components/meta.tsx 11:0-28
[frontend]  @ ./pages/endpoint.tsx 9:0-38 65:39-43
[frontend]  @ ./.cache/_this_is_virtual_fs_path_/$virtual/async-requires.js 31:11-33:5
[frontend]  @ ./.cache/app.js 16:0-52 29:87-33:1 32:29-42 35:27-40 29:0-33:2
[frontend]
[frontend] 3 ERRORS in child compilations (Use 'stats.children: true' resp. 
[frontend] '--stats-children' for more details)
[frontend] develop compiled with 5 errors
success Writing page-data.json files to public directory - 0.211s - 1/23
[frontend] 108.96/s
success onPreExtractQueries - 0.002s
success extract queries from components - 0.017s
success write out requires - 0.002s
success run page queries - 0.015s - 1/1 68.18/s
success Writing page-data.json files to public directory - 0.003s - 1/23
[frontend] 7280.55/s
[frontend]
```

**Comment by jaas666** [comment]
New PR submitted.. closing this one. 

Ref. #7983

**Pull request closed without merging**
