### PR TITLE
For-the-badge | Convert labels to string then uppercase

### LINKED ISSUE #1280: problem with "for the badge" style and numeric values
Is there a maximum amount of parameters that can be applied to a badge until it brakes?
Had some trouble with a badge once I appended 4 parameters. It started to show `invalid` then.

### PR DESCRIPTION
**Pull request by RedSparr0w**
Closes #1280 

was previously trying to convert any numbers to uppercase,

will now convert the label to a string and then to uppercase.

Also removed `.toUpperCase()` from the template as it shouldn't be needed.

Edit: Updated title as it was breaking the tests

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Could you add a unit test for this, maybe in `server.spec.js`?

**Comment by platan** [comment]
I just wanted to propose unit test in `lib/make-badge.spec.js` :-)
```js
  // https://github.com/badges/shields/issues/1280
  it('should produce SVG for "for-the-badge" template with numbers as texts', function () {
    const svg = makeBadge({ text: [1998, 1999], format: 'svg', template: 'for-the-badge' });
    assert(svg.includes('1998'), `${svg} does not contain '1998'`);
    assert(svg.includes('1999'), `${svg} does not contain '1999'`);
  });
```

or even better using chai assertions (it has `contains` assertion):
```js
const chai = require('chai');
chai.should();

...

  // https://github.com/badges/shields/issues/1280
  it('should produce SVG for "for-the-badge" template with numbers as texts', function () {
    const svg = makeBadge({ text: [1998, 1999], format: 'svg', template: 'for-the-badge' });
    svg.should.contains('1998');
    svg.should.contains('1999');
  });
```

**Comment by RedSparr0w** [comment]
Thanks @platan wasn't too sure where to start on the tests!

I'd rather go with your first example as it doesn't depend on a dependencies dependency, and also matches the current tests that is already there.

@paulmelnikow just checking it doesn't need `assert.ok(isSvg(svg));` for every tests as its already tested on the first test and should throw there if something is wrong?

**Comment by paulmelnikow** [comment]
> I just wanted to propose unit test in lib/make-badge.spec.js :-)

Yeah!

> or even better using chai assertions (it has `contains` assertion, we already have chai as a 
node-env-flag's dependency):

I'd be happy to replace Node assert with Chai, which has much richer assertions… though we should make the change across the whole project, declare the dependency, and probably discuss which syntax to use.

> @paulmelnikow just checking it doesn't need `assert.ok(isSvg(svg));` for every tests as its already tested on the first test and should throw there if something is wrong?

It's not great to throw lots of random extra assertions into a test, though occasionally it can be helpful to establish confidence before making the real assertion. In other words, if you know you have a badge, you can be sure the `.contains()` check passing means your code is probably working as you intend.

Separating them from the "real" assertions and calling them out with a comment can help express your intent:

```js
// Set up.
prepareSomething();

// Act.
doSomething();

// Confidence check.
assert(something basic, that sets up my test assertions);

// Test.
assert(something specific);
```

**Comment by RedSparr0w** [comment]
Sweet, this should be ready for merge then if you could please have a quick look over it.
Don't think any other test need to be added.

**Pull request merged**
