### PR TITLE
Add vaadin.svg

### PR DESCRIPTION
**Pull request by binhbbui411**
Has been minimized using svomg

### CODE REVIEW

**Comment by RedSparr0w** [comment]
Thanks for submitting this logo.
But i'm not too sure which badge this relates to, could you please clarify.

**Comment by binhbbui411** [comment]
Hi @RedSparr0w, I am making a badge for our new released [Vaadin Directory](http://vaadin.com/directory). I just want to see if I put the logo in the badge how it would look.  

Is there a requirement which logo can be stored in here?

**Comment by RedSparr0w** [comment]
Unfortunately we generally only accept logos where we have a relevant badge to which it relates.

You can include logos in base64 format + url encoded though:

`https://img.shields.io/badge/label-message-10ADED.svg?logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAAOCAYAAAAfSC3RAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAACEQAAAhEB5S0hzQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAFHSURBVCiRjZC/S0JhFIafc7UQGrQfWOBi3sGov6JVtMmhGtzC1lqaWosag8C1IYhG9d7G/oqKghqCSKK4PyCQ6t7TcMHUruAZz/u833veT7hy8gRiUM48Mc7YronqT5JA9lHSQHUsY8ARIl4SQYASlneGahcAISQMzxEEMTZRjGgvKVRLCBdCy60iXAIy%2BLS%2BggiwMJSpoNUIbn6sYCSWe5LIBKrHESZ7iH71tDC4ZW32ZnSXlrOL5eyM1Zu2W8By66j%2Bna0qWG6dprvYjxqD12sNpYHtb/R2tr%2BO0iAhtX508ENa7zkk%2BQC8YaSXyBLS8e6AHBoWqcw8xydW5l5QToE8gb9Fx98GTISTftP/xKjnNPCI8o2gwCRgUs44ozsClDMOwiFCFpgHDoZN8YkA15ri07sHYCpdZFW6sVzs2K5J2y2Mkn8B5G1xROYb2XgAAAAASUVORK5CYII=`

**Note:**
Closing due to logo has no relevant badges, Feel free to re-open if you feel this should still be merged.
Also feel free to comment here if you have anymore questions in regards to using the logo.

**Comment by binhbbui411** [comment]
Thanks for the notice @RedSparr0w. I am actually making Vaadin service to add your library.  
I will open a ticket again when it's all set.  

Thanks!

**Pull request closed without merging**
