### PR TITLE
[jetbrains] badge to show downloads count from jetbrains plugin repository v2

### PR DESCRIPTION
**Pull request by platan**
This pull request is based on @mskonovalov's pull request https://github.com/badges/shields/pull/896. I've fixed issues reported by @paulmelnikow (badge format + service tests).

### CODE REVIEW

**Comment by platan** [comment]
I've forgotten about adding `[jetbrains]` to PR name (https://github.com/badges/shields/tree/master/service-tests#pull-requests). I'm not sure if Travis will see changed name. Could you please rerun Travis build? 
By the way, maybe all service tests should be run when there is a PR for given branch? This would be less error prone.

**Comment by platan** [comment]
What do you think about this change?

**Comment by platan** [comment]
I've merged master. Unfortunately [CI build failed](https://travis-ci.org/badges/shields/builds/279242446), because some GitHub's service tests failed. The same problem occurred in CRON build in master [yesterday](https://travis-ci.org/badges/shields/builds/279061505), [2 days ago](https://travis-ci.org/badges/shields/builds/278807236), [3 days ago](https://travis-ci.org/badges/shields/builds/278400517), [and so on](https://travis-ci.org/badges/shields/builds) :-(

**Comment by platan** [comment]
I can see you're working intensively on GitHub rate limit problem https://github.com/badges/shields/issues/979

**Comment by paulmelnikow** [comment]
Much appreciated!

**Pull request merged**
