### PR TITLE
Add docker logo

### PR DESCRIPTION
**Pull request by tjamet**
Hi,

Awesome work there.
May I propose adding a docker badge?

### CODE REVIEW

**Comment by RedSparr0w** [comment]
Thanks for submitting this PR,
But i think this logo may be a little too detailed for use in shields badges (it's also quite a large file size):
docker logo badge

**Comment by tjamet** [comment]
yes agree, I have updated the PR with this one

**Comment by tjamet** [comment]
with the white color, this is the rendering, rendered with https://svgtopng.com/

**Comment by RedSparr0w** [comment]
Looks good to me:


Do you think we could remove the ® from down the bottom right?
As it's not legible due to the size anyway, and just adds extra data.

**Comment by tjamet** [comment]
I can have a look at that
I kept it to be compliant with the logo terms of use, let me update the PR

**Comment by RedSparr0w** [comment]
Thanks, Logo looks good,
Merged!
👍

**Pull request merged**
