### PR TITLE
Add GitLab pipline suggestion

### LINKED ISSUE #2679: Add GitLab support to badge suggestion feature
As requested at https://github.com/badges/shields/issues/541#issuecomment-440088237 pasting a Gitlab badge into the Suggest box should suggest a pipeline status badge.

(Labeling this frontend as that's the part of the project this affects; however this is all backend work.)

### PR DESCRIPTION
**Pull request by Oshawk**
Added a suggestion for a pipeline badge when a GitLab URL is entered. Fixes #2679.

### CODE REVIEW

**Comment by calebcartwright** [comment]
image

Awesome!

**Comment by Oshawk** [comment]
@calebcartwright Sure, will add some tests tomorrow.

**Comment by Oshawk** [comment]
Okay, they seem to work now. Sorry, this was my first time writing JS tests.

**Comment by calebcartwright** [comment]
> Okay, they seem to work now. Sorry, this was my first time writing JS tests.

No worries, thanks for adding them!

**Pull request merged**
