### PR TITLE
[travis] Get tested PHP version from Travis CI

### PR DESCRIPTION
**Pull request by peter-gribanov**
For issue https://github.com/badges/shields/issues/819

In this PR i add badge for get PHP version only from Travis CI.
Also need to add a badges for get version from [Composer](https://github.com/badges/shields/issues/819#issuecomment-310058335) and [PHP-Eye](https://github.com/badges/shields/issues/819#issuecomment-302392534).
I plan to make it separate PR.

I added tests, but they are dangerous.
The success of the tests depends on [Symfony](https://github.com/symfony/symfony).
If you have any ideas how to fix this problem, tell me please.

[PHP](https://github.com/yiisoft/yii)

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Hi, thanks for this. I appreciate what you're trying to do here.

The implementation is pretty involved. Would reading values from `.travis.yml` be sufficient?

It seems like a **tests | success**, from Travis API, in conjunction with **PHP | 7.1**, from `.travis.yml`, would provide sufficient signal to the user, without needing to fetch the results of all the Travis tests. It would be simpler to understand and run a lot faster.

**Comment by peter-gribanov** [comment]
Successfully passed tests are the guarantor of that that the application works on this PHP version.
On the same principle, the [PHP-Eye](https://github.com/badges/shields/issues/819#issuecomment-302392534) works.

In order not to pull out data from the Travis CI, you can use [Composer](https://github.com/badges/shields/pull/1256) or [PHP-Eye](https://github.com/badges/shields/issues/819#issuecomment-302392534)

**Comment by peter-gribanov** [comment]
I can make a separate badge which will read data only from `.travis.yml`.

**Comment by paulmelnikow** [comment]
> Successfully passed tests are the guarantor of that that the application works on this PHP version.

If the tests are configured for three versions, and the tests pass, logically it implies that the tests pass on those three versions. The difference between that and a post facto guarantee seems pedantic. It's just a badge, not a deploy trigger.

> On the same principle, the [PHP-Eye](https://github.com/badges/shields/issues/819#issuecomment-302392534) works.

Is the PHP-Eye Travis data different from what you're extracting in #1258?

**Comment by peter-gribanov** [comment]
After merging #1258, i can simplify the implementation and, for example, rename it to **Tested**.

Tested

**Comment by paulmelnikow** [comment]
Okay, so #1258 is now merged. I appreciate the work you put into that, and into this. Though the endpoint from #1258 for "Tested versions based on Travis" is not perfect, as you've observed, it's good enough, given the "perfect" implementation would need to make several requests. If you can pull the data you want more simply from PHP-Eye I'd certainly be open to that. Also, to adding Composer if you'd like. Thanks again!

**Comment by peter-gribanov** [comment]
@paulmelnikow I'll definitely make a badge for PHP-Eye and I'll redo this badge when i have time.

**Comment by paulmelnikow** [comment]
Thanks for understanding!

**Pull request closed without merging**
