### PR TITLE
Avoid sending dummy requests to packagist

### PR DESCRIPTION
**Pull request by Seldaek**
I spotted a bunch of 404s in the packagist logs that are due to people publishing things like https://github.com/thephpleague/skeleton and other people not editing the READMEs before publishing I suppose. 

Anyway I hope the fix is appropriate and acceptable.

### CODE REVIEW

**Comment by espadrine** [comment]
Haha indeed!

**Comment by espadrine** [comment]
Out of curiosity, I wonder if the system supports having a package literally named `:package_name`.

**Comment by Seldaek** [comment]
Heh nope we don't allow `:` in package names as that's not a valid path character on windows.

**Comment by espadrine** [comment]
Ok!

**Pull request merged**
