### PR TITLE
use most permissive license color

### PR DESCRIPTION
**Pull request by pnowaczyk**
Hello, I'd like to propose a solution for a TODO left in `lib/licenses.js` 😄 
I think that since something is available under many licenses, it can be obtained under the most permissive one, thus we can set the badge color to that specific one.
What do you think? I'm open for discussion 😃

### CODE REVIEW

**Comment by platan** [comment]
I closed and reopened this PR because WIP check hung. But it did not help at all.

**Comment by pnowaczyk** [comment]
Any way I can help with that?

**Comment by platan** [comment]
I changed PR title and it helped :-)
@chris48s @PyvesB have you noticed any problems with the WIP check before?

**Comment by chris48s** [comment]
@platan  I've seen this problem a few times. This PR for example: https://github.com/badges/shields/pull/2200 (unless we've changed something before you read this). I had a couple of dependabot PRs incorrectly stuck on WIP as well.

**Pull request merged**
