### PR TITLE
restore cors header injection from #4171, run [npm travis]

### LINKED ISSUE #3273: Blocked by CORS policy
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

When I try using the badges in a Steam addon description, I get this error and the badge doesnt show up:

```
Access to image at 'https://img.shields.io/github/issues-raw/Aperture-Development/MSync-2.png' from origin 'https://steamcommunity.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

:link: **Link to the badge**

https://img.shields.io/github/issues-raw/Aperture-Development/MSync-2.png

Steps for reproduction:

1. Generate a badge
2. Add it like this: ``[img]{badge}[/img]`` to your addon description

### PR DESCRIPTION
**Pull request by calebcartwright**
# Do Not Merge (til after the next deploy)!

Restores the cors header injection updates originally made in #4171  that were temporarily reverted in #4253 

Also ref #4227 
Closes #3273

### CODE REVIEW

**Comment by joelgallant** [comment]
@calebcartwright what was the status of this?

**Comment by paulmelnikow** [comment]
Should we give this change another shot?

**Comment by calebcartwright** [comment]
@paulmelnikow, sure whenever is feasible for you from a deployment perspective 

(and apologies @joelgallant I must have missed the notification from your message :grimacing:)

**Comment by paulmelnikow** [comment]
Let's merge it and I'll deploy it tomorrow.

**Comment by paulmelnikow** [comment]
Given we're moving forward with Heroku, I think we should go ahead and merge this.

**Comment by calebcartwright** [comment]
> Given we're moving forward with Heroku, I think we should go ahead and merge this

Are we all set in the new Heroku environment to measure the impact of this change to determine whether it was the cause of the perf issues we saw around the last time it was deployed?

**Comment by paulmelnikow** [comment]
Yea, we can keep an eye on the performance. And importantly, if we need more capacity, we can add it!

**Comment by calebcartwright** [comment]
> Yea, we can keep an eye on the performance. And importantly, if we need more capacity, we can add it!

SGTM. I'll do a rebase and make any updates (guessing eslint related) to get CI passing again, and we can take it from there

**Comment by chris48s** [comment]
@calebcartwright - are you up for rebasing this to get the tests passing so we can try this out again? Hopefully its quite a small job..

**Review by chris48s — DISMISSED** [review]

**Review by paulmelnikow — DISMISSED** [review]

**Comment by calebcartwright** [comment]
haven't forgotten about this. just need to find some time when I can merge and deploy this commit in isolation, and then watch the metrics for a while to see if it causes any spike

**Comment by calebcartwright** [comment]
Realize this has been sitting for ages. To recap, this was reverted (along with #4254) because of a potential correlation with a performance event observed in our old OVH environment. I've had it parked for a while for various reasons, including some trial comparison periods we've been running with different http client libs.

This should be much easier to deploy in our current Heroku world given how easily we can roll back

**Review by chris48s — APPROVED** [review]

**Comment by calebcartwright** [comment]
Going to merge and deploy this now given that it can be done in isolation (production is currently in sync with the master branch). i'll keep an eye on this today/into the night US time, and check on it again in the morning local time.

As a recap this was reverted because of it being a potential cause of performance issues, so if issues are observed today/tomorrow we should be prepared to rollback prod in Heroku.

**Pull request merged**
