### PR TITLE
Allow env vars to be checked in for the server deploy

### PR DESCRIPTION
**Pull request by paulmelnikow**
What do you think of this approach to handling config on the servers? This is intended as a way to turn on the work we did in #1725 on the VPS without SSH access.

Also ref: #1723 #1568 https://github.com/badges/shields/pull/1742#issuecomment-407446963

Todo:

- [ ] Test on staging
- [ ] Update deploy task
- [ ] Update gitignores?

### CODE REVIEW

**Comment by chris48s** [comment]
I don't have strong opinions on this because It impacts on a process that you and @espadrine run, so I'll defer to @espadrine 's review.

**Comment by PyvesB** [comment]
It's been over a week since this pull request was opened. In the meantime, could we not simply hard-code a non 0 value for `BADGE_MAX_AGE_SECONDS`? This would only be temporary and we can simply revert it once this pull request moves forward. 😉

**Comment by paulmelnikow** [comment]
That seems reasonable to me.

Since we're so often having serious issues, maybe we should start with 60 seconds?

**Comment by Nyholm** [comment]
Why not 300? or 600?

I rather see a badge with stale data then no badge at all.

**Comment by espadrine** [comment]
We should federate env vars and secrets vars instead. That way, all env vars that we want to check in can be stored in secrets.json. No need for multiple files with poorly-defined differences, where people won't know which file contains which flag.

**Comment by paulmelnikow** [comment]
This is coming up again because we need to turn on a feature flag for #2069.

Since we don't have _so_ much configuration, I'd tend to go in the opposite direction, and put everything in the environment. Environment vars are the most common way of handling this. For self-hosting users on Heroku or Now, configuring through env vars will be much easier because they can be set persistently from the command line or a UI, and don't require a deploy commit.

Occasionally for complex systems I've used JSON in environment variables, though I don't see any need for it here. We can use one env var per setting.

Though I'm not sure quite what the alternate proposal is, I don't think we should create a solution that requires the servers to talk to each other in order to configure themselves. Immutability isn't just trendy. A system with fewer moving parts is more predictable, and there's less code to write. I made a similar argument in https://github.com/badges/shields/issues/1848#issuecomment-434898047.

**Comment by paulmelnikow** [comment]
Have labeled this a blocker because of #2069.

**Comment by platan** [comment]
It looks good to me. This PR gives us another way to configure server, which is a good idea in my opinion. This looks similar to [externalized configuration in Spring Boot](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html), where you can configure application using several options. 
`dotenv` does not override existing environment variables ([doc](https://www.npmjs.com/package/dotenv#what-happens-to-environment-variables-that-were-already-set)). 
Conflicts must be resolved and currently `6.2.0` is the newest version of `dotenv`. 
@paulmelnikow how exactly do you want to set environment variables on our servers?

**Comment by paulmelnikow** [comment]
I opened #2621 with a proposal to use node-config which would let us check in the non-secret part of the config in the main repo. We can use dotenv with a deploy commit to set `NODE_CONFIG_ENV` in the current / legacy production deploy, and handle the secrets via checked-in `local-shields-io-public.yml` or additional checked-in environment variables.

**Comment by paulmelnikow** [comment]
Closing in favor of #2626.

**Pull request closed without merging**
