### PR TITLE
Metrics for a response size of an upstream service

### PR DESCRIPTION
**Pull request by platan**
This PR adds a metric for response size of an upstream service. I chose a histogram metric, mainly because in the histogram "Observations are very cheap as they only need to increment counters." (https://prometheus.io/docs/practices/histograms/). In histograms observations fall into buckets. Here we have buckets: 64kB, 128kB, ...,4MB, 8MB. Moreover I added a separate metric (reasons described in https://github.com/badges/shields/pull/3656#pullrequestreview-258613471).

How to test it?
```bash
METRICS_PROMETHEUS_ENABLED=true npm run start

# dynamic XML
curl "http://localhost:8080/badge/dynamic/xml.svg?color=red&label=label1&query=%2F%2Fname&url=https%3A%2F%2Fraw.githubusercontent.com%2Fhsz%2Fidea-gitignore%2Fmaster%2Fresources%2FMETA-INF%2Fplugin.xml"

# dynamic YAML
curl "http://localhost:8080/badge/dynamic/yaml.svg?color=red&label=label1&query=%24.trailingComma&url=https%3A%2F%2Fraw.githubusercontent.com%2Fbadges%2Fshields%2Fmaster%2F.prettierrc.yml"

# dynamic JSON
curl "http://localhost:8080/badge/dynamic/json.svg?color=red&label=label1&query=%24.name&url=https%3A%2F%2Fraw.githubusercontent.com%2Fbadges%2Fshields%2Fmaster%2Fpackage.json"

# non-dynamic
curl "http://localhost:8080/appveyor/ci/gruntjs/grunt.svg"

# results
curl "http://localhost:8080/metrics" -s | grep "service_response_bytes"
```
<details>
<summary>example result</summary>

```
# HELP service_response_bytes Service response size in bytes
# TYPE service_response_bytes histogram
service_response_bytes_bucket{le="65536",type="dynamic-xml"} 1
service_response_bytes_bucket{le="131072",type="dynamic-xml"} 1
service_response_bytes_bucket{le="262144",type="dynamic-xml"} 1
service_response_bytes_bucket{le="524288",type="dynamic-xml"} 1
service_response_bytes_bucket{le="1048576",type="dynamic-xml"} 1
service_response_bytes_bucket{le="2097152",type="dynamic-xml"} 1
service_response_bytes_bucket{le="4194304",type="dynamic-xml"} 1
service_response_bytes_bucket{le="8388608",type="dynamic-xml"} 1
service_response_bytes_bucket{le="+Inf",type="dynamic-xml"} 1
service_response_bytes_sum{type="dynamic-xml"} 36918
service_response_bytes_count{type="dynamic-xml"} 1
service_response_bytes_bucket{le="65536",type="dynamic-yaml"} 1
service_response_bytes_bucket{le="131072",type="dynamic-yaml"} 1
service_response_bytes_bucket{le="262144",type="dynamic-yaml"} 1
service_response_bytes_bucket{le="524288",type="dynamic-yaml"} 1
service_response_bytes_bucket{le="1048576",type="dynamic-yaml"} 1
service_response_bytes_bucket{le="2097152",type="dynamic-yaml"} 1
service_response_bytes_bucket{le="4194304",type="dynamic-yaml"} 1
service_response_bytes_bucket{le="8388608",type="dynamic-yaml"} 1
service_response_bytes_bucket{le="+Inf",type="dynamic-yaml"} 1
service_response_bytes_sum{type="dynamic-yaml"} 84
service_response_bytes_count{type="dynamic-yaml"} 1
service_response_bytes_bucket{le="65536",type="dynamic-json"} 1
service_response_bytes_bucket{le="131072",type="dynamic-json"} 1
service_response_bytes_bucket{le="262144",type="dynamic-json"} 1
service_response_bytes_bucket{le="524288",type="dynamic-json"} 1
service_response_bytes_bucket{le="1048576",type="dynamic-json"} 1
service_response_bytes_bucket{le="2097152",type="dynamic-json"} 1
service_response_bytes_bucket{le="4194304",type="dynamic-json"} 1
service_response_bytes_bucket{le="8388608",type="dynamic-json"} 1
service_response_bytes_bucket{le="+Inf",type="dynamic-json"} 1
service_response_bytes_sum{type="dynamic-json"} 10043
service_response_bytes_count{type="dynamic-json"} 1
service_response_bytes_bucket{le="65536",type="base"} 1
service_response_bytes_bucket{le="131072",type="base"} 1
service_response_bytes_bucket{le="262144",type="base"} 1
service_response_bytes_bucket{le="524288",type="base"} 1
service_response_bytes_bucket{le="1048576",type="base"} 1
service_response_bytes_bucket{le="2097152",type="base"} 1
service_response_bytes_bucket{le="4194304",type="base"} 1
service_response_bytes_bucket{le="8388608",type="base"} 1
service_response_bytes_bucket{le="+Inf",type="base"} 1
service_response_bytes_sum{type="base"} 7241
service_response_bytes_count{type="base"} 1
```
</details>

### CODE REVIEW

**Comment by paulmelnikow** [comment]
I think we have to judiciously pull concerns out of BaseService to avoid it growing huge again. Since the metrics are getting to have a few parts, what do you think about creating a `ServiceMetricsHelper` class (or similar) to encapsulate as much of this functionality as possible? It's similar to what I've done in #3652. It could be refactored in a follow-on, but I thought I'd mention it in case you wanted to tackle it before this was reviewed.

**Comment by platan** [comment]
@paulmelnikow thanks for suggestion. I agree with you. I will try to propose an improved version soon :-)  I'm closing this PR now.

**Comment by paulmelnikow** [comment]
Hi @platan I was just picking this up, and have a question both to you and the maintainer team more broadly.

Would it be worth it to collect separate stats for each service, instead of grouping together all the non-dynamic badges?

**Comment by platan** [comment]
> Would it be worth it to collect separate stats for each service, instead of grouping together all the non-dynamic badges?

@paulmelnikow It would be nice to have such stats. But we have take into account that this will produce a few thousands of new metrics (10 buckets x number of servcies). And currently we have 456 metrics (`curl --insecure https://s2.shields-server.com/metrics -s | grep -v "^#" | grep -v '^$' | wc -l`). I'm not saying it's not possible to add these metrics. But using this PR I just wanted to know the size of responses handled by dynamic badge.

**Pull request closed without merging**
