### PR TITLE
Support (Arabic) language on badges #4140

### PR DESCRIPTION
**Pull request by Aissaoui-Ahmed**
Hi everyone!

Perhaps it would be worthwhile to add a feature to Shields ❤️

Ref: #4140

before:
https://img.shields.io/static/v1?label=تسمية&message=الرسالة&color=green

https://img.shields.io/badge/يسار-يمين-green

after :
https://shields-test.herokuapp.com/static/v1?label=تسمية&message=الرسالة&color=green

https://shields-test.herokuapp.com/badge/يسار-يمين-green

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Hi! Thanks for this. I've been playing around a bit with this and continuing the discussion in #4140. 

I started to suspect a browser bug could be part of the problem here, or at least browser differences. For the record, here are screen shots taken from the top post in Chrome OS X:

Screen Shot 2019-10-06 at 7 45 20 PM

Firefox OS X:

Screen Shot 2019-10-06 at 7 45 11 PM

Safari seems to be the same as Chrome.

**Comment by paulmelnikow** [comment]
The underlying problem here is complicated and difficult to solve correctly. See metabolize/anafanafo#114 and #4140 for more details.

While this doesn't make the Arabic badges look good, they clearly are a lot better than before!

The change from `spacing` to `spacingAndGlyphs` will have an effect on every badge where the spacing is a little off, e.g.

https://img.shields.io/badge/kerning-46-brightgreen


https://img.shields.io/badge/kerning-B---brightgreen


https://img.shields.io/badge/width-probably%20incorrect-brightgreen?style=social


That's of course not a complete list, just a few that come to mind.

They all look okay in Chrome, although none are "pixel perfect."

https://shields-staging-pr-4147.herokuapp.com/badge/kerning-46-brightgreen


https://shields-staging-pr-4147.herokuapp.com/badge/kerning-B---brightgreen


https://shields-staging-pr-4147.herokuapp.com/badge/width-probably%20incorrect-brightgreen?style=social


The addition of `spacing` was to solve #746 and #848. I want to make sure this change doesn't regress that issue.

Apart from that, if the tests I briefly ran above hold up in other browsers, I think we should consider merging this as a better interim compromise until anyone wants to help solve the problem more carefully.

**Comment by Aissaoui-Ahmed** [comment]
Thanks :heart: for your support
I really don't have enough experience to say PR is ready to merge but  If it does not pose any problems, why not

**Comment by PyvesB** [comment]
Just had a brief look at this PR, this is what I'm observing on my Windows machine:
* Firefox (and similar with Edge): 
  firefox

* Opera:
opera

Definitely looks somewhat better and more readable, especially on Firefox/Edge.

**Comment by paulmelnikow** [comment]
`lengthAdjust="spacingAndGlyphs"` will distort the fonts on badges without Arabic text when the estimated and actual text lengths are wrong. Though the results on Windows for Arabic are better than before, I'd like to solve this problem with a solution that actually looks good, and the stretched glyphs do not look good. Let's continue the discussion back in #4140.

**Pull request closed without merging**
