### PR TITLE
Add [Weblate] logo

### PR DESCRIPTION
**Pull request by MichaelHinrichs**
Static Badge
Static Badge
Static Badge
Static Badge
Static Badge
Static Badge
Static Badge
Static Badge
Static Badge
Static Badge
Static Badge

### CODE REVIEW

**Comment by MichaelHinrichs** [comment]
> Warnings
> ⚠️	This PR modified service code for weblate but not its test code.
> That's okay so long as it's refactoring existing code.

What's the difference?

**Comment by PyvesB** [comment]
Hello @MichaelHinrichs 👋🏻 

As highlighted in https://github.com/badges/shields/pull/10287#issuecomment-2189909701, our contributing guidelines specify the following:
> Except for badges using the social style, logos and links should be turned off by default.

Unfortunately, this PR will not be merged.

> What's the difference?

Our documentation also explains how services and their test code fit together, I'd really encourage you to read our [tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md) to get an overview of a Shields.io service gets built.

**Comment by MichaelHinrichs** [comment]
But i like the logos.

**Comment by chris48s** [comment]
You're free to add the logo with the `&logo=` param when you embed the badges in your readme. For example:

 - https://img.shields.io/weblate/progress/godot-engine?server=https%3A%2F%2Fhosted.weblate.org&logo=weblate

They're just off by default

**Comment by MichaelHinrichs** [comment]
Well i think they should be ON by default.

**Pull request closed without merging**
