### PR TITLE
Do not rate limit in dev

### PR DESCRIPTION
**Pull request by paulmelnikow**
I ran into a rate limit while running the service tests, which seems not ideal!

I wonder if it would be better to set RATE_LIMIT=true on the server and default to false.

### CODE REVIEW

**Comment by paulmelnikow** [comment]
@RedSparr0w Would you mind giving this a look?

**Comment by RedSparr0w** [comment]
Yeah this sounds good, doesn't make sense to rate limit ourselves, Would whitelisting `localhost`/`127.0.0.1` also work?
https://github.com/badges/shields/blob/09a2ca144d6529d95e835ac7ee6acff904234a47/lib/sys/monitor.js#L21-L28

**Comment by paulmelnikow** [comment]
> Would whitelisting `localhost`/`127.0.0.1` also work?

That is a great idea! Maybe that would be a simpler way to make this change.

**Comment by paulmelnikow** [comment]
Hmm, this code doesn't have any tests, though. Maybe it's better to merge the fix I'm confident in.

**Comment by RedSparr0w** [comment]
I can't seem to hit the rate limit, I've tried setting:
```javascript
    this.period = 5000; 
    this.maxHitsPerPeriod = 10;
```
and also set `RATE_LIMIT=true`,
But still seems to pass the limit.

Even made 2 test using the static badge which ran 3500 times each and went through fine.
`/badge/test-test-blue.json`
`/badge/test${i}-test${i}-blue.json`

**Comment by paulmelnikow** [comment]
Hmm, did you run the service tests? The static badges aren't rate limited. Not sure whether cached badges would be, either.

**Comment by RedSparr0w** [comment]
That would probably be why then, just tried it on the static badge.
Will give it another go on new badge using a local JSON resource.

**Comment by paulmelnikow** [comment]
@RedSparr0w I've updated this. Would you mind taking it for another spin?

**Comment by paulmelnikow** [comment]
Since you haven't been able to reproduce this, I think I'll close it until I run into the problem again.

**Pull request closed without merging**
