### PR TITLE
Fix [Github] rate limits in CI

### PR DESCRIPTION
**Pull request by paulmelnikow**
Alternate to #1094 for fixing #979.

### CODE REVIEW

**Comment by RedSparr0w** [comment]
Looks like a good approach,
From the looks of [github-auth.js](https://github.com/badges/shields/blob/master/lib/github-auth.js#L12), the keys are stored in `/private/github-user-tokens.json` as something along the lines of:
```json
{
  "data" : [
    "yourkeyhere",
    "asecondkeyhere",
    "athirdkeyifneeded"
  ]
}
```
_although i may be wrong as i haven't actually tested it all out_

**Comment by paulmelnikow** [comment]
Cool. It's working, by the way! The CI build on this PR is running all the Github tests. I'm eager to get this fixed. I guess I was hoping for a better solution than this, though clearly I should have just done this a long time ago.

@Daniel15, would you mind reviewing this?

**Comment by Daniel15** [comment]
Looks great!

**Comment by paulmelnikow** [comment]
Thanks @Daniel15!

**Pull request merged**
