### PR TITLE
add gitee support to [JitpackVersion]

### PR DESCRIPTION
**Pull request by okou19900722**
add gitee

### CODE REVIEW

**Comment by okou19900722** [comment]
jitpack has already supported gitee. https://jitpack.io/docs/#other-git-hosts

**Comment by calebcartwright** [comment]
Thanks @okou19900722 - do you have a gitee repo/project that we can use to test?

**Comment by calebcartwright** [comment]
Review app @ https://shields-staging-pr-3531.herokuapp.com/

**Comment by PyvesB** [comment]
It might be a good idea to add tests for the different Git hosts: we'll be alerted if support for one of them is removed or if there's an issue with the API for that particular host. Probably not a blocker for this PR though. 👍

**Comment by calebcartwright** [comment]
I wasn't proposing adding an automated test. I'm not familiar with gitee, so I was just hoping to get a project name that we could use to test with in the review app

**Pull request merged**
