### PR TITLE
added ethereum logo

### PR DESCRIPTION
**Pull request by scottydelta**
added ethereum's logo from [official source](https://github.com/ethereum/ethereum.org/blob/master/public/images/ethereum_icon.svg).

### CODE REVIEW

**Comment by RedSparr0w** [comment]
Thanks for this PR, Could you also run it though [this](https://jakearchibald.github.io/svgomg/) to [minimize the file](https://github.com/badges/shields/blob/master/CONTRIBUTING.md#logos)?

**Comment by RedSparr0w** [comment]
I feel like the logo might be a little bit too small, do you think you could enlarge it to remove the transparent padding?

**Comment by scottydelta** [comment]
> Also which badges would this logo used for?
As we generally do not accept logo's which do not have a relevant badge.

I plan on using it in a hacky way to display updated prices of crypto currencies using the badges. [Gitcoin Example](https://github.com/gitcoinco/web/issues/165#issuecomment-366129199)

**Comment by RedSparr0w** [comment]
Closing as no related badge, Feel free to re-open if you feel this should still be merged.
Also feel free to comment here if you have anymore questions in regards to using the logo.

Here's a badge that may do what you were wanting though:
ether price badge
```
https://img.shields.io/badge/dynamic/json.svg?colorB=007ec6&style=flat-square&uri=https%3A%2F%2Fmin-api.cryptocompare.com%2Fdata%2Fprice%3Ffsym%3DETH%26tsyms%3DUSD&label=Ether&query=USD&prefix=$&suffix=%20USD&logo=data:image/svg%2bxml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjUwMCA1MDAgMjAwMCAyMDAwIj48cGF0aCBmaWxsPSIjRkZGIiBkPSJNMTUwMCA1MDBMODg2LjEgMTUxOC42bDYxMy45LTI3OS4xeiIvPjxwYXRoIGZpbGw9IiNGRkYiIGQ9Ik0xNTAwIDEyMzkuNWwtNjEzLjkgMjc5LjEgNjEzLjkgMzYyLjh6TTIxMTMuOSAxNTE4LjZMMTUwMCA1MDB2NzM5LjV6Ii8%2bPHBhdGggZmlsbD0iI0ZGRiIgZD0iTTE1MDAgMTg4MS40bDYxMy45LTM2Mi44LTYxMy45LTI3OS4xeiIvPjxwYXRoIGZpbGw9IiNGRkYiIGQ9Ik04ODYuMSAxNjM0LjlMMTUwMCAyNTAwdi01MDIuM3oiLz48cGF0aCBmaWxsPSIjRkZGIiBkPSJNMTQ5OS45IDE5OTcuN1YyNTAwbDYxNC4yLTg2NS4xeiIvPjwvc3ZnPg==
```

**Comment by scottydelta** [comment]
@RedSparr0w That's exactly how I was planning on using it. Do you know any good source where I can find shields.io compatible logos for various crypto currencies?

thanks

**Comment by RedSparr0w** [comment]
@scottydelta you can use any image (as long as its not too complex) by [converting it to base 64](http://b64.io/) and then [urlencode](https://www.urlencoder.org/) the base64 image.
Once you have that just add it to the image url `?logo=data%3Aimage%2Fpng%3Bbase64%2C...` (only thing that seems to **need** to be url encoded is the `+`'s though so could just replace those to make it shorter)
`?logo=data:image/png;base64,...`

**Pull request closed without merging**
