### PR TITLE
Upgrade dependencies

### LINKED ISSUE #421: Security issue on dependency
There is a security issue, should better upgrade semver to version >= 4.3.2

https://github.com/badges/shields/blob/master/package.json#L27
> "semver": "~2.3.0",

https://nodesecurity.io/advisories/semver_redos
> Vulnerable: <4.3.2  Patched: >=4.3.2

### PR DESCRIPTION
**Pull request by PeterDaveHello**
I confirmed each upgrade, only camp can not upgrade to the latest version, only v14.10.12
Every badge works every will in each commits, and all the commits pass all the test, this PR also fix #421

### CODE REVIEW

**Comment by espadrine** [comment]
Unfortunately, canvas has a subtle change that would break the width computation of every badge.

More information on that here: https://github.com/badges/shields/issues/362

**Comment by PeterDaveHello** [comment]
What about keep canvas an old version?

**Comment by espadrine** [comment]
That would be necessary, yes.

**Comment by PeterDaveHello** [comment]
I removed that commit.

**Comment by espadrine** [comment]
Thanks. I'm a bit scared, so I'll do more tests and try to do it during the week-end, so that I can be more reactive and back out if necessary.

**Comment by PeterDaveHello** [comment]
Okay :+1:

**Pull request merged**
