### PR TITLE
re-organise badge examples

### PR DESCRIPTION
**Pull request by chris48s**
Following on from https://github.com/badges/shields/pull/1762#issuecomment-406896626 I've extracted the changes to the examples. This re-shuffles the examples into categories:

- Build
- Chat
- Dependencies
- Downloads
- Funding
- Issue Tracking
- License
- Rating
- Social
- Version
- Other

#1762 can be rebased on to this later.

### CODE REVIEW

**Comment by chris48s** [comment]
Yes- good suggestion. I wrote this little script to do that:

```js
const allBadgeExamples = require('./lib/all-badge-examples');

var examples = [];
allBadgeExamples.forEach(function(category) {
  examples = examples.concat(category.examples);
});
var previewUrls = examples.map(function(example) {
  return example.previewUri;
});
previewUrls.sort();
previewUrls.forEach(function(title) {
  console.log(title);
});
console.log(previewUrls.length);
```

Running that on master and my branch revealed there were a couple of things that got lost somewhere, so I've fixed those in 0076a6e .

Now I get the same result from running that script on my branch and latest `master`. You should be able to check that if you want.

**Comment by chris48s** [comment]
For convenience, if you do want to test the way I did it was I ran that script, piped the output to a file on each branch and then diff the 2 output files.

**Comment by paulmelnikow** [comment]
Thanks for doing that!

**Comment by paulmelnikow** [comment]
This is live.

**Pull request merged**
