### PR TITLE
auto-detect default branch on [github nycrc osslifecycle]

### PR DESCRIPTION
**Pull request by chris48s**
..with this one wierd trick :sparkles: 

Shout out to @andersk for this [excellent suggestion](https://github.com/badges/shields/issues/5215#issuecomment-646375440) which allows us to solve this problem in a large number of cases with one very small code change and no impact on performance :smile: 

Arguably this makes a very slight backwards-incompatible change in that if your repo has a branch which **is** called master but which **isn't** the default, right now https://img.shields.io/osslifecycle/user/repo is looking at your master (by name) branch but this will change it to look at your default branch (whatever that is called). I'm not particularly concerned about this. I think it unlikely many users are consciously relying on that behaviour and we can regard this as a fix which brings us into line with how it should have worked in the first place/what most users will expect anyway.

As a side note, we should probably move nycrc and osslifecycle under the github service family and set up redirects, but that's another issue.

I've only addressed 

* github
* nycrc
* osslifecycle

in this PR. The other services mentioned in https://github.com/badges/shields/issues/5215#issuecomment-646293697 need a different solution (WIP), although solving this for all the affected services under the github family is not to be sniffed at.

I think this should also give us a fix for #4114 ?

There will be some failing tests due to #5230 . Once #5232 is merged, I will rebase to get the tests passing.

### CODE REVIEW

**Comment by calebcartwright** [comment]
This is a fantastically simple solution, love it!

I suppose another rather fringe case: a repo that has both `master` and `HEAD` branches, with `master` as the current default (which i think GitHub will technically let you do) :eyes: 

IMO this is still the right approach, maybe we can just enumerate the handful of edge cases like this in the issue with workarounds should anyone run into these in "real life". Just the tradeoffs we're having to make to avoid doubling the badge response time and doubling our GH token quota usage that the alternatives would've required

**Comment by chris48s** [comment]
> I suppose another rather fringe case: a repo that has both `master` and `HEAD` branches, with `master` as the current default (which i think GitHub will technically let you do)

You can't have a branch which is explicitly called `HEAD` in git:

```sh
$ git init
Initialised empty Git repository in /home/chris/temp/asdf/.git/
$ git checkout -b HEAD
fatal: 'HEAD' is not a valid branch name.
```

You also can't make a branch called `HEAD~1` or `HEAD@{1}` etc for the same reason.

..or do you mean something different?

**Comment by calebcartwright** [comment]
GitHub (not git) will apparently let you do it from the web portal which I found surprising. To your point though, doing so would be spectacularly unhelpful given the client side implications and thus not real/valid badge use case. 

I would still maintain however that as part of this change it would be a good idea to create (and pin) and issue that succinctly summarizes the change we're making, and any known edge cases and workarounds. That way if anyone _does_ encounter an edge case they can easily find the workaround, and/or report any cases we haven't seen yet (as opposed to having to go through lengthy issues/PRs)

**Comment by chris48s** [comment]
So you can :open_mouth: Every day's a school day :mortar_board: 

Screenshot at 2020-06-22 19-46-09

True story: I nearly just tried doing this on a repo I actually care about, then I realised that I might be about to make it impossible to check the repo out so I switched and did it on a test repo :rofl:  I find it incredibly surprising that github lets you do that. I might have a quick play and see what nonsense ensues if I actually try and do something with this.

Side note: I'm also working on another (less nice) PR for bitbucket, gitlab and travis ci which I'm aiming to submit tonight or tomorrow.

**Comment by chris48s** [comment]
I had a quick play with this. You're totally right that if you do create a branch called `HEAD`, github's UI/API assumes you mean HEAD (the branch) not HEAD (the ref) so if you make a branch called HEAD and its not the default then this would result in unexpected behaviour. If you try and check it out locally (at least with the version of git I have), you basically can't interact with that branch at all though so it is quite pointless. I guess you could have a branch called HEAD on a repo that you only ever interact with via the github UI, or (more likely) a branch called HEAD that you created, decided was a terrible idea but then didn't delete.
I think we both still think its the right approach in the grand scheme of things, but dammit that is an annoying edge case.

**Comment by calebcartwright** [comment]
> I think we both still think its the right approach in the grand scheme of things, but dammit that is an annoying edge case.

Absolutely, on both counts! IMHO this is much better than the alternative, and I'd rather have unexpected behavior for the hypothetical (and presumably nonexistent) HEAD branch case instead of impacting every single valid/standard badge use case. 

Have you had a chance to do any additional testing with this? The code changes and approach LGTM, though I think it'd be worth manually validating the behavior with a sample repo and contrived data if no one's done so yet

**Comment by calebcartwright** [comment]
> As a side note, we should probably move nycrc and osslifecycle under the github service family and set up redirects, but that's another issue

Agreed. I keep thinking I've convinced myself one way or the other, only to then change my mind

**Comment by chris48s** [comment]
> Have you had a chance to do any additional testing with this?

Yeah good question. I've tried making some ad-hoc requests on some repos where the default branch is/isn't master. It does appear to work as intended, but its not a super well documented feature.
In terms of automated testing, its essentially a feature of an external service so I haven't added any additional tests - I'm just relying on the existing tests to verify the change doesn't break anything really.

If you've got any other thoughts on stuff I should look at, I'm all ears..

**Comment by calebcartwright** [comment]
>  I've tried making some ad-hoc requests on some repos where the default branch is/isn't master. It does appear to work as intended, but its not a super well documented feature.

That's all I had in mind. Was going to do the same but figured I'd check first.

> In terms of automated testing, its essentially a feature of an external service so I haven't added any additional tests - I'm just relying on the existing tests to verify the change doesn't break anything really.

> If you've got any other thoughts on stuff I should look at, I'm all ears..

Nah I don't think we need anything else, sounds like it's working as expected :+1:

**Pull request merged**
