### PR TITLE
twitter isn't twitter any more

### PR DESCRIPTION
**Pull request by chris48s**
Refs #9677

Tbh, we could just drop linking to this.

@PyvesB - are you still checking https://twitter.com/shields_io ? I think you're the only person who has access to it.

### CODE REVIEW

**Review by calebcartwright — APPROVED** [review]
I thought SI would redirect/map to the X logo but oh well. I've no objections to dropping this either if folks would rather go that route

**Review by jNullj — APPROVED** [review]
I think its best to go by the new brand they set rather then the old one to keep up to date.
Small change but LGTM

**Comment by chris48s** [comment]
I'm going to just merge this for now, but we could remove in future.
It would still be nice to hear back from @PyvesB on this.

**Comment by PyvesB** [comment]
I've not actively monitored it in some time, but still have access to it.

**Comment by chris48s** [comment]
Thanks. I've followed up in https://github.com/badges/shields/pull/9685

**Pull request merged**
