### PR TITLE
[GitHub] Fixes to service tests and try.html

### PR DESCRIPTION
**Pull request by dagwieers**
So I am confused, PR #2010 was merged (in different commits) and the PR closed, but still some code was not merged as-is. Maybe a merge conflict went wrong ? Or maybe the PR was edited before it got merged.

This PR includes:
- Correcting the original commit
- Restructured/improved service tests
- Updated try.html to include proper label tests (using an actively used label)

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Huh. That was #1020, which was merged via 26093d and 8046a4, followed by 3d39cd, which this partly undoes. If you want to change the behavior we should let @espadrine weigh in on that. I'm not sure I follow what he was doing.

Fixing try.html and straight-up test improvements are no-brainers to merge though, so if you'd like to trim this back – or move those things to a different PR – I'd be happy to review it.

**Comment by paulmelnikow** [comment]
@dagwieers Thoughts? I'd like to merge a fix for the flaky Github tests.

**Comment by dagwieers** [comment]
@paulmelnikow I don't understand. This is not undoing anything from PR #2010 AFAICT, it's actually re-doing what should have been done if it would have been merged.

This is how it should have been after merging PR #2010:
https://github.com/dagwieers/shields/blob/62c470d56d230d378e595433e51baf72a1dae65c/server.js#L3373-L3378

This is how it is now after the broken merge:
https://github.com/badges/shields/blob/master/server.js#L3470-L3478

This is how this PR will make it:
https://github.com/dagwieers/shields/blob/1c9e994beea89b3f9f54fe3199c9684ec5062c53/server.js#L3401-L3406

**Comment by paulmelnikow** [comment]
Hey @espadrine, your merge of #1020 brought tests and try.html out of sync with the code. I'm not sure I understand your intent in changing the code as it was in the PR. Could you weigh in on this PR?

**Comment by paulmelnikow** [comment]
Huh. As I did further into the test failures, it seems they are due to our token handling logic and [custom rate limits in the Search API](https://developer.github.com/v3/search/). That probably needs a separate fix.

**Comment by paulmelnikow** [comment]
I moved the example badge fix to #1141.

@dagwieers If you still want to change the behavior back to what it was, could you merge master + clean up the diff so the change is clearer? If @espadrine doesn't weigh in I'll take a closer look myself.

**Pull request closed without merging**
