### PR TITLE
Fix for confusing path behavior in modal

### PR DESCRIPTION
**Pull request by paulmelnikow**
Proposed quick and dirty fix for #2495. This isn't perfect, though I think it addresses the worst of the confusing experience.

I tried to fix this in a better way but iterating on the styling is very slow. I want to address that developer experience before pushing too much further on that. Also I want to keep focused on #2495, which would change this modal in more significant ways.

### CODE REVIEW

**Comment by paulmelnikow** [comment]
This pull request **fixes 1 alert** when merging 301a8fe24256b7356f1ba9699b9cbfa63793ea14 into 1649a42a4a4865d03cb17640df8865c860f18c58 - [view on LGTM.com](https://lgtm.com/projects/g/badges/shields/rev/pr-4f035670ff67db676663fa5c447a8c97e630b5a9)

**fixed alerts:**

* 1 for Unused or undefined state property

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by chris48s** [comment]
Thanks for having a look at this. This seems like an improvement, but it also seems like we're really going to a lot of effort to avoid using `baseUrl` in the Path `<input>` but I'm not sure why its important to do that given we're using it everywhere else in the modal. What am I missing?

**Comment by paulmelnikow** [comment]
What makes the base url inconvenient is editing. The places we’re showing it aren’t editable, I don’t believe.

**Comment by chris48s** [comment]
Hmm. I wonder if we're trying to solve 2 different problems? Sometimes wordsing is hard :)


> The places we’re showing it aren’t editable, I don’t believe

That's completely true, but its also not a new constraint.

For example, if I roll back `master` to 8a8311d (the commit before we merged #2441 ), there is only one editable field and I can either use an absolute or relative URL in it:

At current `HEAD` there is there is still one editable field and I can only use a relative URL in it.

Is the thing that has actually changed that we're now supressing the preview based on whether the contents of that box contains the `:` character, which means a string like `https://` (containing a colon) is causing the preview to be suppressed?

https://github.com/badges/shields/blob/43faea45613574ea5755b82c4e0d68796327f8d7/frontend/components/markup-modal.js#L102

If so, could we solve this by detecting if placeholders are present in a slightly more sophisticated way (e.g: by testing against a regex)?

**Pull request closed without merging**
