### PR TITLE
for the badge style badges

### LINKED ISSUE #818: Feature request: forthebadge-style badges
Like in http://forthebadge.com/. Big and bold (and silly and fun).

[forthebadge](http://forthebadge.com) [forthebadge](http://forthebadge.com)

### PR DESCRIPTION
**Pull request by RedSparr0w**
closes #818 
https://forthebadge.com/ style of badges

This PR | For The Badge
:---: | :---:
image | 
image | image
image | 
image | image

### Other Examples:
image
image
image
image
image
Also supports logos:
image

### CODE REVIEW

**Comment by paulmelnikow** [comment]
I booted up the review app. This SVG image is being served from there:



Neat!

**Comment by RedSparr0w** [comment]
That deployment feature is pretty cool!

**Comment by RedSparr0w** [comment]
I think it would be useful to also in the future add an option `textColorA` or something along those lines, as the white can be hard to see on some of the lighter color backgrounds.
Also the same thing for logos `logoColor` would be useful, as the github logo can only really be used on social style badges if you want the text color to match, or if you change the background color

**Comment by tooomm** [comment]
It should be listed here as well I guess?

styles

**Comment by paulmelnikow** [comment]
Agreed about the color features. There's a really old request open for that (#504).

> It should be listed here as well I guess?

Yea, good call!

**Comment by RedSparr0w** [comment]
Not sure how i missed that!
Updated.

I added it above the `social` style badge because for me it looked strange below it,
Can move it if you like though 😄 
image
image

>Agreed about the color features. There's a really old request open for that (#504).

There always seems to be a relevant issue somewhere 😆 
Will make a PR soon with `fontColorA` & `fontColorB`

**Comment by paulmelnikow** [comment]
> There always seems to be a relevant issue somewhere 😆

Hehe… we're indeed fortunate to have such a rich backlog of requests!

If you'd like to see everything related to badge generation and the core service, you could look at [core](https://github.com/badges/shields/labels/core) issues. We could consider making a focused push to burn down that list, since they're the kind of feature that might be difficult for new contributors.

**Pull request merged**
