### PR TITLE
Add Liberapay logo

### PR DESCRIPTION
**Pull request by mattbk**
Add optional logo for Liberapay badges.

Part of https://github.com/liberapay/liberapay.com/issues/1103.

- [x] Please ensure your contribution follows our guidance for logo submissions.

### CODE REVIEW

**Comment by RedSparr0w** [comment]
Thanks for submitting this PR! 
👍 

Could you remove the extra background elements from the 2nd and 3rd logos,
And also run them through something like [svgomg](https://jakearchibald.github.io/svgomg/).

I'm not sure how we would be wanting to go about merging multiple logos variants, maybe @paulmelnikow has some ideas about this?

On that note though, i would be fine with just merging the 3rd logo for now () until we get more info on adding the extra variants:
_(`liberapay3.svg` &rarr; `liberapay.svg`) Could either update this PR or open a secondary PR_


Examples:
Logo1:


Logo2:


Logo3:

**Comment by mattbk** [comment]
It's a work in progress. I'm running the variants by people at https://github.com/liberapay/liberapay.com/issues/1103 and don't need review yet.

**Comment by mattbk** [comment]
SVG has been optimized and variants removed. Ready for review.

**Comment by RedSparr0w** [comment]
Thanks for the changes,
Logo looks good to me:



Merged!
👍

**Comment by fliiiix** [comment]
@mattbk big thank you! do you know how long it usually takes until these badges are online?

**Comment by RedSparr0w** [comment]
>do you know how long it usually takes until these badges are online?

Quoting @paulmelnikow:

> Deploys usually happen every 1–3 weeks. Thaddée [@espadrine], who has limited time on this project, is the only sysadmin. He's working on giving me access to deploy and logs, but doing so is complicated because the hosting account (and maybe the servers too) are shared with other services he runs.

**Pull request merged**
