### PR TITLE
Update http://shields.io/ tool for new Sonarqube API (since 5.4)

### PR DESCRIPTION
**Pull request by sgrillon14**
Update http://shields.io/ tool for new Sonarqube API since version 5.4: https://sonarqube.com/web_api/api/resources (deprecated since 5.4)

### CODE REVIEW

**Comment by sgrillon14** [comment]
I valid in my dev macbook:
capture d ecran 2017-04-03 a 23 14 10

**Comment by paulmelnikow** [comment]
Thanks again for your contribution!

Let's make the Sonar badges default to the latest supported version of Sonar. That way users of the online version don't have to update their badges every time the API changes. Other users can lock their badge onto the version of their choice.

Could you make the URLs like `sonar/5.1/http`? The idea is that `sonar/5.4/http`, `sonar/6.3/http`, and `sonar/http` – with no version – would all do the same thing.

**Comment by sgrillon14** [comment]
no doing sonar/5.1/http !!

Old API (older than 5.4) is OK

sonar/http  OK
sonar5.1/http  OK
sonar5.4/http  OK
sonar6.3/http  OK

**Comment by paulmelnikow** [comment]
I'm not sure we're understanding each other.

Instead of using the earliest version by default, it would be better to use the latest version.

**Comment by sgrillon14** [comment]
All users of bage can be use the same API:
`/sonar{target_version}/{http|https}/{sonar_target_url}/...` or `/sonar/{http|https}/{sonar_target_url}/...`

Example:
`/sonar6.3/http/sonarqube.com/...` or `/sonar/http/other-sonar-in-the-world.com/...`


For now there are only two versions (<5.4 or> 5.4) but in the future there may be other changes. 
The badge code can manage all versions.

**Comment by victornoel** [comment]
@sgrillon14 could you change the format of the URL to be instead:
```
/sonar/4.1/http/sonarqube.com/...
/sonar/5.0/http/sonarqube.com/...
/sonar/5.1/http/sonarqube.com/...
/sonar/5.2/http/sonarqube.com/...
/sonar/5.3/http/sonarqube.com/...
/sonar/5.4/http/sonarqube.com/...
/sonar/5.5/http/sonarqube.com/...
/sonar/6.0/http/sonarqube.com/...
```

And also have:
```
/sonar/http/sonarqube.com/...
```
be working like `> 5.4` for now (and later we will adapt the code if it changes again).

**Comment by victornoel** [comment]
`/^\/sonar(.*)\/(http|https)\/(.*)\/(.*)\/(.*)\.(svg|png|gif|jpg|json)$/` becomes `/^\/sonar\/(.*)\/(http|https)\/(.*)\/(.*)\/(.*)\.(svg|png|gif|jpg|json)$/`

**Comment by sgrillon14** [comment]
change `/sonarX.X/http/sonarqube.com/..`.  or `/sonar/http/sonarqube.com/...` to `/sonar/4.1/http/sonarqube.com/...` is not a good idea because old API do not work.

with regexp `/^\/sonar(.*)\/(http|https)\/`    you can use `/sonar{target_version}/{http|https}/`

Note: `{target_version}` is not mandatory, you can use `/sonar/{http|https}/` (for old API)

**All users of badge can be use the same API:**
`/sonar{target_version}/{http|https}/{sonar_target_url}/...` or `/sonar/{http|https}/{sonar_target_url}/...`


If you put /^\/sonar(\/.*)?\/(http|https)\/ you can have /sonar//(http/....   if you network use SSO, // is prohibited and you have a 404 error  503 forbidden.

Please keep `/^\/sonar(.*)\/(http|https)\/(.*)\/(.*)\/(.*)\.(svg|png|gif|jpg|json)$/` because is it better.

**Comment by victornoel** [comment]
> change /sonarX.X/http/sonarqube.com/... or /sonar/http/sonarqube.com/... to /sonar/4.1/http/sonarqube.com/... is not a good idea because old API do not work.

you should also support `/sonar/http/sonarqube.com/...`, see next comment.

> If you put `/^/sonar(/.*)?/(http|https)/` you can have `/sonar//(http/....` if you network use SSO, `//` is prohibited and you have a 404 error 503 forbidden.

No you don't: the first `/` is included in the optional group (note the `?`). With this regex you can either write `/sonar/http/...` or `/sonar/51/http...` but not `/sonar//http...`.
Well, technically you can, because you used `.*` instead of `[0-9]+`, so you should use:
```
/^\/sonar(\/[0-9]+)?\/(http|https)\/(.*)\/(.*)\/(.*)\.(svg|png|gif|jpg|json)$/
```

**Comment by christian-draeger** [comment]
Any news on that one? Would be really nice to have it working :)

**Comment by cyChop** [comment]
@victornoel I suppose you should add the dot as authorized character to the version part of your regex if we want to allow for `major.minor` version notation.

```
/^\/sonar(\/[0-9.]+)?\/(http|https)\/(.*)\/(.*)\/(.*)\.(svg|png|gif|jpg|json)$/
```

**Comment by paulmelnikow** [comment]
If anyone would like to adopt this PR, please feel free to do so: grab the branch, add more commits addressing the comments, and open a new PR referencing this one. Will close in one month if no one has done so.

**Comment by paulmelnikow** [comment]
Closing for inactivity. If you're reading this and want this implemented, don't be discouraged. You can grab the commits from the pull request branch using `git fetch origin pull/931/head:pr-931`, address the comments, and reopen.

**Pull request closed without merging**
