### PR TITLE
Supporting status as query parameter

### PR DESCRIPTION
**Pull request by leog**
Adding a status parameter to override the right-hand-side text of a badge.
This implements feature request on #835

### CODE REVIEW

**Comment by espadrine** [comment]
Thanks for your patch!

Query parameters are meant to have an effect on all badges; they mustn't be badge-type-dependent.

**Comment by leog** [comment]
@espadrine Gotcha. I though it made sense to include it just on the general badge in order to avoid customizing the other badges which could potentially defeat the whole purpose of having them in the first place. Seemed like the general badge was general enough to include it there alone.

Taking into account my situation describen on #835, should I try to work on applying it to the other badges as well?

Thanks a lot in advance.

**Comment by leog** [comment]
@espadrine would appreciate a response on this to manage other options, although seems like a perfectly good feature to customize better a badge

**Comment by leog** [comment]
Closing in favor of direct implementation presented on #852 rather than this workaround.

**Pull request closed without merging**
