### PR TITLE
Changed endpoint `star` to `stars`

### PR DESCRIPTION
**Pull request by binhbbui411**

### CODE REVIEW

**Comment by paulmelnikow** [comment]
(Reopen of #1597)

**Comment by PyvesB** [comment]
> Given this hasn't been deployed yet I think its reasonable to change the endpoint because every other service uses /stars as opposed to /star and there is no backwards-compatibility to break yet.

Careful, we have now deployed these badges, so there may be an impact on early user. 😉

**Comment by binhbbui411** [comment]
@PyvesB I have noticed that today too! It's awesome that we have the badge ready now. Huge thanks to the team!  
  
And yes I will take responsibility for my code. 💪

**Comment by chris48s** [comment]
> Careful, we have now deployed these badges, so there may be an impact on early users

I had spotted this complication. Given that if we merge this now, there's probably a few weeks between now and the next deploy, I think it would be better if the examples say `/stars` but the regex/case statement accepts `star|stars` so we don't unexpectedly break badges for people who have adopted it in the meantime.

Do you mind making that change @binhbbui411 - apologies for the bad timing

**Comment by PyvesB** [comment]
@chris48s there are quite a few issues with the current deployment (see all the issues opened by @paulmelnikow in the past hours), so I suspect we might be deploying sooner than in a few weeks. Should we take that into account?

**Comment by binhbbui411** [comment]
@chris48s @PyvesB No problem, that makes sense as well. I have committed those changes.  
  
Also, we have only announced the badge to our internal staffs, so if you guys plan to make the next deploy in the next 2 weeks, I can postpone the announcement to our users and thus, accept only the endpoint `star` for the consistency. I would like to get a notice about that.

**Pull request merged**
