### PR TITLE
deprecate [lgtm]

### LINKED ISSUE #8770: Deprecate LGTM
:clipboard: **Description**

On 16 December 2022 lgtm.com was shut down

https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/#16th-of-december-lgtm-com-will-be-shut-down

We should deprecate the service and also remove the dead LGTM badge from our own README.

@PaulaBarszcz - if you were looking for a quick issue to pick off, this is a nice easy bit of maintenance. When upstream services go away like this, first we convert them to a `deprecatedService` before eventually removing the route completely. This PR is a good example https://github.com/badges/shields/pull/8501

(also I need to circle back to https://github.com/badges/shields/pull/8621 but that is another issue)

### PR DESCRIPTION
**Pull request by PaulaBarszcz**
Closes #8770 

For now, I didn't touch `lgtm/lgtm-redirector.service.js`. We can probably delete this redirector in the same PR in which we will remove the deprecated LGTM services.

### CODE REVIEW

**Comment by PaulaBarszcz** [comment]
@chris48s 

Do you happen to know why this test failed? :)

https://github.com/PaulaBarszcz/shields/actions/runs/3832990295/jobs/6523944332

image

**Comment by chris48s** [comment]
> Do you happen to know why this test failed?

It looks like the build failed trying to download Node JS 17. I think its a transient failure - if you restart the build it'll probably just pass. Same build worked on the PR: https://github.com/badges/shields/actions/runs/3833016010/jobs/6523998906

**Comment by chris48s** [comment]
Having had a look over this I think it is good to merge, but the PR is still marked as draft. Is there anything else you wanted to do to it?

**Comment by PaulaBarszcz** [comment]
> Having had a look over this I think it is good to merge, but the PR is still marked as draft. Is there anything else you wanted to do to it?

The only question was about the failing build :) Marked as Ready for review, thanks

**Review by chris48s — APPROVED** [review]

**Pull request merged**
