### PR TITLE
[Github] Populate Service Test 

### PR DESCRIPTION
**Pull request by webcaetano**
Multiple github service tests

Merge this PR will also auto merge #745 and #756 

Related to #937

### CODE REVIEW

**Comment by webcaetano** [comment]
@paulmelnikow *rebased*

**Comment by webcaetano** [comment]
I'll remake this soon in order to eliminate unnecessary conflicts

**Comment by webcaetano** [comment]
Remaked

**Comment by paulmelnikow** [comment]
Hey, just wanted to say that I started reviewing this. Will hopefully wrap it up at some point this weekend.

**Comment by webcaetano** [comment]
ok, thanks

**Comment by paulmelnikow** [comment]
Cherry-picked and merged via 8ec2b6b.

**Pull request closed without merging**
