### PR TITLE
Add support for international iTunes App Store requests, rating badge, minimum iOS version badge

### PR DESCRIPTION
**Pull request by cyrille-legrand**
Some apps are only available on non-US App Stores, and the default request will return zero results.

This new badge is a clone of the original, country-neutral iTunes badge, which supports such apps.

Test it with /itunes/v/fr/484006842.svg
(Equidia app, only available in French App Store -- default badge will show "invalid" while international badge should show "4.7.1" as of today)

### CODE REVIEW

**Comment by PyvesB** [comment]
Hello @cyrille-legrand !

Thanks for your contribution! This seems very similar to pull request #1504, am I right? If so, we should probably fit the best parts of both pull requests into a single one and close the other. 😉

**Comment by cyrille-legrand** [comment]
Agreed. I'll tackle this tomorrow.

**Comment by cyrille-legrand** [comment]
I have updated my pull request to use the same method as #1504 (common regex for international and country-specific request), and to use `const` instead of `var`. (Sorry, my JavaScript-foo is quite a bit behind these days...)
Hope these changes adhere to your specifications.

I plan on adding other iTunes badges such as App Store rating, minimum required iOS version, release dates, … but not in the immediate future. Should I make another pull request (as these are new features), or should I update this one?

**Comment by cyrille-legrand** [comment]
Alright, I managed to find the time to add Rating and Minimum iOS version badges too.

**Comment by RedSparr0w** [comment]
Thanks for your PR,
I should have some time next week to do a full review (if anyone else has some time feel free 😄)
Here's a couple of quick notes for now though:
- could you add `[iTunes]` to your PR title (this will run the iTunes tests)
- will need some tests to be added for the new badges
- while your updating the iTunes badge could you also update [this line](https://github.com/badges/shields/pull/1515/files#diff-78c12f5adc1848d13b1c6f07055d996eR2082) to use the new helper:
https://github.com/badges/shields/blob/75503ec5144b349ab42c4877b774d3acac8157f3/server.js#L6515-L6518

**Comment by paulmelnikow** [comment]
Hi! Whoever picks this up, could you please merge master into this branch before continuing? A bunch of files moved around in #1563. Thanks!

**Comment by paulmelnikow** [comment]
Closing for inactivity. If you're reading this and want this implemented, don't be discouraged. You can grab the commits from the pull request branch using `git fetch origin pull/1515/head:pr-1515`, address the comments, and reopen.

**Pull request closed without merging**
