### PR TITLE
Activating Open Collective

### PR DESCRIPTION
**Pull request by asood123**
This pull request adds backers and sponsors from your Open Collective https://opencollective.com/shields ❤️
  
  It adds two badges at the top to show the latest number of backers and sponsors. It also adds placeholders so that the avatar/logo of new backers/sponsors can automatically be shown without having to update your README.md. [[more info](https://github.com/opencollective/opencollective/wiki/Github-banner)]. See how it looks on [this repo](https://github.com/apex/apex#backers).
We have also added a `postinstall` script to let people know after `npm|yarn install` that you are welcoming donations (optional). [[More info](https://github.com/OpenCollective/opencollective-cli)]
You can also add a "Donate" button to your website and automatically show your backers and sponsors there with our widgets. Have a look here: https://opencollective.com/widgets

  P.S: As with any pull request, feel free to comment or suggest changes. The only thing "required" are the placeholders on the README because we believe it's important to acknowledge the people in your community that are contributing (financially or with code!).

  Thank you for your great contribution to the open source community. You are awesome! 🙌
  And welcome to the open collective community! 😊

  Come chat with us in the #opensource channel on https://slack.opencollective.com - great place to ask questions and share best practices with other open source sustainers!

### CODE REVIEW

**Comment by paulmelnikow** [comment]
@espadrine Looks like you set this up! I guess this is because [Gratipay is shutting down](https://gratipay.com/).

Are you keen to go ahead and use Open Collective?

I did set up a monitoring service (#1245) which I'd love to keep running if users are willing to fund it.

I'm thinking we should change up the tiers. Given the relatively small role Shields plays in many, many projects, I think a lot of folks might consider backing at something like $10/year. In fact I think we're more likely to get 60 backers @ $10/year than 10 backers @ $5/month.

Maybe the sponsor level could be $25/month instead of $100/month.

**Comment by paulmelnikow** [comment]
In terms of the PR, I'd probably drop the postinstall since hardly anyone uses this as a library, and also the Credits section which is duplicated into CONTRIBUTING.md, which reduces the impact of that document. The longer it is, the less likely people are to read it, and that's more important.

We should also add it to the web page. Question @asood123: one of our core features is "no tracking." Any suggestions for how we could include backers in our website without our users getting tracked by Open Collective? Unless they click, that is.

**Comment by asood123** [comment]
@paulmelnikow You can change the tiers (once you log in to edit your collective) to support annual donations, instead of monthly one.

Re: postinstall, feel free to change the PR and drop commits that you don't need.

Re: Tracking. Do you mean that you don't want to hit an Open Collective url to fetch avatars on your website?

**Comment by paulmelnikow** [comment]
> Re: Tracking. Do you mean that you don't want to hit an Open Collective url to fetch avatars on your website?

Yes, that's right. Perhaps we could fetch it through an anonymizing proxy.

**Comment by asood123** [comment]
Anonymizing proxy is fine. I don't think we have to make any changes in that case, right?

**Comment by paulmelnikow** [comment]
I updated the tiers:

https://opencollective.com/shields

**Comment by paulmelnikow** [comment]
I changed the backer tier from annual to a one-time donation. I think that might improve the amount we're able to raise overall.

**Comment by paulmelnikow** [comment]
Closing in favor of #1295.

**Pull request closed without merging**
