### PR TITLE
Nudge forward style checks a la eslint-config-standard

### PR DESCRIPTION
**Pull request by paulmelnikow**
Because I despise nitpicking stuff like indentation and spacing in pull request comments, I'd like to nudge forward our automated style checking, at least for new files being added.

I don't want to totally rewrite server.js just to get automated style checking… the blame tracking is just too useful. So let's it's just take care of that when we start splitting it out.

More discussion in #948.

### CODE REVIEW

**Comment by paulmelnikow** [comment]
I'd support dropping it in for the files except server.js. Here's what I wrote about Prettier in #948:

> I'm open to pursuing Prettier at some point in the future. It seems a much better solution for formatting. However it doesn't handle the semantic issues, so it doesn't keep us from also needing an eslint config.

**Comment by Daniel15** [comment]
Thanks @paulmelnikow, I missed that comment 

> However it doesn't handle the semantic issues, so it doesn't keep us from also needing an eslint config.

That's true. However, using a combination of ESLint + Prettier works well. I think you can even run Prettier via ESLint (that is, there's a custom ESLint rule that runs Prettier).

**Comment by paulmelnikow** [comment]
>  However, using a combination of ESLint + Prettier works well.

I'm definitely down for that! Let's do it.

**Comment by Daniel15** [comment]
I think this is the ESLint plugin I was thinking of: https://github.com/prettier/eslint-plugin-prettier. It supports only running prettier on files that have a particular docblock tag in them (eg. `@prettier`), which we could add to all files except `server.js`. This is similar to what we do internally at Facebook (except we have some custom integration rather than using this particular ESLint plugin).

There's also [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) that disables ESLint rules that conflict with Prettier. This lets you use some shared ESLint config along with Prettier and not experience any conflicts.

**Pull request merged**
