### PR TITLE
[GitHub] badge for (pre-)release date

### PR DESCRIPTION
**Pull request by ritwickdey**
URI : `github/release-date/:user/:repo/all.svg`

Actually, there has URI for *release version* badge like that -
[/github/release/Cockatrice/Cockatrice.svg](https://img.shields.io/github/release/Cockatrice/Cockatrice.svg) `full release`
[/github/release/Cockatrice/Cockatrice/all.svg](https://img.shields.io/github/release/Cockatrice/Cockatrice/all.svg) `included pre-release`

So, for consistency, I've done *release date* like that - 
[/github/release-date/Cockatrice/Cockatrice.svg](https://img.shields.io/github/release-date/Cockatrice/Cockatrice.svg) `full release` (Previously Merged #1122)
[/github/release-date/Cockatrice/Cockatrice/all.svg](https://img.shields.io/github/release-date/Cockatrice/Cockatrice/all.svg) `included pre-release` (This PR)

image

https://github.com/badges/shields/pull/1122#issuecomment-334113759

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Thanks for this!

In terms of the URL, indeed, we've got `https://img.shields.io/github/release/qubyte/rubidium/all.svg`, and it looks like that is an old badge. Though we also have a number of pre-release _version_ badges, and all of those use `/vpre`.

Since there are more `vpre`, how about we try to standardize in that direction? `releasepre` and `release-datepre` don't look so great, so I think we should use `release-pre/` and `release-date-pre/`.

Does that make sense?

No need to change `release/` in this PR. Just `release-date/.../all` -> `release-date-pre`.

**Comment by tooomm** [comment]
I guess that's a bit tricky. Since the `/all` version will return simply all releases (normal releases AND prereleases, not only prereleases). Prereleases just happen to be the latest releases available, if there are any.

If there are none, then `https://img.shields.io/github/release/qubyte/rubidium/all.svg` will return the same as `https://img.shields.io/github/release/qubyte/rubidium.svg`.

**Comment by ritwickdey** [comment]
Yep! @tooomm  is right.

Actually there is no API for getting pre-release. `All` means, it is the most latest release (may be Pre or may be NOT).  [Previous `release/` works like that. So I've done like that ]

I think, if I do this `release-date-pre` , then all I've to do - just filter the received data .

**Comment by paulmelnikow** [comment]
Hmm. Is this different from the behavior of `vpre`?

**Comment by ritwickdey** [comment]
`/release/qubyte/rubidium/all` & `/release/qubyte/rubidium` is giving same result.
As `all` picks the most lastest version (may or may not PRE).

image

As case here.

**Comment by paulmelnikow** [comment]
These two badges are both showing

screen shot 2017-10-06 at 1 16 35 pm

https://img.shields.io/nuget/v/Microsoft.AspNet.Mvc.svg
https://img.shields.io/nuget/vpre/Microsoft.AspNet.Mvc.svg

**Comment by ritwickdey** [comment]
ok ok! I got that. Okay, I'm just changing the route

**Comment by tooomm** [comment]
>I think, if I do this release-date-pre , then all I've to do - just **filter the received data**.

If that would be possible, that surpasses the way `/all` works right now for surel
An actual badge that consistently shows only prerelease data all the time would be nice.

**Comment by paulmelnikow** [comment]
> An actual badge that consistently shows only prerelease data (date, downloads, ...) all the time would be nice.

I'm not sure I get it. If 2.0.0-rc2 were followed by 2.0.0, why would it be helpful to see 2.0.0-rc2?

**Comment by paulmelnikow** [comment]
Github service tests passing locally when merging master + applying the patch from #1112, except a couple services, unaffected here, which are timing out.

```
  1) Github Commits since by latest release
	[ GET http://localhost:1111/github/commits-since/microsoft/typescript/latest.json ]:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.


  2) Github github issue author
	[ GET http://localhost:1111/github/issues/detail/u/badges/shields/979.json ]:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

Working on fixing the timeout in MarkHerhold/IcedFrisby#71.

**Comment by tooomm** [comment]
>I'm not sure I get it. If 2.0.0-rc2 were followed by 2.0.0, why would it be helpful to see 2.0.0-rc2?

You might be right, in case you just published a new version... your `pre-release` badge would be outdated because there is no newer pre-release than `release` yet.

**Comment by ritwickdey** [comment]
Honestly, I think so 😄 👍 

Btw, thanks for the merging

**Pull request merged**
