### PR TITLE
Moving text width measure to it's own function, with cache

### PR DESCRIPTION
**Pull request by ElNounch**

### CODE REVIEW

**Comment by espadrine** [comment]
Thanks for contributing!

Do you have benchmark figures that justify the cost of RAM?

As an aside, all of the RAM of our current Heroku instances is currently allocated, so we'll have to wait for us to move to new servers to merge this.

**Comment by AdrieanKhisbe** [comment]
now we are not on heroku I think we can merge it :)

**Comment by espadrine** [comment]
I'd like to further compare this to what https://github.com/badges/shields/pull/496 gives.

**Comment by olivierlacan** [comment]
There's no feedback from @ElNounch in nearly two years. I'm going to close this and @espadrine can re-open it if #496 didn't provide the benefits this offers.

**Pull request closed without merging**
