### PR TITLE
adding Scrutinizer CI's logo

### PR DESCRIPTION
**Pull request by salaros**

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Hi! Thanks for this. Has this been run through SVGo?

**Comment by salaros** [comment]
Yes, but than it was tweaked a little bit in order to match the style of other icons I found in logo folder

For example I used a compact header, such as:

`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 40">`

instead of something like:

`<svg xmlns="http://www.w3.org/2000/svg" version="1.2" baseProfile="tiny" width="40" height="40">`

etc

**Comment by RedSparr0w** [comment]
Thanks for this,
Looks good to me.

image
image
image
image
image

Just checking that this is the correct color logo to use though as all the logos i could find are using
- white on top, grey on bottom
image
- blue on top, grey on bottom
image
- blue on top, white on bottom
image

**Comment by salaros** [comment]
yeah, try using the blue-on-top and white-on-bottom logo in a small form factor and dark color scheme (of the label) you will notice that only white-on-bottom part is actually visible and the blue part is mixes with the dark grey label bg color

**Comment by salaros** [comment]
As you might have noticed Travis CI uses colored icon, AppVeyor has light blue one etc, but all icons in logo folder are in b/w (or so-called better grays) scheme. IMO we just have to tweak the icon so it works with the light version of the label.

BTW have you done the same check for other icons?
Here is an example of what Dockbit logo looks like on a light gray social-like badge:

[Dockbit logo fail]()

`[Dockbit logo fail]()`

**Comment by RedSparr0w** [comment]
I dont think it's too much of an issue if it doesn't look great on the social style badge as that wouldn't be a common use case for this particular badge.
Was just making sure that all the official options had been tried before we merge.

:+1: Thanks for you contribution!

**Pull request merged**
