### PR TITLE
Website revamp/redesign

### PR DESCRIPTION
**Pull request by mbrandau**
I redesigned the website using Bootstrap 4. Now it's responsive and better looking in my opinion.
If you don't like it, no problem, but I thought the current version needed some changes. :smile:

Please tell me what you guys think.

desktop
mobile
The design is not quite finished. I thought it would be better to get some opinions in first.

### CODE REVIEW

**Comment by paulmelnikow** [comment]
I like it! Seems like an improvement.

**Comment by paulmelnikow** [comment]
I like it! Seems like a big improvement.

I wonder if it's possible to avoid so many boilerplate classes to the elements for each badge, and also whether the original badge lines could be kept as is, for benefit of the other open PRs.

**Comment by paulmelnikow** [comment]
In #1163 I did some work on the code generation for the badge portion of the web page. After that's done it should be much easier to modify the badge rendering independent of the data. I think that, and a more modern frontend build system, would be a nice foundation for a frontend redesign.

In the meantime, could you merge master into this branch so I can deploy a Heroku review app? Might be nice for people to play around with what you've started!

**Comment by PyvesB** [comment]
This seems like a promising piece of work! Maybe it would be better to put the URL on the same line as the badge and its title, in order to save some space? You seem to fit significantly less badges per screen than the current page does, with the ever growing number of badges the page may become gigantic. Of course that's only my personal opinion. :wink:

**Comment by tooomm** [comment]
Any updates or progress around here?

**Comment by wow-apps** [comment]
@tooomm seems not ...
I have an idea to make new UI with new feature 'Create collection' .. I'll create an issue and make pull request in a few weeks )

**Comment by paulmelnikow** [comment]
Going to close this for now. For sweeping overhauls, I wonder if we should start with some visual designs? Or possibly starting with some more incremental changes to the user experience?

**Comment by PyvesB** [comment]
@mbrandau and @wow-apps you seemed to have some promising ideas to improve the homepage, wouldn't you be interested in giving it another shot? 😃

**Comment by chris48s** [comment]
Given we've refactored the front-end to use ReactJS since this was started, it would probably be quite hard to directly resurrect this PR. That said, one of the other things we have done since this PR was closed is we've decoupled the badge examples from the presentation. That would make something like this much easier to work on and less likely to create conflicts with other ongoing work.

**Comment by mbrandau** [comment]
Just had a quick look at it again. The new frontend seems promising. As @paulmelnikow proposed, I will create an issue and start with some designs.

**Pull request closed without merging**
