### PR TITLE
added coon integration

### PR DESCRIPTION
**Pull request by comtihon**
Added [coon](https://github.com/comtihon/coon) Erlang build tool integration.
* badge for coon package version
* badge for Erlang build system
* badge for Erlang version

Everything is tested locally but `http://coon.justtech.blog/badge/` is not running now (service will be up in several days).

### CODE REVIEW

**Comment by paulmelnikow** [comment]
if anyone would like to adopt this PR, please feel free to do so: grab the branch, add more commits addressing the comments, and open a new PR referencing this one. Will close in one month if no one has.

**Comment by comtihon** [comment]
Hi,
Please, don't close this pr.
I have a lack of time now, but I'll write the test (also I need to learn java script to understand how can I do it)

**Comment by paulmelnikow** [comment]
Perhaps someone else could help out with the tests so we can get this feature added.

**Comment by paulmelnikow** [comment]
I know you want this implemented, so please don't be discouraged. The commits aren't going anywhere. You can reopen it when you're ready.

If anyone else would like to help, you can grab the commits from the pull request branch using `git fetch origin pull/1032/head:pr-1032`, address the comments, and reopen.

**Pull request closed without merging**
