### PR TITLE
Bugfix: override colorB in [docker] badges

### PR DESCRIPTION
**Pull request by platan**
Problem described here: https://github.com/badges/shields/pull/1675#discussion_r186843360
Before:
before
After:
after

### CODE REVIEW

**Comment by RedSparr0w** [comment]
Do you think it would be a good idea to also update the default docker color to match the logo?

color | badge | note
:--: | :--: | :--:
`#008BB8` | 008BB8 | Current docker badge color
`#099CEC` | 099CEC | Matches light colored logo
`#066DA5` | 066DA5 | Matches dark colored logo
`#007EC6` | 099CEC | Shields.io blue

**Comment by platan** [comment]
@PyvesB  @RedSparr0w  I guess `#008BB8` comes from previous logo https://blog.docker.com/2013/06/announcing-new-docker-style/. All 3 of 4 docker badges are using this color so I decided to change `blue` to #008BB8. 
Updating default color is a good idea. I will change it to dark version (`#066DA5`). Please let me know if you prefer light one.

**Comment by platan** [comment]
PR name updated, all tests are passing.

**Comment by platan** [comment]
@RedSparr0w and @PyvesB Thank you for reviews.

**Pull request merged**
