### PR TITLE
github "star" -> "stars"

### PR DESCRIPTION
**Pull request by nschloe**
Fixes issue #1003.

### CODE REVIEW

**Comment by espadrine** [comment]
Thanks for submitting a PR!

A bit of background story. The `Star` (singular) is on purpose: the SVG actually supports clicking. However, browsers have a number of security measures to ensure that images stay images, even SVG images! So they prevent any interaction, like clicking.

So `` is forever bound to be static, but `<object data=my.svg type=image/svg+xml></object>` works like a champ!

<a href="https://thefiletree.com/gh-badges/button.html?plug=none">See for yourself</a> on the actual page I played around with when I first designed the social badges!

I wanted to update the website in that way, but I had no time. Are you up to the challenge?

**Comment by nschloe** [comment]
Note that this is merely a change of labels. As far as I can tell, this does not interfere with whatever technicality of the badge.

**Comment by paulmelnikow** [comment]
I think what @nschloe is saying is that the action doesn't match the label. In the case of **Fork**, clicking begins a fork action. In the case of **Star**, clicking takes you to the project. To my knowledge, Github does not provide a way to initiate a star action. Their own Star button takes you directly to the project.

Given the button takes no action (except navigation), **Stars** is a bit clearer.

There are several upvotes on #1003 including @Daniel15 so I'll merge this change.

**Comment by espadrine** [comment]
@paulmelnikow The behavior is identical to GitHub's own reference buttons https://ghbtns.com/ which are as official as you'll get, since mdo is employed by GitHub.

I would prefer to have verbs used for social badges, as it is the de-facto standard in the industry. Showcasing those badges with a noun encourages to go against what Twitter, Facebook, etc. do.

**Comment by espadrine** [comment]
Also, I mean it when I said that it would be welcome to use `<object>` to have those links work on the front page.

**Comment by paulmelnikow** [comment]
> I would prefer to have verbs used for social badges, as it is the de-facto standard in the industry. Showcasing those badges with a noun encourages to go against what Twitter, Facebook, etc. do.

I agree with that principle.

Whereas the Fork button does a good job of taking you into a workflow with intent to fork, the other two do not. In that sense I agree with @nschloe.

Though, I hear what you're saying about de-facto standard in the industry. Feel free to revert this if you'd like.

Apologies for merging this prematurely. I think I misunderstood that your suggestion, which if I'm understanding now, is about the shields.io index page, not the inline links.

**Comment by espadrine** [comment]
> Apologies for merging this prematurely.

No need to apologize, you did great.

It might have warranted a Twitter poll on the @shields_io account to be sure, but I felt that now that it was in master, I might as well put it live, and see whether there was a bigger backlash than there was to push for this change. Admittedly, it has not been long, but currently nobody was offended by this change, while there were four thumbs up on #1003.

As for the argument being about the index page or the inline links, I wrongly felt like it was somewhat related.
Indeed, the original argument presented in #1003 relates to copying the inline link in a website.
But merely copying the image link does not include the target link, unless the image link is in an `<object>`.
I felt like if the pop-up dialog in the shields.io index page gave a Markdown or HTML snippet which inlined an `<object>`, people wouldn't have to realize that they need to put the image inside a link.

But upon closer reading of the issue, that wasn't actually the problem:

> while it really is a link to the Github repo

If I understand correctly, people copy the image link, put it in a GitHub readme inside a link to the GitHub project itself (which is already the current page), and so viewers assume that this image which looks like a button acts like a button, but they are redirected to the current page.

In that case, we are stuck: we cannot add an `<object>` or an `<iframe>` in a GitHub readme to perform the `POST …/user/repo/star` to do what viewers of the readme expect the button to do.

In which case, I can only note that this patch could have been shorter, by simply removing the `?label` parameter, as the plural form (`[ Stars | 142 ]`) is the default.

**Pull request merged**
