### PR TITLE
Allowing GitHub API URL override

### PR DESCRIPTION
**Pull request by pyro2927**
Useful for GitHub Enterprise installations.  Docker containers for enterprise can be easily built then by adding:
```Dockerfile
ENV GITHUB_URL "https://github.enterprisedomain.com/api/v3"
```
and then deployed inside of the firewall

### CODE REVIEW

**Comment by eranimo** [comment]
Can we get this as a query parameter to the badge URLs?

**Comment by pyro2927** [comment]
@eranimo: How were you thinking this would be done? URL encoded as a param, or safe to assume the `/api/v3 part?

**Comment by eranimo** [comment]
I'm not sure how different enterprise Github setups are. I think to be safe, all parts should be customizable.

**Comment by pyro2927** [comment]
Now that I think about this more, I don't see the use case.  Most (if not all) GH Enterprise deployments are done behind a firewall, which means a public facing Shields.IO server wouldn't be able to access them.  In order to actually use this it has to be deployed within the firewall anyways, at which point it seems easier to set the URL once as an `ENV` and route all requests appropriately.

If someone else wants to support it on a per-requests basis for some reason they can, but I'm not going to do the work for a useless feature.

**Comment by drdamour** [comment]
it's not _completely_ useless:
some orgs have multiple githubs is a reason it may be needed (extremely rare, obv)
another use case is the user who does no want to use public shields and private shields based on source...but that's just a pref thing to eliminate complexity

**Comment by pyro2927** [comment]
> it's not completely useless

That's legitimate.  If someone else wants to do the work to support that, more power to them.  We've gone the route of using https://shields.io for public badges, and our internal Docker container for Jenkins/GH/etc inside of the firewall.

**Comment by teppeis** [comment]
any updates?

I've created https://github.com/teppeis/shields/tree/github-enterprise on latest master.
I can send PR if you need.

**Comment by espadrine** [comment]
Query parameters in Shields.io are meant to be global, because of their interaction with the cache system (having global badges would increase complexity of a few key components).

The patch is fine as it is. Having corporate shields.io instances running behind a firewall is a supported use-case. Thanks!

**Comment by espadrine** [comment]
It is live.

**Pull request merged**
