### PR TITLE
[WIP] Badge: CircleCI test summary

### PR DESCRIPTION
**Pull request by jankeromnes**
Fixing #2642 by pair programming with @paulmelnikow.

### CODE REVIEW

**Comment by paulmelnikow** [comment]
This pull request **introduces 1 alert** when merging 14884a11fb1106ce4ad206011d80cb68a6417d91 into 5b122ddd73ff34748fed4f6954fd1e41fe168606 - [view on LGTM.com](https://lgtm.com/projects/g/badges/shields/rev/pr-1bcd1d5058681bf7fccfe577795f561348c22952)

**new alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by calebcartwright** [comment]
How'd the pair programming experience go?

**Comment by paulmelnikow** [comment]
This pull request **introduces 1 alert** when merging b100fa7c0e83d757e2f7731c7d5a378d6d9234c3 into 5af5c480db5b3473254c18753ca8b0ebc086430d - [view on LGTM.com](https://lgtm.com/projects/g/badges/shields/rev/pr-8eb8d21bc753a9bc29adf7de84a6a3dd68533671)

**new alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by jankeromnes** [comment]
> How'd the pair programming experience go?

It was a cool experience. I found a few things that could be improved in Gitpod (for example the live collaboration URL didn't work for Paul) but overall it seemed to do the job well! Also we found that repurposing the older CircleCI badge to implement the new one made us jump all over the codebase, fetching or refactoring things, replacing old stuff with newer code, so we thought that it might be nice to have one or two "reference badge implementations", with all the latest best practices, and extra comments to explain everything to newcomers. This new badge could be the first one.

We're following up next Monday. :)

**Comment by paulmelnikow** [comment]
Hi Jan, since it looks like it's going to take a bit of time to get back to this, let's reopen when it's ready :)

**Pull request closed without merging**
