### PR TITLE
Fix spacing issues, Badge to spec

### PR DESCRIPTION
**Pull request by RedSparr0w**
Update of #1132:
Fixes spacing issues,
Also think i may have made the badge fit the spec now:
image
Currently the left label is placed in the middle (5px either side) as `x` position is calculated as `width/2` instead of `(width/2)+1` to give 6 px on the left and 4px on the right.

on the `textLength` I originally didn't account for the total padding of 10px i for some reason thought it was 4px each side.

Heres some test:

## Windows 10 - Chrome 61

This PR | Production
:---: | :---:
image | image
image | image
image | image
image | image
image | image
image | image
image | image

## Windows 10 - Firefox 56
This PR | Production
:---: | :---:
image | image
image | image

**Notes:**
* the Codetally badge shows up weird because for some reason it has an [extra space at the beginning](https://github.com/badges/shields/blob/master/server.js#L1114), should probably strip all outer spaces at some point in another PR
* the gem badge (rank) also has extra width due to when the width is calculated it counts the `ᵗʰ` as being a standard `th`
* no idea whats up with the `social` badge, not sure what the spec is supposed to be with those.

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Thanks for picking this up. 😃 

master (37bcddb2):

screen shot 2017-10-11 at 7 37 39 pm

this PR (8c9699d):

screen shot 2017-10-11 at 7 37 21 pm

Indeed, these are a bit different, though you're right that they better match the spec!

Will leave this open a bit in case anyone else would like to comment. Meanwhile would you mind merging master into this branch and resolving the conflicts, so I can merge through the UI?

**Comment by RedSparr0w** [comment]
Made a quick test page,
Will add some more badges to it soon,
https://shields.redsparr0w.com/1161/

Also just realised `?style=plastic` does not support logos,
`https://img.shields.io/github/issues/detail/s/badges/shields/979.svg?style=plastic&logo=github`

**Comment by paulmelnikow** [comment]
Thanks. This also resolves #671 then!

Do you think you could articulate some of the invariants in the badge design so we could express them in code? e.g. width of the left side === the left text width + x, first y pixels are gray followed by a white pixel, the height is z, etc. I'd love to get some more tests written. There's no reason to hold up this on more tests. Though perhaps it would be easier to identify the invariants while they're fresh in your mind.

Also… I'm finding the long math expressions in the templates pretty opaque. I might ask for your help sometime to move some of the logic from the template into the code.

**Comment by RedSparr0w** [comment]
>Do you think you could articulate some of the invariants in the badge design so we could express them in code? e.g. width of the left side === the left text width + x, first y pixels are gray followed by a white pixel, the height is z, etc. I'd love to get some more tests written. There's no reason to hold up this on more tests. Though perhaps it would be easier to identify the invariants while they're fresh in your mind.

Not quite sure what you mean sorry 😆

>Also… I'm finding the long math expressions in the templates pretty opaque. I might ask for your help sometime to move some of the logic from the template into the code.

Yeah most of the template values could be calculated before,
But some of them are probably best left in the template in case more templates are added later that follow a different layout?
The main one i can see that would work is the `textLength` as that is what the [badges width is calculated from](https://github.com/badges/shields/blob/master/lib/badge.js#L118-L119) originally anyway,

Another thing i've just noticed [badge width is rounded up](https://github.com/badges/shields/blob/master/lib/badge.js#L121-L122) to the nearest even number which would change the look if an odd number was calculated for text length:
`6px`Label`5px` `4px`Data`7px`

**Comment by paulmelnikow** [comment]
> But some of them are probably best left in the template in case more templates are added later that follow a different layout?

I think we could structure the data along these lines:

```js
{
   layout: {
      standard: {
         leftWidth: ...
      },
      social: {
         leftWidth: ...
      }
   }
   text: [...]
}
```

Alternatively the code could switch on the format, and provide only the data that template needs.

If we add another template we could add additional math logic along with it in the .js file. The more of this math logic is in code, the easier it should be to avoid duplicating it.

**Comment by RedSparr0w** [comment]
That would work,
Sounds like a good plan,
Would definitely make it easier to manage the look of the badges as well.

**Comment by paulmelnikow** [comment]
> Not quite sure what you mean sorry 😆

To clarify, I'm thinking something like this:
```js
describe('The badge spec', function () {
  it('The badge is the expected height', ...
  it('The left side of the badge has the expected amount of left and right padding', ...
  it('The right side of the badge has the expected amount of left and right padding', ...
});
```

No particular urgency, just something I'd much rather get into code than test manually!

**Comment by paulmelnikow** [comment]
This change got deployed over the weekend. Yay!

I noticed the spacing on this social badge looks off.



Do you know what might be causing it?

**Comment by RedSparr0w** [comment]
Yeah it does look a little strange

Before | After
:---: | :---:
image | image

The possible problem could be something with [this line](https://github.com/RedSparr0w/shields/blob/master/templates/social-template.svg?short_path=805092e#L2) `it.widths[1]-=4;` which is pushing the text closer together by 4px
Best guess is an old fix for some spacing issues?
If it's changed to be `-=2` or completely removed and shrink the `textLength` it doesn't look too bad.

image - (master) without `it.widths[1]-=4;` line
image - (master) without `it.widths[1]-=4;` & `textLength-10px` (right label 5px padding)
image - (master) changed to `it.widths[1]-=2;` (right label 4px padding)
image - current live badge
image - commit merged just before this PR was merged

**Comment by paulmelnikow** [comment]
Yea, it's like the left side got extended and the right side got compressed.

It seems to me that when the computed length is correct, `lengthAdjust="spacing"` should have no effect. How about seeing what kind of width adjustment looks the same, with or without that?

**Pull request merged**
