### PR TITLE
Migrated [JenkinsPlugin] to new service architecture

### PR DESCRIPTION
**Pull request by PyvesB**
See #2863.

### CODE REVIEW

**Comment by calebcartwright** [comment]
Wow you turned that around fast!

**Comment by paulmelnikow** [comment]
> The only question I have is around `regularUpdate` since the file containing it currently resides within the `legacy` directory hierarchy. If that helper will continue to be leveraged in the new service architecture, should that file (eventually) be moved to a different directory?

I think regular-update needs a total rewrite using async/await. Caching code is notoriously difficult to test and so I'd rather base the cache part on `node-cache`.

If this is the last legacy service to use it, the time to rewrite may be upon us!

https://github.com/badges/shields/pull/3101#issuecomment-468089472

**Comment by PyvesB** [comment]
Yes, I believe this is the last legacy service that is using `regularUpdate`.

**Comment by calebcartwright** [comment]
> I think regular-update needs a total rewrite using async/await. Caching code is notoriously difficult to test and so I'd rather base the cache part on node-cache

Do we want to do that here as part of refactoring this service? Or should we go ahead and merge this and then in a follow on tackle rewriting regular-update (and updating this service accordingly)?

**Comment by paulmelnikow** [comment]
Think that can definitely be a follow-on.

**Pull request merged**
