### PR TITLE
Fix edge case for service detection in PR titles [cran] [crates]

### PR DESCRIPTION
**Pull request by paulmelnikow**
Service detection didn’t work correctly for PR titles with multiple bracketed entries.

e.g. https://circleci.com/gh/badges/shields/6797

### CODE REVIEW

**Comment by chris48s** [comment]
Slightly difficult to tell if this has worked as expected because the Circle build says "This is not a pull request. Skipping." on the service tests. What would be the expected behaviour with the title "Fix edge case for service detection in PR titles [cran] [crates]" - should it run the tests for cran and crates, or only crates?

**Comment by paulmelnikow** [comment]
Huh, okay. Well, if you look at this slightly earlier build, you can see it "working", except that one of the services I picked the first time has no tests: https://circleci.com/gh/badges/shields/6836

The expected behavior is that both sets of tests run.

The observed behavior is completely broken. The regex greedily grabs the entire string between the outermost brackets. On #1743 it would attempt to test a service called `rfc], add, joi-based, request, validation, to, basejsonservice, and, rewrite, [npm`.

You can see it here: https://circleci.com/gh/badges/shields/6797

**Comment by chris48s** [comment]
Cool. That sounds sensible. Can we formalise that with a test for that case in `services-for-title.spec.js` as well then, so we're testing something like:

```js
given('make changes to [CRAN] and [CPAN]').expect([
  'cran',
  'cpan',
]);
```

**Comment by paulmelnikow** [comment]
Sure, I can add one more test.

**Comment by paulmelnikow** [comment]
Added! I was thinking this case was already covered by the test I had, though that's with the implementation in mind. From the outside it's a different case.

**Pull request merged**
