### PR TITLE
Refactoring some classes to static property, run [mavencentral mavenmetadata microbadger mozillaobservatory myget netlify nexus node npm nodeping]

### PR DESCRIPTION
**Pull request by jabbar86**

### CODE REVIEW

**Comment by calebcartwright** [comment]
hi @jabbar86 thank you for the PR. Could you please rebase your branch on the latest from the Shields master branch? The batch of already-merged commits from other PRs confused me initially as to which services were refactored here

**Comment by calebcartwright** [comment]
Please also stick to the guidance and request detailed in #5555. The individual changes are simple enough, but the diffs really start to add up especially with service classes that have more examples. Larger PRs are more difficult and time consuming to review, which is why it's easier to review  2 (or 3) smaller PRs vs. 1 giant one

**Comment by jabbar86** [comment]
@calebcartwright can you check why the test case is failing in my local env its working fine when in run `npm run test`

**Comment by calebcartwright** [comment]
Thank you for trying to get the branches synchronized but there's way too much going on in this PR right now @jabbar86, and it's not merge-able in its current form even if the tests were passing. Would you mind splitting this into at least two separate PRs that are clean/based on the latest, and avoid the package.json and lockfile changes? Let us know if you have any questions

**Comment by jabbar86** [comment]
> 
> 
> Thank you for trying to get the branches synchronized but there's way too much going on in this PR right now @jabbar86, and it's not merge-able in its current form even if the tests were passing. Would you mind splitting this into at least two separate PRs that are clean/based on the latest, and avoid the package.json and lockfile changes? Let us know if you have any questions

**Pull request closed without merging**
