### PR TITLE
Add [github] status API

### LINKED ISSUE #755: Badge request: GitHub status API
https://developer.github.com/v3/repos/statuses
would be useful to support it, as it allows for CI-agnostic build shields.

### PR DESCRIPTION
**Pull request by jamesjwood**
Closes #755

/github/status/:user/:repository/["status" OR status context][OPTIONAL .description].format

Examples:

[GitHub]()
http://shields.io/github/status/badges/shields/status.svg (for the overall status of the repository)

[GitHub]()
http://jamesjwood-shields.herokuapp.com/github/status/badges/shields/continuous-integration/travis-ci/push.svg?label=Travis (for the status of the 'continuous-integration/travis-ci/push' context)

[GitHub]()
http://jamesjwood-shields.herokuapp.com/github/status/badges/shields/continuous-integration/travis-ci/push.description.svg?label=Travis (for the status of the 'continuous-integration/travis-ci/push' context using the description on the status)

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Great!  I was just about to open an issue for this, but now I don't have to. :smile:

**Comment by olivierlacan** [comment]
This is really neat. Curious what @espadrine thinks.

**Comment by paulmelnikow** [comment]
Hi, thanks for this contribution. I'd like to get this merged, perhaps with a few tweaks.

Would you be willing to add tests using the project's [new testing framework](https://github.com/badges/shields/tree/master/service-tests)?

**Comment by paulmelnikow** [comment]
If anyone would like to adopt this PR, please feel free to do so: grab the branch, add more commits addressing the comments, and open a new PR referencing this one. Will close in one month if no one has.

**Comment by paulmelnikow** [comment]
Closing for inactivity. If you're reading this and want this implemented, don't be discouraged. You can grab the commits from the pull request branch using `git fetch origin pull/774/head:pr-774`, address the comments, and reopen.

**Pull request closed without merging**
