### PR TITLE
Make Dropdown Visible When Overflows

### PR DESCRIPTION
**Pull request by mackmmiller**
This PR addresses the dropdown visibility issue described in https://github.com/badges/shields/issues/2806. 

Screen Shot 2019-05-29 at 9 53 47 PM

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Hi! Thanks for picking this up!

Have you been able to reproduce the problem (i.e. before the fix)?

When I try it now I'm seeing the popup is not obscured as in the screenshot in #2806, but rather that it opens in the opposite direction. 

Screen Shot 2019-05-29 at 11 09 32 PM

I wonder if a subsequent release of react-select fixed it?

**Comment by mackmmiller** [comment]
@paulmelnikow, I have been able to reproduce the problem!

The following image is a screenshot from the current live site:
Screen Shot 2019-05-30 at 7 22 09 PM

And this is an image of the site, at the same size, with the changes:
Screen Shot 2019-05-30 at 7 24 20 PM

The behavior you've described seems to be controlled by the `menuPlacement` prop on the [`<MarkupFormatSelect/>`](https://github.com/badges/shields/blob/98f380b2549fdd3c765cdf96ad453584c606c4f8/frontend/components/customizer/request-markup-button.js#L104) component. According to the [documentation](https://react-select.com/props), it should move the dropdown above the button when there isn't enough room, though clearly that is only working some of the time.

**Comment by paulmelnikow** [comment]
Ah, gotcha. Thanks for digging into that!

**Comment by calebcartwright** [comment]
Nice!

**Comment by paulmelnikow** [comment]
P.S. Thanks for jumping in @mackmmiller! We've got lots of things we'd like to do with the frontend and would welcome your help!

**Comment by paulmelnikow** [comment]
Hey @mackmmiller, just a heads up that we had to revert this (see #3513).

I'm guessing to deal with this specific issue we'd need to find out why the `menuPlacement` is sometimes not working as intended and fix it upstream. Feel free to dig further if you'd like… or to find something else to tackle!

**Pull request merged**
