### PR TITLE
Allow nulls for boolean fields on Libraries.io APIs

### PR DESCRIPTION
**Pull request by corebreaker**
Fix the issue #3529

### CODE REVIEW

**Comment by calebcartwright** [comment]
Hi @corebreaker, thanks for reporting and opening a PR with a fix! I updated the PR title so that the tests associated with the Libraries.io service would be run, and as you can see the changes added here are causing the tests to fail. 

Can you take a look and update/fix the tests accordingly?

**Comment by calebcartwright** [comment]
Actually looks like it was just a timeout. I'll re-start the tests and see if they pass this time

**Comment by calebcartwright** [comment]
timeout errors are spurious, tests pass locally (with increased timeout) so going to disable the service test runs accordingly

**Comment by corebreaker** [comment]
Hi @calebcartwright . Good news ! Thank you for the merge :+1: .

**Pull request merged**
