### PR TITLE
MarkupModal: Convert from class component to functional component

### PR DESCRIPTION
**Pull request by paulmelnikow**
This continues the work from #3177, of converting our class components to function components.

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Spotted a (first) transient failure in the e2e tests: https://circleci.com/gh/badges/shields/52855.

**Comment by platan** [comment]
@paulmelnikow thanks for reporting the problem with e2e tests! We have a screenshot and a video https://circleci.com/gh/badges/shields/52855#artifacts/containers/0. But the video is broken and the screenshot shows that there is no "Suggest badges" button. I will try to measure stability of these tests. 
Please report any problems with e2e tests, this will help to know the scale of the problem.

**Comment by paulmelnikow** [comment]
Will do! Since this failure I saw a second transient failure in CI.

If you want to open a new issue I can post a link there every time I see it pop up.

**Comment by platan** [comment]
@paulmelnikow you can post a link here: https://github.com/badges/shields/issues/3430

**Pull request merged**
