### PR TITLE
 Bump nock from 11.0.0.beta-14 to 11.0.0.beta-20

### PR DESCRIPTION
**Pull request by paulmelnikow**
Hoping the changes from #3615 will fix the issues that appeared at https://github.com/badges/shields/pull/3552#issuecomment-504610847

Diff should clean up after #3615.

### CODE REVIEW

**Comment by calebcartwright** [comment]
🤞

**Comment by paulmelnikow** [comment]
How did the problem manifest last time? Was it weird errors on service-test failures or was it false failures? It seemed to me such a mixed set of conditions.

**Comment by calebcartwright** [comment]
Last time the nock update was causing north of 100 service tests to fail. There was a couple of the usual timeout types, but the bulk seemed related. I forget the specifics of the errors, trying to find them now

**Comment by calebcartwright** [comment]
https://circleci.com/gh/badges/shields/58187?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by calebcartwright** [comment]
> 600 test failures in the services job: https://circleci.com/gh/badges/shields/58498?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

The services@node latest job has ~150 test failures which looks similar to what we were seeing before
https://circleci.com/gh/badges/shields/58497?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by paulmelnikow** [comment]
Two observations:

1. At least two of the failures are due to what I think what ought to be called breaking changes in the nock API for `.reply()`. These changes were made in nock/nock#1520 and clarified the ambiguity in the way `.reply()` is invoked. It's clear however that they are likely to cause downstream failures, because old tests might invoke these methods using the old signatures which used to work, despite how confusing the old signatures were.
2. Icedfrisby does not seem to be correctly cleaning up after failures. Once one test fails (in a certain way) the subsequent tests seem to show "Error: Nock: No match for request", even when those tests aren't using mocks. It's possible this is an underlying bug in nock, though it seems a bit more likely it's happening in icedfrisby.

**Comment by paulmelnikow** [comment]
These last test runs look good and I don't think item 2 above is blocking.

**Comment by calebcartwright** [comment]
> These last test runs look good and I don't think item 2 above is blocking.

Agreed. Thanks for digging into this one!

**Pull request merged**
