### PR TITLE
add wordpress.org active installs shield

### PR DESCRIPTION
**Pull request by koter84**
i have made a badge for wordpress-active-installs.
this is a number which is rounded-down and then a + is added at the end to show that at least a number of sites are actively using this plugin.

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Reopen of #680. Also related: #662.

**Comment by paulmelnikow** [comment]
Hi, thanks for this!

Would you be willing to add tests? We have a new framework: https://github.com/badges/shields/tree/master/service-tests

Also, `index.html` has been removed in master. When you merge master you can remove it.

**Comment by jhabdas** [comment]
I want it. @koter84 Please let me know if I can help.

**Comment by paulmelnikow** [comment]
@jhabdas, or anyone else, if you would like to adopt this PR, please feel free to do so. Just grab the branch, add more commits addressing the comments, and open a new PR referencing this one. Will close in one month if no one has done so.

@koter84 if you have time, of course feel free to address the comments! Would love to get this merged.

**Comment by jhabdas** [comment]
@paulmelnikow happy to drive this home. looks like we just need a few unit tests against the service framework using tape? should I just model discord?

**Comment by paulmelnikow** [comment]
@jhabdas Yup, looks like tests are the main thing. Discord would be a good one to model after, or CRAN in the service test readme.

**Comment by jhabdas** [comment]
Okay. Cloned repo down and rebased pull. Look like I'll just need a couple of services. One to check active installs and then a couple of boilerplate negative tests. Am I on the right track?

**Comment by paulmelnikow** [comment]
Yes, that should do it!

**Comment by jhabdas** [comment]
@paulmelnikow thanks for the pointer. I sent a message to the community channel on wordpress's slack server asking about an endpoint to get the active install count. if I don't hear back feel free to poke and I'll do some more digging

**Comment by tobifjellner** [comment]
I saw your note in Slack group community-team. You might consider posting your question in another channel: meta.
I think I've seen that there is an api. But it will give you rounded numbers, not the raw data.

**Comment by paulmelnikow** [comment]
I'm assigning this to @jhabdas just to signal to myself and others that someone is working on this.

**Comment by jhabdas** [comment]
@tobifjellner thanks for the pointer! whatever matches what wordpress shows should be good. even npm doesn't provide raw numbers. I'll ask in meta to find out how to tap into that api.

**Comment by paulmelnikow** [comment]
@jhabdas any update?

**Comment by jhabdas** [comment]
@paulmelnikow I'm sorry—I'm swamped right now with cryptocurrency stuff. I've opened [an issue](https://github.com/comfusion/hyperdrive/issues/91) against my WordPress plug-in to remember and come back to this later.

**Comment by paulmelnikow** [comment]
It's no problem at all! We're all volunteering our time.

If anyone else would like to tackle this in the meantime, feel free to do so. Just grab the branch, add more commits addressing the comments, and open a new PR referencing this one.

**Comment by paulmelnikow** [comment]
Closing for inactivity. If you're reading this and want this implemented, don't be discouraged. You can grab the commits from the pull request branch using `git fetch origin pull/890/head:pr-890`, address the comments, and reopen.

**Pull request closed without merging**
