### PR TITLE
fix(gratipay): distinguish between anonymous and 0 dollar projects

### LINKED ISSUE #1005: Gratipay badge shows "anonymous" if no one is donating
If a project on Gratipay is not receiving any money, the badge will incorrectly list their total as anonymous.

For example, ``https://img.shields.io/gratipay/Distilled.svg`` shows up as: 
gratipay-anonymous

### PR DESCRIPTION
**Pull request by danShumway**
Fixes #1005, adds service tests to Gratipay

Previous merge request (#1006) was off of the maintenance branch.

### CODE REVIEW

**Comment by danShumway** [comment]
Locally I'm seeing test failures for Github, possibly related to the lack of a secrets file. I'm assuming that this won't happen on the official build.

**Comment by whit537** [comment]
Thanks for working on this, @danShumway. Let us (Gratipay) know if there are any API changes needed on our side. Repo for that is https://github.com/gratipay/grtp.co.

**Comment by whit537** [comment]
screen shot 2017-06-09 at 1 34 06 pm

So cool! 😄 💃

**Comment by danShumway** [comment]
Thanks, I feel comfortable with the changes here, doesn't look like Gratipay needs to do anything on their end. Relatively small bug.

**Comment by Daniel15** [comment]
I think it's a good idea to add a test that uses mock data to test that the original issue is indeed fixed 😃

**Comment by danShumway** [comment]
Good idea, should have dug around the original codebase more - I didn't realize ServiceTester allowed intercepting requests.

**Comment by Daniel15** [comment]
Thanks for your contribution!

**Pull request merged**
