### PR TITLE
Improved [MicroBadger] tests speed

### PR DESCRIPTION
**Pull request by PyvesB**
Addresses #2489. Selected images that are less "heavy" and seemed to give faster response times from the API. I also aligned the example `previewUrls` to match what was used in the test.

### CODE REVIEW

**Comment by paulmelnikow** [comment]
It's not essential, though it'd be great if you could update the `previewUrl`s to `namedParams` to help with #2496.

**Comment by PyvesB** [comment]
No tests have timed out this time round and they execute much faster with the new images, below one second.

**Comment by PyvesB** [comment]
@paulmelnikow can these examples really be converted at this point? As the tag is optional, wouldn't we be affected by #2497?

**Comment by paulmelnikow** [comment]
In examples I haven't been using optionals, so #2497 doesn't apply. Instead there's usually a different pattern for each example, one with and without the optional part. That way each example renders the way you'd expect:

screen shot 2018-12-11 at 5 08 48 pm

**Pull request merged**
