### PR TITLE
Add Azure DevOps tests service [AzureDevOpsTests AzureDevOpsCoverage]

### PR DESCRIPTION
**Pull request by mehmetseckin**
Added a test results badge service for an Azure Pipelines
build using the ResultSummaryByBuild endpoint. Added
basic unit tests for the service.

Implements the badge described in #2411

### CODE REVIEW

**Comment by paulmelnikow** [comment]
This pull request **introduces 2 alerts** when merging 33579dace304d949c87d9d45779aef3a45aa03d4 into a524658e74791a4fe98e4f058a3bb11ec2fa837f - [view on LGTM.com](https://lgtm.com/projects/g/badges/shields/rev/pr-1401c397e2a0a005b8ec0b2038f60ec14897e1aa)

**new alerts:**

* 2 for Inefficient regular expression

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by calebcartwright** [comment]
Just a thought, but should we extract the `getLatestBuildId` function (perhaps into the `helpers` file) so that we don't have duplicate definitions in both the coverage and tests classes?

**Comment by mehmetseckin** [comment]
@calebcartwright - That's a really good shout, I wanted to do that initially, but I thought it's best to keep changes to minimum and keep this PR simple. 

I can happily update this PR and add the refactoring changes, or we can simply create a new refactoring PR after this is merged.

**Comment by paulmelnikow** [comment]
Confusingly, half these tests started failing seemingly moments after this was merged. This is failing on the merge commit as well as current master, so it's not related to subsequent changes.

Would you be up for looking into it?

```
  AzureDevOpsTests
    unknown build definition
      ✓
	[ GET /azuredevops-powershell/azuredevops-powershell/9999.json ] (297ms)
    404 latest build error response
      ✓
	[ GET /azuredevops-powershell/azuredevops-powershell/1.json ] (97ms)
    no build response
      ✓
	[ GET /azuredevops-powershell/azuredevops-powershell/9999.json ]
    no test result summary response
      ✓
	[ GET /azuredevops-powershell/azuredevops-powershell/1.json ]
    invalid test result summary response
      ✓
	[ GET /azuredevops-powershell/azuredevops-powershell/1.json ]
    no tests in test result summary response
      ✓
	[ GET /azuredevops-powershell/azuredevops-powershell/1.json ]
    test status
GET /azuredevops-powershell/azuredevops-powershell/1.json has FAILED with the following response:
      1)
	[ GET /azuredevops-powershell/azuredevops-powershell/1.json ]
    test status on branch
GET /azuredevops-powershell/azuredevops-powershell/1/master.json has FAILED with the following response:
      2)
	[ GET /azuredevops-powershell/azuredevops-powershell/1/master.json ]
    test status with compact message
GET /azuredevops-powershell/azuredevops-powershell/1.json has FAILED with the following response:
      3)
	[ GET /azuredevops-powershell/azuredevops-powershell/1.json ]
    test status with custom labels
GET /azuredevops-powershell/azuredevops-powershell/1.json has FAILED with the following response:
      4)
	[ GET /azuredevops-powershell/azuredevops-powershell/1.json ]
    test status with compact message and custom labels
GET /azuredevops-powershell/azuredevops-powershell/1.json has FAILED with the following response:
      5)
	[ GET /azuredevops-powershell/azuredevops-powershell/1.json ]
```

**Comment by calebcartwright** [comment]
Adding my two cents here again :) 

it looks like those tests that are failing are live/non-mocked tests that are querying [this](https://dev.azure.com/azuredevops-powershell/azuredevops-powershell/_build?definitionId=1&_a=summary) build pipeline and it looks like the [latest job](https://dev.azure.com/azuredevops-powershell/azuredevops-powershell/_build/results?buildId=32) that ran for that pipeline earlier today (0.1.30) is now failing on the build/test step which means there are no test results available. 

I believe those tests could be fixed either by resolving the build/test issues that exist in that pipeline, and/or updating those unit tests to point to a different pipeline (perhaps a stable/not-in-use pipeline that may break from time to time) 

I'm going to double check the pipelines I used for the unit tests on the coverage service for the same

**Comment by paulmelnikow** [comment]
Aha! Good sleuthing. They're returning **no tests** which doesn't sound like the right message for this scenario. **error** or **build error** would be better.

Is it possible to detect this case?

**Comment by paulmelnikow** [comment]
Here are the responses in case they're helpful later:

<details>

```js
{ count: 1,
  value:
   [ { _links:
        { self:
           { href:
              'https://dev.azure.com/azuredevops-powershell/4d81da9c-b02f-4f9a-8775-c8444d950246/_apis/build/Builds/32' },
          web:
           { href:
              'https://dev.azure.com/azuredevops-powershell/4d81da9c-b02f-4f9a-8775-c8444d950246/_build/results?buildId=32' },
          sourceVersionDisplayUri:
           { href:
              'https://dev.azure.com/azuredevops-powershell/4d81da9c-b02f-4f9a-8775-c8444d950246/_apis/build/builds/32/sources' },
          timeline:
           { href:
              'https://dev.azure.com/azuredevops-powershell/4d81da9c-b02f-4f9a-8775-c8444d950246/_apis/build/builds/32/Timeline' },
          badge:
           { href:
              'https://dev.azure.com/azuredevops-powershell/4d81da9c-b02f-4f9a-8775-c8444d950246/_apis/build/status/1' } },
       properties: {},
       tags: [],
       validationResults: [],
       plans: [ { planId: '5b389dab-c9d6-493a-ab64-404c1fcf393d' } ],
       triggerInfo: {},
       id: 32,
       buildNumber: '0.1.30',
       status: 'completed',
       result: 'failed',
       queueTime: '2018-12-03T15:20:48.1796269Z',
       startTime: '2018-12-03T15:20:59.234572Z',
       finishTime: '2018-12-03T15:22:03.4763836Z',
       url:
        'https://dev.azure.com/azuredevops-powershell/4d81da9c-b02f-4f9a-8775-c8444d950246/_apis/build/Builds/32',
       definition:
        { drafts: [],
          id: 1,
          name: 'azuredevops-powershell-ci',
          url:
           'https://dev.azure.com/azuredevops-powershell/4d81da9c-b02f-4f9a-8775-c8444d950246/_apis/build/Definitions/1?revision=3',
          uri: 'vstfs:///Build/Definition/1',
          path: '\\',
          type: 'build',
          queueStatus: 'enabled',
          revision: 3,
          project:
           { id: '4d81da9c-b02f-4f9a-8775-c8444d950246',
             name: 'azuredevops-powershell',
             description:
              'This is a very simple (and primitive) PowerShell module to interact with the Azure DevOps REST API.\n\nhttps://github.com/mehmetseckin/azuredevops-powershell',
             url:
              'https://dev.azure.com/azuredevops-powershell/_apis/projects/4d81da9c-b02f-4f9a-8775-c8444d950246',
             state: 'wellFormed',
             revision: 15,
             visibility: 'public' } },
       buildNumberRevision: 30,
       project:
        { id: '4d81da9c-b02f-4f9a-8775-c8444d950246',
          name: 'azuredevops-powershell',
          description:
           'This is a very simple (and primitive) PowerShell module to interact with the Azure DevOps REST API.\n\nhttps://github.com/mehmetseckin/azuredevops-powershell',
          url:
           'https://dev.azure.com/azuredevops-powershell/_apis/projects/4d81da9c-b02f-4f9a-8775-c8444d950246',
          state: 'wellFormed',
          revision: 15,
          visibility: 'public' },
       uri: 'vstfs:///Build/Build/32',
       sourceBranch: 'refs/heads/master',
       sourceVersion: '016287ec39a9e4b0ae5ceb6776941e394e14ce4f',
       priority: 'normal',
       reason: 'individualCI',
       requestedFor:
        { displayName: 'GitHub',
          url:
           'https://app.vssps.visualstudio.com/A1b89fde7-4d96-49b6-9337-1ef58fdbb813/_apis/Identities/db890558-d5de-4037-b700-d0e7078cc68a',
          _links:
           { avatar:
              { href:
                 'https://dev.azure.com/azuredevops-powershell/_apis/GraphProfile/MemberAvatars/svc.MWI4OWZkZTctNGQ5Ni00OWI2LTkzMzctMWVmNThmZGJiODEzOkdpdEh1YiBBcHA6NGQ4MWRhOWMtYjAyZi00ZjlhLTg3NzUtYzg0NDRkOTUwMjQ2' } },
          id: 'db890558-d5de-4037-b700-d0e7078cc68a',
          uniqueName: null,
          imageUrl: null,
          descriptor:
           'svc.MWI4OWZkZTctNGQ5Ni00OWI2LTkzMzctMWVmNThmZGJiODEzOkdpdEh1YiBBcHA6NGQ4MWRhOWMtYjAyZi00ZjlhLTg3NzUtYzg0NDRkOTUwMjQ2' },
       requestedBy:
        { displayName: 'GitHub',
          url:
           'https://app.vssps.visualstudio.com/A1b89fde7-4d96-49b6-9337-1ef58fdbb813/_apis/Identities/db890558-d5de-4037-b700-d0e7078cc68a',
          _links:
           { avatar:
              { href:
                 'https://dev.azure.com/azuredevops-powershell/_apis/GraphProfile/MemberAvatars/svc.MWI4OWZkZTctNGQ5Ni00OWI2LTkzMzctMWVmNThmZGJiODEzOkdpdEh1YiBBcHA6NGQ4MWRhOWMtYjAyZi00ZjlhLTg3NzUtYzg0NDRkOTUwMjQ2' } },
          id: 'db890558-d5de-4037-b700-d0e7078cc68a',
          uniqueName: null,
          imageUrl: null,
          descriptor:
           'svc.MWI4OWZkZTctNGQ5Ni00OWI2LTkzMzctMWVmNThmZGJiODEzOkdpdEh1YiBBcHA6NGQ4MWRhOWMtYjAyZi00ZjlhLTg3NzUtYzg0NDRkOTUwMjQ2' },
       lastChangedDate: '2018-12-03T15:22:03.687Z',
       lastChangedBy:
        { displayName: 'Microsoft.VisualStudio.Services.TFS',
          url:
           'https://app.vssps.visualstudio.com/A1b89fde7-4d96-49b6-9337-1ef58fdbb813/_apis/Identities/00000002-0000-8888-8000-000000000000',
          _links:
           { avatar:
              { href:
                 'https://dev.azure.com/azuredevops-powershell/_apis/GraphProfile/MemberAvatars/s2s.MDAwMDAwMDItMDAwMC04ODg4LTgwMDAtMDAwMDAwMDAwMDAwQDJjODk1OTA4LTA0ZTAtNDk1Mi04OWZkLTU0YjAwNDZkNjI4OA' } },
          id: '00000002-0000-8888-8000-000000000000',
          uniqueName: null,
          imageUrl: null,
          descriptor:
           's2s.MDAwMDAwMDItMDAwMC04ODg4LTgwMDAtMDAwMDAwMDAwMDAwQDJjODk1OTA4LTA0ZTAtNDk1Mi04OWZkLTU0YjAwNDZkNjI4OA' },
       orchestrationPlan: { planId: '5b389dab-c9d6-493a-ab64-404c1fcf393d' },
       logs:
        { id: 0,
          type: 'Container',
          url:
           'https://dev.azure.com/azuredevops-powershell/4d81da9c-b02f-4f9a-8775-c8444d950246/_apis/build/builds/32/logs' },
       repository:
        { id: 'mehmetseckin/azuredevops-powershell',
          type: 'GitHub',
          clean: null,
          checkoutSubmodules: false },
       keepForever: false,
       retainedByRelease: false,
       triggeredByBuild: null } ] }
```

```js
{ aggregatedResultsAnalysis:
   { previousContext: { contextType: 0, build: null, release: null },
     resultsDifference:
      { increaseInTotalTests: 0,
        increaseInFailures: 0,
        increaseInPassedTests: 0,
        increaseInOtherTests: 0,
        increaseInDuration: '00:00:00' },
     totalTests: 0,
     duration: '00:00:00',
     resultsByOutcome: {},
     runSummaryByState: {},
     runSummaryByOutcome: {} },
  testResultsContext:
   { contextType: 'build',
     build: { id: 32, definitionId: 0, uri: 'vstfs:///Build/Build/32' },
     release: null },
  teamProject:
   { id: '4d81da9c-b02f-4f9a-8775-c8444d950246',
     name: 'azuredevops-powershell',
     state: 'unchanged',
     visibility: 'unchanged' } }
```

**Comment by mehmetseckin** [comment]
Wow, I didn't expect that to happen :smile: thanks for following up! 

I agree with @calebcartwright, `no tests` is the expected message in case of an empty response, and there is other unit tests to assert the message in that case.

In those failed tests, I intended to assert the message produced by the badge when there are some tests available. I think mocking the API calls here and providing a preset response would be a better approach, I think we shouldn't be testing the live API itself.

I'm happy to refactor these tests and add mock responses.

**Comment by paulmelnikow** [comment]
Thanks so much! Let's continue discussion at https://github.com/badges/shields/pull/2454#issuecomment-444175784.

**Pull request merged**
