### PR TITLE
Refactor service classes [snyk sonar sourceforge sourcegraph spack]

### PR DESCRIPTION
**Pull request by vanhaaggen**

### CODE REVIEW

**Review by jabbar86 — COMMENTED** [review]
Run the prettier before pushing any changes.

**Comment by calebcartwright** [comment]
Thank you for the PR @vanhaaggen! Could you run `npm run prettier` to correct the formatting/style issues, and then push the fix to get the CI checks passing?

**Comment by vanhaaggen** [comment]
@jabbar86 @calebcartwright  Sorry guys!! It will be first thing I do when I get home today.

**Comment by calebcartwright** [comment]
> After running prettier, why does git mark all files from the repo as modified? Has this something to do with the line endings?

@vanhaaggen - just to clarify, you've run prettier locally and now git's showing all files modified? Are you on windows by any chance?

**Comment by vanhaaggen** [comment]
@calebcartwright yes I run prettier locally, on Windows.

**Comment by calebcartwright** [comment]
What's the current autocrlf value set to?

**Comment by vanhaaggen** [comment]
It was set to `true`, now it's set to `false`.

**Review by calebcartwright — APPROVED** [review]
Thank you!

**Pull request merged**
