### PR TITLE
Typo3 ter

### PR DESCRIPTION
**Pull request by sHorst**
Hey,

i added support for Typo3 Extension Repository. Since there is no official api for doing this, i scraped the webpage using jQuery.

br

Stefan Horst

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Hi, thanks for this contribution.

It's a sweet implementation. Unfortunately I don't think we'll be able to include it. Downloading web pages, HTML parsing, and running jQuery are pretty expensive in terms of time, memory, and CPU. And what happens when they change their web page? It's extremely brittle.

Perhaps you could reach out to them and ask them to create a REST API. Or, see if you could contribute one!

**Comment by sHorst** [comment]
hey, i am in contact with them. And they are building an api. 

But for now, they only have the website. I use jquery, because it is faster and easier in javascript :) .. i wanted to do it with grep :)

I will change the code, if they have the api. but for now it would be great to have it working already.

**Comment by paulmelnikow** [comment]
Any progress on an API?

**Comment by paulmelnikow** [comment]
Going to close this for now. Feel free to open a new PR when they make an API. In the meantime, you could host your own shields server if you'd like.

**Pull request closed without merging**
