### PR TITLE
Run tests with Mocha

### LINKED ISSUE #911: Make tests more reliable
I've noticed a few problems with the tests. 

I have this test failing silently on my machine. 
```js
['should produce PNG badges', function(done, assert) {
  console.log(1);
  child = cproc.spawn('node',
    ['test/cli-test.js', 'cactus', 'grown', '.png']);
  child.stdout.on('data', function(chunk) {
    console.log(2);
    // Check the PNG magic number.
    assert.equal(chunk[0], 0x89);
    assert.equal(chunk[1], 0x50);
    assert.equal(chunk[2], 0x4e);
    assert.equal(chunk[3], 0x47);
    assert.equal(chunk[4], 0x0d);
    assert.equal(chunk[5], 0x0a);
    assert.equal(chunk[6], 0x1a);
    assert.equal(chunk[7], 0x0a);
    done();
  });
```

`1` prints but `2` doesn't, then the test suite finishes without an error or any other output.

Whether or not it prints a stack trace seems to depend on timing. Sometimes I get the stack trace, sometimes I don't.

Some of the CI builds appear to be generating uncaught exceptions, yet the CI build is passing.

Here is one example:

- https://travis-ci.org/badges/shields/builds/215764775

```sh
> gh-badges@1.3.0 test:js /home/travis/build/badges/shields
> node test/test.js
No secret data (private/secret.json, see server.js): { Error: Cannot find module './private/secret.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/travis/build/badges/shields/server.js:36:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
No secret data (private/secret.json, see server.js): { Error: Cannot find module '../private/secret.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/travis/build/badges/shields/lib/suggest.js:7:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
```

I think it started before that commit though. I'm trying to track it down but Travis is being slow.

**Added:**

Here's a build of an earlier commit with the same issue: https://travis-ci.org/badges/shields/builds/215308677

### PR DESCRIPTION
**Pull request by paulmelnikow**
This avoids silent failures observed CI and locally (resolves #911).

Mocha is lightweight, popular, and well documented. I renamed the files containing tests with `.spec.js`. This is a common convention which avoids hard-coding each test filename in package.json.

The eslintrc change is needed for #912.

### CODE REVIEW

**Comment by espadrine** [comment]
For some reason, the tests systematically fail on this branch (rebased on top of master), with the following error that I don't fully understand:

```
  1) The server "before all" hook: Start running the server:

      Uncaught AssertionError: 255 == 137
      + expected - actual

      -255
      +137
      
      at Socket.<anonymous> (test/test.spec.js:62:14)
      at readableAddChunk (_stream_readable.js:178:18)
      at Socket.Readable.push (_stream_readable.js:136:10)
      at Pipe.onread (net.js:559:20)
```

I am on v7.8.0. Do you not have something like that?

**Comment by paulmelnikow** [comment]
Hmmm, that is puzzling. From the line number, it appears to be a legitimate failure of a totally separate test, the `it` which starts on line 57. You can try to change `it` to `it.only` to run just that test, which would confirm my suspicion.

Is lint passing? There are a couple missing `var`'s in that file. Though I doubt that is the problem.

I'll resolve these conflicts and push, then we can debug apples to apples.

**Comment by paulmelnikow** [comment]
By the way, that's the failure I saw when `imagemagick` wasn't installed.

**Comment by espadrine** [comment]
Yes, I had fixed the vars as part of rebasing. Getting http://localhost:1111/badge/png-test-red.png yields the correct result. I have imagemagick installed.

Here's what happens if I log the chunk:

```
  The CLI
    ✓ should provide a help message (368ms)
    ✓ should produce default badges (373ms)
    ✓ should produce colorschemed badges (375ms)
    ✓ should produce right-color badges (373ms)
<Buffer 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 00 5a 00 00 00 14 08 03 00 00 00 3a 24 da 2c 00 00 00 04 67 41 4d 41 00 00 b1 8f 0b fc 61 05 00 ... >
    ✓ should produce PNG badges (676ms)

  The server
<Buffer ff fa d0 a4 da fc d1 92 55 3c 3c 3d 92 bf 0a df fc fe f1 d6 5c 66 86 07 f8 fe ff ff fd c9 aa db f1 ff ff fe 71 a9 9d ff ff fd e9 fe ff c3 c8 0c 92 c0 ... >
    1) "before all" hook: Start running the server
```

I'll try investigating it further tomorrow. Just to confirm, you don't have that issue with v7.8.0?

**Comment by paulmelnikow** [comment]
Confirmed. I tried it in 6.10.1 and 7.8.0.

Ah, I see you're logging two chunks. So the problem must be this: the first chunk comes in, the test passes. Then later, another chunk comes in, and it fails. It's the second chunk, so it doesn't start with the PNG magic numbers.

If that's right, changing `.on` to `.once` should fix it.

**Comment by espadrine** [comment]
Cool! Merged as 1930d9f.

**Pull request closed without merging**
