### PR TITLE
[VisualStudioMarketplace] Trending Badges

### PR DESCRIPTION
**Pull request by YashTotale**
Added Visual Studio Marketplace Trending Badges.

- Trending Daily Badge
- Trending Weekly Badge
- Trending Monthly Badge

### CODE REVIEW

**Comment by calebcartwright** [comment]
Thank you for the PR. Do you know if these `trending*` fields are based on the initial install measure, or if they also include updates? I imagine we're going to need to incorporate these as variants within our existing download/install badges vs. maintaining entirely separate classes and routes. 

https://github.com/badges/shields/blob/master/doc/badge-urls.md

**Comment by YashTotale** [comment]
I'm not sure what the trending fields are based or what they are out of...

**Comment by calebcartwright** [comment]
@YashTotale - In order to move forward with this, we're going to need at least two things:

* Determine whether these data points are associated with Downloads or Installs. We'll need this in order to be able to properly identify variants in the route param, since the API provides both of those numbers in total and we provided badges for both.
    * I suspect the easiest way to do this would be to look at the API response for a handful of packages. If any of the trending data points exceed the value for the install total, then we know the trends are for downloads
* This should not be implemented as a separate service with a non-compliant badge route. These additional variants need to be incorporated in the [existing service](https://github.com/badges/shields/blob/master/services/visual-studio-marketplace/visual-studio-marketplace-downloads.service.js), and will need to follow [our route conventions](https://github.com/badges/shields/blob/master/doc/badge-urls.md) as I mentioned earlier. This would likely end requiring adding a redirector to map the old `d` to `dt` (or `i` to `it` depending on which metric these map to)

**Comment by PyvesB** [comment]
Given that there hasn't been any activity for a while, I'm going to close this pull request. Feel free to reopen it if you get a chance to look into it again.

If someone else wants to pick this up, you can simply fetch the commits by running git fetch origin pull/5411/head:pr-5411. Address the pending review comments and open a new pull request with a co-authored trailer included in the commit message to give attribution to the original author.

**Pull request closed without merging**
