### PR TITLE
Support chrome web store

### PR DESCRIPTION
**Pull request by sanemat**
* Version, Downloads, Price, Rating and Rating Count
  for chrome app, chrome extension and chrome theme.
* Google does not provide a public API for chrome web store.
* Use `chrome-web-store-item-property`.
    * Gather meta information from chrome web store.

### CODE REVIEW

**Comment by sanemat** [comment]
I need your advice :)

## About scraping

Google does not provide a public API for chrome web store.
I heard that usually people scrape the detail page.
http://stackoverflow.com/questions/31830249/how-to-get-chrome-extensions-meta-information-e-g-version-name-from-chrome

## Name

### url

Which is better, `chrome-web-store` or `chromewebstore`?

### label

Which is better, `chrome-web-store`, `chrome web store` or `chromeWebStore`?

**Comment by espadrine** [comment]
Thanks for the contribution!

I'm uneasy about the brittleness of HTML scraping. Do you know for how long in the past this code has worked, for instance by using the wayback machine? If it always has (if the 2010 version could be scraped by your module), that worry goes away. Otherwise, I'd like you to contact Google and ask for a public API access first. Scraping is always the last option (especially here, considering it adds a large-ish dependency tree).

`chrome-web-store` is better in the URL, `chrome web store` in the label.

**Comment by sanemat** [comment]
Thank you for your response!

What you're saying is reasonable.
I asked a question about a public api on chromium-apps group.

`chrome-web-store-item-property` can parse the detail page for gmail on 2013-07-02, but this does not guarantee it can parse tomorrow.

```
https://web.archive.org/web/20130702005956/https://chrome.google.com/webstore/detail/gmail/pjkljhegncpnkpknbcohdijeoejaedia
{
    url: 'https://chrome.google.com/webstore/detail/gmail/pjkljhegncpnkpknbcohdijeoejaedia',
    image: 'https://lh6.googleusercontent.com/DLaZDFm1ocpFFLiiDMD0uBp1w7vgPRt8xx211wnZXFUOloEBuE-GC9Qw9hVPn5QQtVZjTHv0Vd8=s128-h128-e365',
    version: '7',
    price: '$0',
    priceCurrency: 'USD',
    interactionCount: { UserDownloads: 10 },
    ratingValue: 4.611226400769348,
    id: 'pjkljhegncpnkpknbcohdijeoejaedia'
},
```

Use `chrome-web-store` in the URL, `chrome web store` in the label. d22921be19d4711a8924485b584cc540db7fc87c

**Comment by espadrine** [comment]
Thanks! Keep me posted on what comes out of the chromium-apps discussion!

**Comment by sanemat** [comment]
This has no future.

**Pull request closed without merging**
