### PR TITLE
Move legacy services from server.js into services/

### PR DESCRIPTION
**Pull request by paulmelnikow**
This builds on the work of #1931 by moving the legacy services into `services/`. I haven't gotten through all of them yet, though I figure I should try to wrap them up in the next day or so and get this merged to avoid conflicts.

It would be great to get #1922 merged first, though if it can't be, it's not a huge deal.

I suggest we test this through the review app, and also by running all the service tests. Probably some of them will fail because they can be flaky, though if any of them crash, well then we'll know there's a problem that needs fixing. 😀 

There's a risk that this forklifting will break something, though the risk of catching it is relatively high because we're not moving any badge examples nor tests.

### CODE REVIEW

**Comment by paulmelnikow** [comment]
In about one hour, I got 18% of the way through the service code.

**Comment by paulmelnikow** [comment]
These are all moved! I left behind PyPI and CircleCI which were in flight at the time I started this.

#1931 gives a good overview of the change. It's probably worth clicking on a few commits, to get a sense of what I've done, though I guess I'm asking you to trust that I did this very carefully. I don't really expect anyone to comb through the entire diff.

The unit tests are passing now. I'll run the service tests when I get settled and look for crashes. If they pass, I'm as confident as I can be that this is working.

**Comment by paulmelnikow** [comment]
Here is the result of running the service tests:

<details>

```
  942 passing (6m)
  39 failing

  1) Bower
       pre version
         
	[ GET /vpre/bootstrap.json ]:
     Error: Request timed out after 5000 ms
      at Timeout.handleRequestTimeout [as _onTimeout] (node_modules/icedfrisby/lib/icedfrisby.js:1098:35)

  2) Bower
       Version for Invaild Package
         
	[ GET /v/it-is-a-invalid-package-should-error.json ]:
     Error: Request timed out after 5000 ms
      at Timeout.handleRequestTimeout [as _onTimeout] (node_modules/icedfrisby/lib/icedfrisby.js:1098:35)

  3) ELM PACKAGE
       gets the package version of elm-lang/core
         
	[ GET /v/elm-lang/core.json ]:
     ValidationError: child "value" fails because ["value" with value "invalid" fails to match the required pattern: /\bv?(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:-[\da-z-]+(?:\.[\da-z-]+)*)?(?:\+[\da-z-]+(?:\.[\da-z-]+)*)?\b/i]
      at Object.exports.process (node_modules/joi/lib/errors.js:196:19)
      at internals.Object._validateWithOptions (node_modules/joi/lib/types/any/index.js:675:31)
      at module.exports.internals.Any.root.validate (node_modules/joi/lib/index.js:138:23)
      at Object.pathMatch.matchJSONTypes (node_modules/icedfrisby/lib/pathMatch.js:303:9)
      at _expect (node_modules/icedfrisby/lib/icedfrisby.js:563:10)
      at IcedFrisbyNock._invokeExpects (node_modules/icedfrisby/lib/icedfrisby.js:1261:26)
      at start (node_modules/icedfrisby/lib/icedfrisby.js:1244:12)
      at Request.runCallback [as _callback] (node_modules/icedfrisby/lib/icedfrisby.js:1131:16)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.EventEmitter.emit (domain.js:442:20)
      at Request.<anonymous> (node_modules/request/request.js:1161:10)
      at Request.EventEmitter.emit (domain.js:442:20)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)
      at IncomingMessage.EventEmitter.emit (domain.js:442:20)
      at endReadableNT (_stream_readable.js:1081:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)

  4) Github
       GitHub open issues by multi-word label is > zero
         
	[ GET /issues/Cockatrice/Cockatrice/App%20-%20Cockatrice.json ]:
     Error: Request timed out after 5000 ms
      at Timeout.handleRequestTimeout [as _onTimeout] (node_modules/icedfrisby/lib/icedfrisby.js:1098:35)

  5) Github
       GitHub open issues by label (raw)
         
	[ GET /issues-raw/badges/shields/service-badge.json ]:
     Error: Request timed out after 5000 ms
      at Timeout.handleRequestTimeout [as _onTimeout] (node_modules/icedfrisby/lib/icedfrisby.js:1098:35)

  6) Github
       GitHub open issues by label including slash charactr (raw)
         
	[ GET /issues-raw/IgorNovozhilov/ndk/@ndk/cfg.json ]:
     Error: Request timed out after 5000 ms
      at Timeout.handleRequestTimeout [as _onTimeout] (node_modules/icedfrisby/lib/icedfrisby.js:1098:35)

  7) Github
       GitHub open issues (repo not found)
         
	[ GET /issues-raw/badges/helmets.json ]:
     Error: Request timed out after 5000 ms
      at Timeout.handleRequestTimeout [as _onTimeout] (node_modules/icedfrisby/lib/icedfrisby.js:1098:35)

  8) Github
       GitHub open pull requests by label
         
	[ GET /issues-pr/badges/shields/service-badge.json ]:
     Error: Request timed out after 5000 ms
      at Timeout.handleRequestTimeout [as _onTimeout] (node_modules/icedfrisby/lib/icedfrisby.js:1098:35)

  9) Github
       GitHub open pull requests by label (raw)
         
	[ GET /issues-pr-raw/badges/shields/service-badge.json ]:
     Error: Request timed out after 5000 ms
      at Timeout.handleRequestTimeout [as _onTimeout] (node_modules/icedfrisby/lib/icedfrisby.js:1098:35)

  10) Github
       hit counter
         
	[ GET /search/torvalds/linux/goto.json ]:
     Error: Request timed out after 8000 ms
      at Timeout.handleRequestTimeout [as _onTimeout] (node_modules/icedfrisby/lib/icedfrisby.js:1098:35)

  11) Github
       hit counter for nonexistent repo
         
	[ GET /search/torvalds/not-linux/goto.json ]:
     Error: Request timed out after 8000 ms
      at Timeout.handleRequestTimeout [as _onTimeout] (node_modules/icedfrisby/lib/icedfrisby.js:1098:35)

  12) Github
       github issue update
         
	[ GET /issues/detail/last-update/badges/shields/979.json ]:
     Error: Request timed out after 5000 ms
      at Timeout.handleRequestTimeout [as _onTimeout] (node_modules/icedfrisby/lib/icedfrisby.js:1098:35)

  13) Github
       github pull request check state
         
	[ GET /status/s/pulls/badges/shields/1110.json ]:
     Error: Request timed out after 5000 ms
      at Timeout.handleRequestTimeout [as _onTimeout] (node_modules/icedfrisby/lib/icedfrisby.js:1098:35)

  14) Github
       github pull request check state (pull request not found)
         
	[ GET /status/s/pulls/badges/shields/5110.json ]:
     Error: Request timed out after 5000 ms
      at Timeout.handleRequestTimeout [as _onTimeout] (node_modules/icedfrisby/lib/icedfrisby.js:1098:35)

  15) Github
       github pull request check contexts
         
	[ GET /status/contexts/pulls/badges/shields/1110.json ]:
     Error: Request timed out after 5000 ms
      at Timeout.handleRequestTimeout [as _onTimeout] (node_modules/icedfrisby/lib/icedfrisby.js:1098:35)

  16) Github
       top language
         
	[ GET /languages/top/badges/shields.json ]:
     Error: Request timed out after 5000 ms
      at Timeout.handleRequestTimeout [as _onTimeout] (node_modules/icedfrisby/lib/icedfrisby.js:1098:35)

  17) Github
       top language with empty repository
         
	[ GET /languages/top/pyvesb/emptyrepo.json ]:
     Error: Request timed out after 5000 ms
      at Timeout.handleRequestTimeout [as _onTimeout] (node_modules/icedfrisby/lib/icedfrisby.js:1098:35)

  18) Github
       language count
         
	[ GET /languages/count/badges/shields.json ]:
     Error: Request timed out after 5000 ms
      at Timeout.handleRequestTimeout [as _onTimeout] (node_modules/icedfrisby/lib/icedfrisby.js:1098:35)

  19) Github
       language count (repo not found)
         
	[ GET /languages/count/badges/helmets.json ]:
     Error: Request timed out after 5000 ms
      at Timeout.handleRequestTimeout [as _onTimeout] (node_modules/icedfrisby/lib/icedfrisby.js:1098:35)

  20) Github
       code size in bytes for all languages
         
	[ GET /languages/code-size/badges/shields.json ]:
     Error: Request timed out after 5000 ms
      at Timeout.handleRequestTimeout [as _onTimeout] (node_modules/icedfrisby/lib/icedfrisby.js:1098:35)

  21) Github
       repository size
         
	[ GET /repo-size/badges/shields.json ]:
     Error: Request timed out after 5000 ms
      at Timeout.handleRequestTimeout [as _onTimeout] (node_modules/icedfrisby/lib/icedfrisby.js:1098:35)

  22) Github
       repository size (repo not found)
         
	[ GET /repo-size/badges/helmets.json ]:
     Error: Request timed out after 5000 ms
      at Timeout.handleRequestTimeout [as _onTimeout] (node_modules/icedfrisby/lib/icedfrisby.js:1098:35)

  23) Github
       commit status - commit in branch
         
	[ GET /commit-status/badges/shields/master/5d4ab86b1b5ddfb3c4a70a70bd19932c52603b8c.json?style=_shields_test ]:
     Error: Request timed out after 5000 ms
      at Timeout.handleRequestTimeout [as _onTimeout] (node_modules/icedfrisby/lib/icedfrisby.js:1098:35)

  24) Github
       commit status - commit not in branch
         
	[ GET /commit-status/badges/shields/master/960c5bf72d7d1539fcd453343eed3f8617427a41.json?style=_shields_test ]:
     Error: Request timed out after 5000 ms
      at Timeout.handleRequestTimeout [as _onTimeout] (node_modules/icedfrisby/lib/icedfrisby.js:1098:35)

  25) Github
       commit status - unknown commit id
         
	[ GET /commit-status/atom/atom/v1.27.1/7dfb45eb61a48a4ce18a0dd2e31f944ed4467ae3.json?style=_shields_test ]:
     Error: Request timed out after 5000 ms
      at Timeout.handleRequestTimeout [as _onTimeout] (node_modules/icedfrisby/lib/icedfrisby.js:1098:35)

  26) Github
       commit status - unknown branch
         
	[ GET /commit-status/badges/shields/this-branch-does-not-exist/b551a3a8daf1c48dba32a3eab1edf99b10c28863.json?style=_shields_test ]:
     Error: Request timed out after 5000 ms
      at Timeout.handleRequestTimeout [as _onTimeout] (node_modules/icedfrisby/lib/icedfrisby.js:1098:35)

  27) Github
       commit status - no common ancestor between commit and branch
         
	[ GET /commit-status/badges/shields/master/b551a3a8daf1c48dba32a3eab1edf99b10c28863.json?style=_shields_test ]:
     Error: Request timed out after 5000 ms
      at Timeout.handleRequestTimeout [as _onTimeout] (node_modules/icedfrisby/lib/icedfrisby.js:1098:35)

  28) LibrariesIoDependents
       dependent count
         
	[ GET /npm/got.json ]:
     Error: Request timed out after 5000 ms
      at Timeout.handleRequestTimeout [as _onTimeout] (node_modules/icedfrisby/lib/icedfrisby.js:1098:35)

  29) MicroBadger
       layers with a specified tag
         
	[ GET /layers/_/httpd/alpine.json ]:
     Error: Request timed out after 5000 ms
      at Timeout.handleRequestTimeout [as _onTimeout] (node_modules/icedfrisby/lib/icedfrisby.js:1098:35)

  30) PHP version from PHP-Eye
       gets the package version of symfony
         
	[ GET /symfony/symfony.json ]:
     Error: Request timed out after 5000 ms
      at Timeout.handleRequestTimeout [as _onTimeout] (node_modules/icedfrisby/lib/icedfrisby.js:1098:35)

  31) PHP version from PHP-Eye
       gets the package version of symfony 2.8
         
	[ GET /symfony/symfony/v2.8.0.json ]:
     Error: Request timed out after 5000 ms
      at Timeout.handleRequestTimeout [as _onTimeout] (node_modules/icedfrisby/lib/icedfrisby.js:1098:35)

  32) PHP version from PHP-Eye
       gets the package version of yii
         
	[ GET /yiisoft/yii.json ]:
     Error: Request timed out after 5000 ms
      at Timeout.handleRequestTimeout [as _onTimeout] (node_modules/icedfrisby/lib/icedfrisby.js:1098:35)

  33) PHP version from PHP-Eye
       invalid package name
         
	[ GET /frodo/is-not-a-package.json ]:
     Error: Request timed out after 5000 ms
      at Timeout.handleRequestTimeout [as _onTimeout] (node_modules/icedfrisby/lib/icedfrisby.js:1098:35)

  34) suggest
       issues, forks, stars and twitter
         
	[ GET /v1?url=https%3A%2F%2Fgithub.com%2Fatom%2Fatom ]:
     Error: Request timed out after 5000 ms
      at Timeout.handleRequestTimeout [as _onTimeout] (node_modules/icedfrisby/lib/icedfrisby.js:1098:35)

  35) suggest
       license
         
	[ GET /v1?url=https%3A%2F%2Fgithub.com%2Fatom%2Fatom ]:
     Error: Request timed out after 5000 ms
      at Timeout.handleRequestTimeout [as _onTimeout] (node_modules/icedfrisby/lib/icedfrisby.js:1098:35)

  36) Travis CI/PHP version from .travis.yml
       gets the package version of symfony
         
	[ GET /php-v/symfony/symfony.json ]:
     ValidationError: child "name" fails because ["name" must be one of [PHP]]
      at Object.exports.process (node_modules/joi/lib/errors.js:196:19)
      at internals.Object._validateWithOptions (node_modules/joi/lib/types/any/index.js:675:31)
      at module.exports.internals.Any.root.validate (node_modules/joi/lib/index.js:138:23)
      at Object.pathMatch.matchJSONTypes (node_modules/icedfrisby/lib/pathMatch.js:303:9)
      at _expect (node_modules/icedfrisby/lib/icedfrisby.js:563:10)
      at IcedFrisbyNock._invokeExpects (node_modules/icedfrisby/lib/icedfrisby.js:1261:26)
      at start (node_modules/icedfrisby/lib/icedfrisby.js:1244:12)
      at Request.runCallback [as _callback] (node_modules/icedfrisby/lib/icedfrisby.js:1131:16)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.EventEmitter.emit (domain.js:442:20)
      at Request.<anonymous> (node_modules/request/request.js:1161:10)
      at Request.EventEmitter.emit (domain.js:442:20)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)
      at IncomingMessage.EventEmitter.emit (domain.js:442:20)
      at endReadableNT (_stream_readable.js:1081:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)

  37) Travis CI/PHP version from .travis.yml
       gets the package version of symfony 2.8
         
	[ GET /php-v/symfony/symfony/2.8.json ]:
     ValidationError: child "name" fails because ["name" must be one of [PHP]]
      at Object.exports.process (node_modules/joi/lib/errors.js:196:19)
      at internals.Object._validateWithOptions (node_modules/joi/lib/types/any/index.js:675:31)
      at module.exports.internals.Any.root.validate (node_modules/joi/lib/index.js:138:23)
      at Object.pathMatch.matchJSONTypes (node_modules/icedfrisby/lib/pathMatch.js:303:9)
      at _expect (node_modules/icedfrisby/lib/icedfrisby.js:563:10)
      at IcedFrisbyNock._invokeExpects (node_modules/icedfrisby/lib/icedfrisby.js:1261:26)
      at start (node_modules/icedfrisby/lib/icedfrisby.js:1244:12)
      at Request.runCallback [as _callback] (node_modules/icedfrisby/lib/icedfrisby.js:1131:16)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.EventEmitter.emit (domain.js:442:20)
      at Request.<anonymous> (node_modules/request/request.js:1161:10)
      at Request.EventEmitter.emit (domain.js:442:20)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)
      at IncomingMessage.EventEmitter.emit (domain.js:442:20)
      at endReadableNT (_stream_readable.js:1081:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)

  38) Travis CI/PHP version from .travis.yml
       gets the package version of yii
         
	[ GET /php-v/yiisoft/yii.json ]:
     ValidationError: child "name" fails because ["name" must be one of [PHP]]
      at Object.exports.process (node_modules/joi/lib/errors.js:196:19)
      at internals.Object._validateWithOptions (node_modules/joi/lib/types/any/index.js:675:31)
      at module.exports.internals.Any.root.validate (node_modules/joi/lib/index.js:138:23)
      at Object.pathMatch.matchJSONTypes (node_modules/icedfrisby/lib/pathMatch.js:303:9)
      at _expect (node_modules/icedfrisby/lib/icedfrisby.js:563:10)
      at IcedFrisbyNock._invokeExpects (node_modules/icedfrisby/lib/icedfrisby.js:1261:26)
      at start (node_modules/icedfrisby/lib/icedfrisby.js:1244:12)
      at Request.runCallback [as _callback] (node_modules/icedfrisby/lib/icedfrisby.js:1131:16)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.EventEmitter.emit (domain.js:442:20)
      at Request.<anonymous> (node_modules/request/request.js:1161:10)
      at Request.EventEmitter.emit (domain.js:442:20)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)
      at IncomingMessage.EventEmitter.emit (domain.js:442:20)
      at endReadableNT (_stream_readable.js:1081:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)

  39) Travis CI/PHP version from .travis.yml
       invalid package name
         
	[ GET /php-v/frodo/is-not-a-package.json ]:

      AssertionError: expected { name: 'build', value: 'unknown' } to deeply equal { name: 'PHP', value: 'invalid' }
      + expected - actual

       {
      -  "name": "build"
      -  "value": "unknown"
      +  "name": "PHP"
      +  "value": "invalid"
       }
      
      at Object.pathMatch.matchJSON (node_modules/icedfrisby/lib/pathMatch.js:138:38)
      at _expect (node_modules/icedfrisby/lib/icedfrisby.js:583:10)
      at IcedFrisbyNock._invokeExpects (node_modules/icedfrisby/lib/icedfrisby.js:1261:26)
      at start (node_modules/icedfrisby/lib/icedfrisby.js:1244:12)
      at Request.runCallback [as _callback] (node_modules/icedfrisby/lib/icedfrisby.js:1131:16)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.EventEmitter.emit (domain.js:442:20)
      at Request.<anonymous> (node_modules/request/request.js:1161:10)
      at Request.EventEmitter.emit (domain.js:442:20)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)
      at IncomingMessage.EventEmitter.emit (domain.js:442:20)
      at endReadableNT (_stream_readable.js:1081:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
```

</details>

**Comment by paulmelnikow** [comment]
All of these are timeouts, save two.

1. The travis/php-v tests. These are failing because the loading order of services has changed, and now they're getting picked up by the travis build regex. That regex needs to be modified so it excludes `travis/php-v`.
2. The Elm badge, which is broken in master: see #1979.

There may be others which have broken due to regex changing; I think I will run through the examples on a review app + on staging to see if that picks up any others.

**Comment by paulmelnikow** [comment]
> The next step would probably be to deploy the review app, and have the current homepage on the left side of a screen and the review homepage on the right side, and scroll through to see if there are any unexpected differences between the examples.

I ran through this very exercise on the review app vs staging, and everything looked identical. :+1:

I’d be curious about memory usage too. I wish we could see those stats!

Yea, I think it’s time to start pointing people to the new-style services. We could superficially update the tutorial for registerLegacyRouteHandler, though it probably makes more sense to put the time into rewriting it for new-style services.

**Comment by paulmelnikow** [comment]
@tooomm the formatting in https://github.com/badges/shields/pull/1958#issuecomment-415484265 is looking nice!

@PyvesB Looks like this will need another 👍post-conflict-resolution.

**Comment by tooomm** [comment]
@paulmelnikow Yes indeed, I like it! Will consider further tweaks like line break changes, though.

**Comment by chris48s** [comment]
Just catching up after a few days away

> We could superficially update the tutorial for registerLegacyRouteHandler, though it probably makes more sense to put the time into rewriting it for new-style services.

:+1: I totally agree we should update the tutorial and test docs for the new service arch now. I'm happy to take a first bash at this over the next few days. I've raised #1984 and assigned myself. If anyone else is already working on it or itching to get started, post there so we can co-ordinate.

**Comment by paulmelnikow** [comment]
Even though I tested this on the review app using the method described at https://github.com/badges/shields/pull/1958#pullrequestreview-149661148 described, I'll test it again before deploying it.

Given the regex issue described in https://github.com/badges/shields/pull/1958#issuecomment-416067965 and fixed in bcf53fb4a68699483dbf2ca61d61f85370f70e29, it seems likely that another badge may have broken along the way that may not be caught by that test.

If it does, we'll just have to find out, and then fix it!

**Pull request merged**
