### PR TITLE
upgrade to got 11; test on [github]

### PR DESCRIPTION
**Pull request by chris48s**
..just because it was mostly already done

### CODE REVIEW

**Comment by calebcartwright** [comment]
Anyone else seeing this on some of these PRs where the update button is just missing?

image

**Comment by chris48s** [comment]
nope

Screenshot at 2020-05-02 17-24-48

**Comment by calebcartwright** [comment]
I'm only seeing it on a couple of PRs coming from your fork, but it's there on others :thinking: 

odd :man_shrugging:

**Comment by paulmelnikow** [comment]
Yea, I'm seeing it too on PR's on Chris's fork. Maybe the checkbox "let maintainers edit" is unchecked?

**Comment by chris48s** [comment]
I've not been knowingly un-ticking it..
I just submitted https://github.com/badges/shields/pull/5037 and made sure "allow edits by maintainers" is _definitely_ ticked when I submitted it. Have a look at that one..

**Comment by calebcartwright** [comment]
Working on #5037 :+1: 

image

**Pull request merged**
