### PR TITLE
Add Dockerhub automated build integration #866

### PR DESCRIPTION
**Pull request by niccokunzmann**
As stated in issue #866 I want to be able to have a badge which shows the dockerhub build status.

### CODE REVIEW

**Comment by eddiewebb** [comment]
Is this duplicate of #856

**Comment by paulmelnikow** [comment]
Thanks for this PR. It does look like it overlaps with #856.

I like your the way this handles the 404 / not found case.

Could you add that to your branch for #856 @eddiewebb?

The tag build feature would be a great addition, but unfortunately we can't have a badge that is "unbounded" in time or number of requests. To support the tag feature, we'd need them to add an API that allows accessing this information more directly.

Also related: #886 #241

**Comment by eddiewebb** [comment]
@paulmelnikow  added to #856, but checking for 404 which works for both invalid user and invalid repo (some reason docker hub returns valid JSON with invalid repo, but a html page for invalid user.

**Comment by eddiewebb** [comment]
agree on busy, new look just committed.
screen shot 2017-04-06 at 11 14 14 am

**Comment by paulmelnikow** [comment]
Since this will need to be reworked, and we're tracking that in #935, I'll close this.

**Pull request closed without merging**
