### PR TITLE
[SonarQube] Support alert_status measure aka Quality gate

### PR DESCRIPTION
**Pull request by kakawait**
`alert_status` measure aka *Quality gate* is great metrics from sonar to determine if code is valid regarding its quality.

Use `?label=quality%20gate` if you need to change label name

### CODE REVIEW

**Comment by paulmelnikow** [comment]
I can't test this, because it seems to depend on #931, or something like it, being merged first.

**Comment by paulmelnikow** [comment]
Closing for inactivity. If you're reading this and want this implemented, don't be discouraged. You can grab the commits from the pull request branch using `git fetch origin pull/931/head:pr-931`, address the comments, and reopen.

**Comment by paulmelnikow** [comment]
@RedSparr0w Do you want to look at this too?

**Comment by RedSparr0w** [comment]
Yeah i should be able to check this out later next week.

**Pull request closed without merging**
