### PR TITLE
When configured, require requests to come from Cloudflare

### PR DESCRIPTION
**Pull request by paulmelnikow**
This is the code part of #3027, following [this article](https://www.viget.com/articles/heroku-cloudflare-the-right-way/) and using [this middleware](https://github.com/clive-io/cloudflare-middleware).

I pulled in the `addHandlerAtIndex()` function @chris48s wrote for #5574.

The middleware isn't perfect for scoutcamp, since it relies on `req.ip` which is something set by Express. However, the other solutions I found were either explicitly deprecated ([cloudflare-ip](https://www.npmjs.com/package/cloudflare-ip)) or relied on dynamically fetching the list of Cloudflare hosts ([cloudflare-ips](https://www.npmjs.com/package/cloudflare-ips)), which seems unnecessary as this list has not changed in several years.

If folks prefer, we could also adapt the code from `cloudflare-middleware` and/or create our own package that does exactly what we want, rather than depend on it. I opened one downstream PR to check that the ranges are still up to date (they are) though I'm not sure if the author will be responsive to us.

I've left this off to start, so we can test it in production using an env var before we make it the production default.

Looking forward to feedback on this approach!

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Opened #5667 to fix this Danger error.

**Comment by calebcartwright** [comment]
> The middleware isn't perfect for scoutcamp, since it relies on `req.ip` which is something set by Express. However, the other solutions I found were either explicitly deprecated ([cloudflare-ip](https://www.npmjs.com/package/cloudflare-ip)) or relied on dynamically fetching the list of Cloudflare hosts ([cloudflare-ips](https://www.npmjs.com/package/cloudflare-ips)), which seems unnecessary as this list has not changed in several years.
> 
> If folks prefer, we could also adapt the code from `cloudflare-middleware` and/or create our own package that does exactly what we want, rather than depend on it. I opened one downstream PR to check that the ranges are still up to date (they are) though I'm not sure if the author will be responsive to us.

Seems straightforward enough, even with the extra handler step. Also seems sufficiently small/simple that I'd be comfortable with pulling it in too

**Review by calebcartwright — APPROVED** [review]
LGTM

**Comment by paulmelnikow** [comment]
I'll probably merge this tomorrow, and maybe take it for a spin on non-peak Sunday time?

**Comment by calebcartwright** [comment]
> I'll probably merge this tomorrow, and maybe take it for a spin on non-peak Sunday time?

SGTM

**Review by calebcartwright — APPROVED** [review]

**Pull request merged**
