### PR TITLE
[Flathub]Add downloads badge

### LINKED ISSUE #5506: Badge request: Flathub downloads
:clipboard: **Description**

- Which service is this badge for e.g: GitHub, Travis CI
Flathub: https://flathub.org
- What sort of information should this badge show?
Download count of a particular package. Currently only a version badge is supported.

- Provide an example in plain text e.g: "version | v1.01" or as a static badge
(static badge generator can be found at https://shields.io)
<kbd>Flathub Downloads | 123.456</kbd>

:link: **Data**

Where can we get the data from?

There is all the data at https://flathub.org/stats/ in various json files.
This page uses the data already: https://klausenbusk.github.io/flathub-stats/

:microphone: **Motivation**

- What is the specific use case?

Showing useful download data like all time, recent month etc. as with other services.

### PR DESCRIPTION
**Pull request by JakobDev**
Closes #5506

### CODE REVIEW

**Comment by calebcartwright** [comment]
Thank you for the PR!

To avoid any bifurcation or loss of discussion for historical context, I'd recommend we first continue/resolve conversation back on the issue (especially the questions in https://github.com/badges/shields/issues/5506#issuecomment-1067129626) before diving to deeply into the proposed implementation

**Comment by calebcartwright** [comment]
This was closed by mistake due to a typo in an unrelated commit message, reopening

**Comment by calebcartwright** [comment]
In a holding pattern for now as the upstream service maintainers have stated they'd like to modify the API response before we start consuming

**Comment by JakobDev** [comment]
@calebcartwright flathub/website#67 has now been merged. I had updated my PR. This PR is now ready to merge.

**Review by chris48s — APPROVED** [review]

**Comment by chris48s** [comment]
I think this one is good to go. I'll leave it open in cast @calebcartwright wants to chime in before we merge but LGTM

**Review by calebcartwright — APPROVED** [review]

**Pull request merged**
