### PR TITLE
add badges for github last commit date and commit freq

### PR DESCRIPTION
**Pull request by mskonovalov**
Created bages for
Need badges for Github Repo Code frequency or status 
#897

1) latest commit date
image
image
image
image

2) commits amount for week/month/year
image

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Hi, thanks for your contribution.

The last commit badge is very clear.

I'm not as clear about the frequency badge. When it says "commits | 6k/year", what does that mean?

**Comment by mskonovalov** [comment]
It's just amount of commits for last 52 weeks.
Unfortunately API doesn't provide enough features.

**Comment by mskonovalov** [comment]
I can add something like "average amount of commits per week for last 52 weeks"

**Comment by mskonovalov** [comment]
ups, accidentally closed

**Comment by paulmelnikow** [comment]
I'm working on a branch for this. I'll open a new pull request when it's ready.

**Comment by MarkoPaul0** [comment]
The badge for the last commit is stuck on displaying "last Friday" even though I've made commits every day since. Has anyone run into that issue before? (Note that I set the HTTP cache to 3600 sec to no avail)

**Comment by platan** [comment]
@MarkoPaul0 Could you provide an example (a repo name)?

**Comment by MarkoPaul0** [comment]
@platan, [sure thing](https://github.com/MarkoPaul0/WireBait)

**Comment by platan** [comment]
@MarkoPaul0 please look at you README source https://raw.githubusercontent.com/MarkoPaul0/WireBait/826e910ef1d869108e87ea27ed7cf0495614d061/README.md
It contains https://img.shields.io/github/last-commit/google/skia.svg?maxAge=3600, not https://img.shields.io/github/last-commit/MarkoPaul0/WireBait.svg

**Comment by MarkoPaul0** [comment]
Wow I feel really dumb for missing that in the doc. Thanks again @platan!

**Pull request closed without merging**
