### PR TITLE
Fix [suggest]

### PR DESCRIPTION
**Pull request by paulmelnikow**
Ref https://github.com/badges/shields/issues/2420#issuecomment-450400904

### CODE REVIEW

**Comment by techtonik** [comment]
Is it possible to have a smoke test for this functionality?

**Comment by paulmelnikow** [comment]
It gets tested as part of the service test run. The test was failing, but hadn’t been picked up on yet.

**Comment by techtonik** [comment]
I don't see any failures in https://github.com/badges/shields/commits/master - is service test run is a manual process?

**Comment by techtonik** [comment]
> We can’t run all the tests on every commit

Why? It is only 4 minutes in the daily log.

**Comment by paulmelnikow** [comment]
Our PR build runs in about 20 seconds; 4 minutes is much too slow. The other issue is that the service tests rely on external services. #927 is the discussion about that. We used to run the full suite on every commit to master, but stopped because they often fail for reasons outside our control. The thing we could use more help with is keeping up with fixing the failures identified tests (i.e. #1359).

**Pull request merged**
