### PR TITLE
GitHub Standards integration + linkable templates

### PR DESCRIPTION
**Pull request by leog**
This corresponds to the planned GitHub Standards badges discussed here https://github.com/standards/meta/issues/1

For more information about GitHub Standards, please visit https://github.com/standards/meta

### CODE REVIEW

**Comment by leog** [comment]
PTAL @espadrine

**Comment by leog** [comment]
any word on this @espadrine? launching @standards now, would be great to have this.

**Comment by paulmelnikow** [comment]
Hi @leog, thanks for this contribution. I recently joined this project, and would like to find a way to accommodate yours.

This is a significant change, so it's going to take me a little while to digest. Wanted to let you know it was received!

**Comment by paulmelnikow** [comment]
Possibly related: #598

**Comment by paulmelnikow** [comment]
#589 has been closed in favor of #1079, to discuss linking in templates.

**Comment by paulmelnikow** [comment]
@leog Would you be up for pulling the badge change into a new branch and adding a test? I'd like to get that merged.

@RedSparr0w, you've been doing a lot of work on the templates, and you're much more knowledgeable about how the badges behave in different browsers. Would you be up for taking a look at the linking part of this in relation to the discussions in #1079 and #598?

**Comment by leog** [comment]
@paulmelnikow sure, I can do that, and hopefully, then you can consider merging this PR which I need to modify to remove the linkable stuff 👍

**Comment by paulmelnikow** [comment]
Sure, if you'd prefer to update this one that is totally fine! Would like to get it merged.

Thanks for your patience btw! This project is complicated and had quite a learning curve. 😉 

And yes, it looks like linkable templates will be taken care of in #1172.

**Comment by leog** [comment]
@paulmelnikow oh ok, so I I'll need to wait for that PR to use that implementation of linkable templates.

Thank you for taking care of the project and already making progress on resolving issues. Count on me to help with anything 👍

**Comment by paulmelnikow** [comment]
#1172 is merged!

**Comment by paulmelnikow** [comment]
Hey, just wanted to follow up! Are you up for updating this PR (or opening a new one)?

**Comment by paulmelnikow** [comment]
Hey @leog, wanna just reopen this when you're ready?

**Comment by leog** [comment]
Sorry @paulmelnikow, I've been swamped. Will do, thanks.

**Pull request closed without merging**
