### PR TITLE
Bump simple-icons from 1.19.0 to 1.19.1

### PR DESCRIPTION
**Pull request by ljvmiranda921**
The latest release contains a handful of icons that are widely used in the industry, namely: C, arxiv, Notion, Zoom, etc.

### CODE REVIEW

**Comment by calebcartwright** [comment]
Not sure why all the CI checks failed 🤷‍♂ Let me restart them

**Comment by calebcartwright** [comment]
Ah I see, can you bump the lockfile too?

**Comment by ljvmiranda921** [comment]
Hello @calebcartwright ! Ok let me do that!

**Comment by ljvmiranda921** [comment]
Hi @calebcartwright done!

**Pull request merged**
